import assert from 'node:assert/strict';
import {CommandRegistry} from '../../../dist/foundation/models.js';
import {AnalyticalCompareOwner} from '../../../dist/foundation/analytical/compare.js';
import {RQDomainAdapter,RQ_PROVIDER_TRUTH} from '../../../dist/adapters/rq/domain.js';
import {bindRqSurface,projectRqWorkbench} from '../../../dist/surfaces/rq/surface.js';
const record=(revision,digest,value,extra={})=>({sourceId:'source-1',revision,digest,locator:`local://source-1/${revision}`,schemaVersion:'rq-source/1',comparable:{title:{label:'Title',type:'string',value}},provenanceRefs:[`rq:${revision}`],...extra});
const left=record('r1','sha-r1','Alpha');
const right=record('r2','sha-r2','Beta',{workingConflict:{classification:'WORKING_DIFFERENCE',rationale:'Analyst comparison only'}});
const ref=x=>({sourceId:x.sourceId,revision:x.revision,digest:x.digest,locator:x.locator});
const owner=()=>new AnalyticalCompareOwner();

assert.throws(()=>new RQDomainAdapter([left,right]),/RQ_SHARED_ANALYTICAL_COMPARE_OWNER_REQUIRED/);
assert.throws(()=>new RQDomainAdapter([left,right],{analyticalCompareOwner:{owner:'AnalyticalCompareOwner',ownerToken:'AnalyticalCompare'}}),/RQ_SHARED_ANALYTICAL_COMPARE_OWNER_REQUIRED/);
assert.throws(()=>new RQDomainAdapter([left,right],{analyticalCompareOwner:owner(),providerAdmitted:true,providerTestOnly:true}),/RQ_PROVIDER_TRUTH_CONTRADICTION/);
const normal=new RQDomainAdapter([left,right],{analyticalCompareOwner:owner()});
assert.equal(normal.descriptor().providerTruth,RQ_PROVIDER_TRUTH.UNAVAILABLE);
assert.equal(normal.descriptor().canonicalProductTruth,false);
assert.equal(normal.search('Alpha').status,'RQ_CURRENT_PROVIDER_UNAVAILABLE');
assert.equal(normal.compareAvailability({workingAnalysisId:'normal',scope:['claim'],left:ref(left),right:ref(right)}).code,'RQ_CURRENT_PROVIDER_UNAVAILABLE');
const normalProjection=projectRqWorkbench({adapter:normal,mode:'COMPARE',compareContext:{workingAnalysisId:'normal',scope:['claim'],left:ref(left),right:ref(right)}});
assert.equal(normalProjection.center.owner,'AnalyticalResearchWorkbench');
assert.equal(normalProjection.center.state,'UNAVAILABLE');
assert.match(normalProjection.center.emptyReason,/No fixture data has been substituted/);
assert.equal(normalProjection.visualAuthority.classification,'REVIEWED_FINAL_CANDIDATE');
assert.equal(normalProjection.visualAuthority.final,false);
assert.equal(normalProjection.bottom.localReplacement,false);
assert.equal(normalProjection.boundaries.formalEvidenceReview,'PROHIBITED');

const adapter=new RQDomainAdapter([left,right],{analyticalCompareOwner:owner(),providerTestOnly:true,providerClassification:'DS01_ACCEPTANCE_DATA__NON_CANONICAL'});
const descriptor=adapter.descriptor();
assert.equal(descriptor.providerTruth,RQ_PROVIDER_TRUTH.DS01_TEST_ONLY);
assert.equal(descriptor.providerAdmitted,false);
assert.equal(descriptor.providerTestOnly,true);
assert.equal(descriptor.canonicalProductTruth,false);
assert.equal(adapter.providerAvailability().code,'AVAILABLE_TEST_ONLY');
assert.equal(adapter.compareAvailability({workingAnalysisId:'s0',scope:['claim'],left:ref(left)}).code,'RQ_COMPARE_EXACT_SOURCE_REVISION_PAIR_REQUIRED');
assert.equal(adapter.compareAvailability({workingAnalysisId:'s0',left:ref(left),right:ref(right)}).code,'RQ_COMPARE_SCOPE_REQUIRED');
assert.equal(adapter.compareAvailability({scope:['claim'],left:ref(left),right:ref(right)}).code,'RQ_COMPARE_WORKING_ANALYSIS_CONTEXT_REQUIRED');
const valid={workingAnalysisId:'s1',scope:['claim:C-014','source:source-1'],left:ref(left),right:ref(right)};
assert.equal(adapter.compareAvailability(valid).code,'AVAILABLE_TEST_ONLY');
const result=adapter.compare(valid);
assert.equal(result.status,'DIFFERENT');
assert.equal(result.formalReview,false);
assert.equal(result.canonicalProductTruth,false);
assert.equal(result.providerTruth,RQ_PROVIDER_TRUTH.DS01_TEST_ONLY);
const review=adapter.review('s1',{conflict:{id:'c1',author:'analyst-1',revision:'w1',classification:'WORKING_DIFFERENCE',rationale:'Bounded analysis only'}});
assert.equal(review.status,'WORKING_REVIEW_ONLY');
assert.equal(review.reviewDecisionAuthority,false);
assert.equal(review.evidenceDecisionWrites,0);
assert.equal(review.workingConflict.formalReview,false);
const provenance=adapter.provenance('s1');
assert.equal(provenance.sourceAuthority,'DERIVED_ONLY');
assert.equal(provenance.originalHashAssertion,'FORBIDDEN_DERIVED_ONLY');
assert.equal(adapter.saveAnalysisSession('s1').status,'RQ_ANALYSIS_SESSION_PERSISTENCE_UNAVAILABLE');
assert.equal(adapter.saveAnalysisSession('s1').persisted,false);
const missing=adapter.compareAvailability({workingAnalysisId:'s2',scope:['claim'],left:ref(left),right:{sourceId:'missing',revision:'r1',digest:'x',locator:'local://missing'}});
assert.equal(missing.code,'RQ_COMPARE_RIGHT_MISSING');
const ds01Projection=projectRqWorkbench({adapter,mode:'COMPARE',selection:ref(left),compareContext:valid,bottomOpen:true});
assert.equal(ds01Projection.truth.epistemicState,'TEST_ONLY_AVAILABLE');
assert.equal(ds01Projection.truth.canonicalProductTruth,false);
assert.equal(ds01Projection.center.compare.enabled,true);
assert.equal(ds01Projection.center.compare.exactPairRequired,true);
assert.equal(ds01Projection.right.selectedSourceRevision.sourceId,'source-1');
assert.equal(ds01Projection.bottom.owner,'BottomDeepWorkCore');

const commands=new CommandRegistry();
const bound=bindRqSurface({commands,adapter,presentation:{mode:'COMPARE',selection:ref(left),compareContext:valid}});
assert.equal(bound.sharedFamilyOwner,'AnalyticalCompareOwner');
assert.equal(bound.providerTruth,RQ_PROVIDER_TRUTH.DS01_TEST_ONLY);
assert.equal(bound.canonicalProductTruth,false);
assert.equal(bound.formalReviewAuthority,false);
assert.equal(bound.workbench.center.owner,'AnalyticalResearchWorkbench');
assert.equal(bound.visualReferenceCeiling,'REVIEWED_FINAL_CANDIDATE');
assert.equal(commands.execute('rq.compare',{...valid,workingAnalysisId:'s3'}).status,'DIFFERENT');
console.log(JSON.stringify({surface:'rq',status:'PASS',cases:40,normalProviderTruth:RQ_PROVIDER_TRUTH.UNAVAILABLE,ds01ProviderTruth:RQ_PROVIDER_TRUTH.DS01_TEST_ONLY,persistence:'UNAVAILABLE',formalReviewAuthority:false,visualReferenceCeiling:'REVIEWED_FINAL_CANDIDATE'}));
