import assert from 'node:assert/strict';
import {CommandRegistry} from '../../../dist/foundation/models.js';
import {RQDomainAdapter} from '../../../dist/adapters/rq/domain.js';
import {bindRqSurface} from '../../../dist/surfaces/rq/surface.js';
const record=(revision,digest,value,extra={})=>({sourceId:'source-1',revision,digest,locator:`local://source-1/${revision}`,schemaVersion:'rq-source/1',comparable:{title:{label:'Title',type:'string',value}},provenanceRefs:[`rq:${revision}`],...extra});
const left=record('r1','sha-r1','Alpha');
const right=record('r2','sha-r2','Beta',{workingConflict:{classification:'WORKING_DIFFERENCE',rationale:'Analyst comparison only'}});
const adapter=new RQDomainAdapter([left,right]);
const commands=new CommandRegistry();bindRqSurface({commands,adapter});
const ref=x=>({sourceId:x.sourceId,revision:x.revision,digest:x.digest,locator:x.locator});
const result=commands.execute('rq.compare',{sessionId:'s1',left:ref(left),right:ref(right)});
assert.equal(result.status,'DIFFERENT');
assert.equal(result.formalReview,false);
assert.equal(adapter.review('s1').reviewDecisionAuthority,false);
assert.equal(adapter.saveAnalysisSession('s1').status,'RQ_ANALYSIS_SESSION_PERSISTENCE_UNAVAILABLE');
assert.equal(adapter.saveAnalysisSession('s1').persisted,false);
const missing=adapter.compareOwner.createPair({left:{providerId:adapter.providerId,ref:ref(left)},right:{providerId:adapter.providerId,ref:{sourceId:'missing',revision:'r1',digest:'x',locator:'local://missing'}}});
assert.equal(adapter.compareOwner.comparePair(missing).state,'MISSING_RIGHT');
let contradiction=false;try{adapter.compareOwner.createPair({left:{providerId:adapter.providerId,ref:{...ref(left),digest:''}},right:{providerId:adapter.providerId,ref:ref(right)}})}catch{contradiction=true}assert.equal(contradiction,true);
console.log(JSON.stringify({surface:'rq',status:'PASS',cases:8,persistence:'UNAVAILABLE',formalReviewAuthority:false}));
