import {DurableAuditRuntimeAdapter} from '../../../adapters/audit.js';
import {auditSharedOwnerBinding,projectAuditEventEntries} from '../../../surfaces/audit/index.js';

const assert=(value:any,message='assertion failed')=>{if(!value)throw Error(message)};
const run=async(name:string,fn:()=>any,out:any[])=>{try{await fn();out.push({name,status:'PASS'})}catch(error){out.push({name,status:'FAIL',error:String((error as any)?.message||error)})}};
const event=(sequence:number,eventId:string,previousHash='GENESIS',hash=`hash-${sequence}`)=>({schema:'CEP_AUDIT_EVENT_V1',sequence,eventId,occurredAt:`2026-09-26T0${sequence}:00:00.000Z`,actor:'auditor',action:`ACTION_${sequence}`,target:'audit',outcome:'OBSERVED',correlationId:`corr-${sequence}`,details:null,previousHash,hash});

class FakeTransport{
  calls:any[]=[];handlers:any;
  constructor(handlers:any={}){this.handlers=handlers;}
  async request(method:string,path:string,body?:any){this.calls.push({method,path,body});const key=Object.keys(this.handlers).find(item=>path.startsWith(item));const handler=key?this.handlers[key]:null;if(handler instanceof Error)throw handler;if(typeof handler==='function')return handler({method,path,body});return handler||{ok:false,code:'UNEXPECTED_REQUEST'};}
}

export async function runAuditMissionTests(){const tests:any[]=[];
  await run('audit.projection-preserves-canonical-provider-identity',()=>{const first=event(1,'evt-001','GENESIS','h1'),second=event(2,'evt-002','h1','h2'),rows=projectAuditEventEntries([first,second]);assert(rows[0].id==='evt-001');assert(rows[0].timestamp===first.occurredAt);assert(rows[0].attributes.recordHash==='h1');assert(rows[1].parentIds[0]==='evt-001');assert(rows[1].attributes.previousEventId==='evt-001');assert(rows[1].correlationIds[0]==='corr-2');assert(rows[1].attributes.providerSource==='AuditEventProvider');},tests);
  await run('audit.projection-rejects-synthetic-identity-repair',()=>{let rejected=false;try{projectAuditEventEntries([{...event(1,'evt-001'),eventId:''}])}catch(error){rejected=String((error as any)?.message||error).startsWith('AUDIT_EVENT_CANONICAL_PROJECTION_REQUIRED:')}assert(rejected,'missing canonical eventId must fail closed');},tests);
  await run('audit.search-truth-separates-observed-from-upstream-coverage',async()=>{const row=event(1,'evt-001'),transport=new FakeTransport({'/v1/audit/events':{ok:true,events:[row],pagination:{limit:100,cursor:null,nextCursor:null,returned:1},filters:{actor:null,action:null,target:null,outcome:null,correlationId:null,from:null,to:null},observedScope:{fromSequence:1,toSequence:1,count:1,watermarkHash:row.hash},historyMutated:false}}),adapter=new DurableAuditRuntimeAdapter({transport});await adapter.search({limit:100});const truth=adapter.truth();assert(truth.observedCoverage==='COMPLETE_OBSERVED');assert(truth.upstreamCoverage==='UNKNOWN');assert(truth.totalUpstreamKnown===false);assert(truth.zeroObservedProvesCompleteCoverage===false);},tests);
  await run('audit.zero-observed-never-claims-total-upstream-completeness',async()=>{const transport=new FakeTransport({'/v1/audit/events':{ok:true,events:[],pagination:{limit:100,cursor:null,nextCursor:null,returned:0},filters:{actor:null,action:null,target:null,outcome:null,correlationId:null,from:null,to:null},observedScope:{fromSequence:null,toSequence:null,count:0,watermarkHash:'GENESIS'},historyMutated:false}}),adapter=new DurableAuditRuntimeAdapter({transport});await adapter.search({limit:100});const truth=adapter.truth();assert(truth.eventCount===0&&truth.observedCoverage==='COMPLETE_OBSERVED'&&truth.upstreamCoverage==='UNKNOWN'&&truth.zeroObservedProvesCompleteCoverage===false);},tests);
  await run('audit.invalid-chain-surfaces-exact-first-invalid-sequence',async()=>{const transport=new FakeTransport({'/v1/audit/verify':{ok:true,valid:false,firstInvalidSequence:7,observedScope:{fromSequence:1,toSequence:9,count:9,watermarkHash:'h9'}}}),adapter=new DurableAuditRuntimeAdapter({transport});await adapter.verify();const state=adapter.snapshot();assert(state.integrity.status==='INVALID_CHAIN');assert(state.integrity.firstInvalidSequence===7);},tests);
  await run('audit.provider-verification-failure-is-verification-error',async()=>{let mode='valid';const transport=new FakeTransport({'/v1/audit/verify':()=>mode==='valid'?{ok:true,valid:true,firstInvalidSequence:null,observedScope:{fromSequence:1,toSequence:1,count:1,watermarkHash:'h1'}}:{ok:false,code:'AUDIT_STORAGE_CORRUPT'}}),adapter=new DurableAuditRuntimeAdapter({transport});await adapter.verify();assert(adapter.snapshot().integrity.status==='VALID_CHAIN');mode='error';await adapter.verify();const state=adapter.snapshot();assert(state.integrity.status==='VERIFICATION_ERROR');assert(state.integrity.firstInvalidSequence===null);assert(state.integrity.errorCode==='AUDIT_STORAGE_CORRUPT');},tests);
  await run('audit.provider-verification-exception-is-verification-error',async()=>{const transport=new FakeTransport({'/v1/audit/verify':new Error('provider offline')}),adapter=new DurableAuditRuntimeAdapter({transport});const result=await adapter.verify();assert(result.ok===false&&adapter.snapshot().integrity.status==='VERIFICATION_ERROR');},tests);
  await run('audit.search-error-remains-distinct-from-successful-verification',async()=>{const transport=new FakeTransport({'/v1/audit/events':{ok:false,code:'RUNTIME_UNAVAILABLE'},'/v1/audit/verify':{ok:true,valid:true,firstInvalidSequence:null,observedScope:{fromSequence:null,toSequence:null,count:0,watermarkHash:'GENESIS'}}}),adapter=new DurableAuditRuntimeAdapter({transport});await adapter.search({limit:100});await adapter.verify();const state=adapter.snapshot();assert(state.errors.search?.code==='RUNTIME_UNAVAILABLE');assert(state.integrity.status==='VALID_CHAIN');},tests);
  await run('audit.annotation-requires-canonical-event-id-not-sequence-or-hash',async()=>{const row=event(1,'evt-canonical','GENESIS','h1'),transport=new FakeTransport({'/v1/audit/events':{ok:true,events:[row],pagination:{limit:100,cursor:null,nextCursor:null,returned:1},filters:{},observedScope:{fromSequence:1,toSequence:1,count:1,watermarkHash:'h1'},historyMutated:false},'/v1/audit/annotations':({body}:any)=>({ok:true,annotation:{annotationId:'a1',eventId:body.eventId,revision:1,note:body.note,actor:body.actor,createdAt:'2026-09-26T02:00:00.000Z'}})}),adapter=new DurableAuditRuntimeAdapter({transport});await adapter.search({limit:100});const bySequence=await adapter.annotate({eventId:'1',note:'no'}),byHash=await adapter.annotate({eventId:'h1',note:'no'}),canonical=await adapter.annotate({eventId:'evt-canonical',note:'yes'});assert(bySequence.code==='AUDIT_CANONICAL_EVENT_ID_REQUIRED');assert(byHash.code==='AUDIT_CANONICAL_EVENT_ID_REQUIRED');assert(canonical.ok===true);assert(transport.calls.filter(call=>call.path==='/v1/audit/annotations').length===1);},tests);
  await run('audit.shared-analytical-compare-fails-closed-without-local-owner',()=>{const missing=auditSharedOwnerBinding(),bound=auditSharedOwnerBinding({analyticalCompareOwner:{owner:'AnalyticalCompareOwner'}});assert(missing.analyticalCompare.state==='UNAVAILABLE');assert(missing.analyticalCompare.fallbackConstructed===false);assert(missing.analyticalCompare.code==='CANONICAL_ANALYTICAL_COMPARE_OWNER_REQUIRED');assert(bound.analyticalCompare.state==='BOUND'&&bound.analyticalCompare.fallbackConstructed===false);},tests);
  return tests;
}

if(import.meta.url===new URL(process.argv[1],'file:').href){const tests=await runAuditMissionTests(),pass=tests.filter(test=>test.status==='PASS').length,fail=tests.length-pass;console.log(JSON.stringify({mission:'SWR-W05-AUDIT',pass,fail,tests},null,2));if(fail)process.exitCode=1;}
