import {ReleasesDomainAdapter} from '../../../adapters/releases/domain-adapter.js';
import {createReleasesSurfaceComposition} from '../../../surfaces/releases/composition.js';
import {describeContextProvider} from '../../../foundation/global/context-descriptor-contract.js';
const assert=(v:any,m='assertion failed')=>{if(!v)throw Error(m)};const run=(name:string,fn:()=>void,out:any[])=>{try{fn();out.push({name,status:'PASS'})}catch(e){out.push({name,status:'FAIL',error:String((e as any)?.message||e)})}};const h=(c:string)=>c.repeat(64);const candidate=(patch:any={})=>({candidateId:'cand-1',commitSHA:h('a'),treeSHA:h('b'),artifactDigest:h('c'),state:'TECHNICALLY_READY',evidenceDigest:h('d'),authorization:'NONE',deployment:'UNKNOWN',deploymentObservedAt:null,...patch});
export function runReleasesSurfaceTests(){const t:any[]=[];
 run('releases.empty-is-not-green-readiness',()=>{const a=new ReleasesDomainAdapter();const r=a.inspect();assert(!r.ok&&r.code==='NO_CANDIDATE')},t);
 run('releases.exact-candidate-identity-required',()=>{let failed=false;try{new ReleasesDomainAdapter({candidates:[candidate({commitSHA:'bad'})] as any})}catch{failed=true}assert(failed)},t);
 run('releases.authorization-is-not-deployment',()=>{const a=new ReleasesDomainAdapter({candidates:[candidate()],requester:{request:()=>({requestId:'auth-1',state:'REQUESTED'})}});a.select('cand-1');const r=a.requestAuthorization();assert(r.ok&&r.authorization==='REQUESTED'&&r.deployment==='UNKNOWN'&&r.executesDeployment===false)},t);
 run('releases.unavailable-auth-provider-does-not-request',()=>{const a=new ReleasesDomainAdapter({candidates:[candidate()]});a.select('cand-1');const r=a.requestAuthorization();assert(!r.ok&&r.code==='AUTHORIZATION_REQUEST_PROVIDER_UNAVAILABLE')},t);
 run('releases.unknown-deployment-stays-unknown',()=>{const a=new ReleasesDomainAdapter({candidates:[candidate()]});const r=a.inspect('cand-1');assert(r.ok&&r.candidate.deployment==='UNKNOWN'&&r.truth.unknownDeploymentRemainsUnknown)},t);
 run('releases.head-move-is-explicit-stale',()=>{const a=new ReleasesDomainAdapter({candidates:[candidate()]});a.select('cand-1');const r=a.compare({currentHeadCommitSHA:h('e')});assert(r.stale&&r.pinnedCommitSHA===h('a')&&!r.evidenceAttributionAllowed)},t);
 run('releases.plan-never-executes-deployment',()=>{const a=new ReleasesDomainAdapter({candidates:[candidate()]});const r=a.plan('cand-1');assert(r.ok&&r.executesDeployment===false)},t);
 run('releases.command-unavailable-emits-no-receipt',()=>{const c=createReleasesSurfaceComposition({adapter:new ReleasesDomainAdapter({candidates:[candidate()]})});c.adapter.select('cand-1');const before=c.commands.receipts.length;const r=c.commands.execute('releases.requestAuthorization',{});assert(r.ok===false&&c.commands.receipts.length===before)},t);
 run('releases.collection-is-shared-core-bound-domain-data',()=>{const c=createReleasesSurfaceComposition({adapter:new ReleasesDomainAdapter({candidates:[candidate()]})});assert(c.collection.snapshot().totalRows===1&&c.slots.LEFT==='collection')},t);
 run('releases.context-exact-candidate-descriptor-valid',()=>{const a=new ReleasesDomainAdapter({candidates:[candidate()]});a.select('cand-1');const c=createReleasesSurfaceComposition({adapter:a});const r=describeContextProvider(c.contextProvider,{id:'cand-1'});assert(r.ok&&r.descriptor.revisionToken===h('c'))},t);
 run('releases.deployment-execution-capability-not-owned',()=>{const c=createReleasesSurfaceComposition();assert(c.providerTruth.deploymentExecution==='NOT_OWNED')},t);
 run('releases.platform-truth-remains-unavailable-fallback',()=>{const c=createReleasesSurfaceComposition();assert(c.platformTruth.activeKeyboardSource.includes('UNAVAILABLE')&&c.platformTruth.nativeWindow.includes('UNAVAILABLE'))},t);
 return t;}
if(import.meta.url===new URL(process.argv[1],'file:').href){const tests=runReleasesSurfaceTests();console.log(JSON.stringify({surface:'releases',pass:tests.filter(x=>x.status==='PASS').length,fail:tests.filter(x=>x.status==='FAIL').length,tests},null,2));if(tests.some(x=>x.status==='FAIL'))process.exitCode=1;}
