import {SemanticCommandBus} from '../../../foundation/global/commands.js';
import {AnalyticalCompareOwner} from '../../../foundation/analytical/compare.js';
import {ReleasesDomainAdapter,type ReleaseCandidate} from '../../../adapters/releases/domain-adapter.js';
import {createReleasesSurfaceComposition} from '../../../surfaces/releases/composition.js';
import {describeContextProvider} from '../../../foundation/global/context-descriptor-contract.js';

const assert=(v:any,m='assertion failed')=>{if(!v)throw Error(m)};
const run=(name:string,fn:()=>void,out:any[])=>{try{fn();out.push({name,status:'PASS'})}catch(e){out.push({name,status:'FAIL',error:String((e as any)?.message||e)})}};
const h=(c:string)=>c.repeat(64);
const ref=(id='cand-1')=>({candidateId:id,commitSHA:h(id==='cand-1'?'a':'e'),treeSHA:h(id==='cand-1'?'b':'f'),artifactDigest:h(id==='cand-1'?'c':'1')});
const candidate=(patch:any={}):ReleaseCandidate=>({candidateId:'cand-1',commitSHA:h('a'),treeSHA:h('b'),artifactDigest:h('c'),state:'TECHNICALLY_READY',evidenceDigest:h('d'),authorization:'NONE',deployment:'UNKNOWN',deploymentObservedAt:null,...patch});

export function runReleasesSurfaceTests(){const t:any[]=[];
  run('releases.empty-is-not-green-readiness',()=>{const a=new ReleasesDomainAdapter();const r=a.inspect();assert(!r.ok&&r.code==='NO_CANDIDATE'&&r.dataCoverage==='DATA_COVERAGE_BLOCKER')},t);
  run('releases.exact-candidate-identity-required',()=>{let failed=false;try{new ReleasesDomainAdapter({candidates:[candidate({commitSHA:'bad'})] as any})}catch{failed=true}assert(failed)},t);
  run('releases.authorization-is-not-deployment',()=>{const a=new ReleasesDomainAdapter({candidates:[candidate()],requester:{request:()=>({requestId:'auth-1',state:'REQUESTED'})}});a.select('cand-1');const r=a.requestAuthorization();assert(r.ok&&r.authorization==='REQUESTED'&&r.deployment==='UNKNOWN'&&r.executesDeployment===false&&r.grantsDeploymentAuthorization===false)},t);
  run('releases.unavailable-auth-provider-does-not-request',()=>{const a=new ReleasesDomainAdapter({candidates:[candidate()]});a.select('cand-1');const r=a.requestAuthorization();assert(!r.ok&&r.code==='AUTHORIZATION_REQUEST_PROVIDER_UNAVAILABLE')},t);
  run('releases.unknown-deployment-stays-unknown',()=>{const a=new ReleasesDomainAdapter({candidates:[candidate()]});const r=a.inspect('cand-1');assert(r.ok&&r.candidate.deployment==='UNKNOWN'&&r.truth.unknownDeploymentRemainsUnknown&&r.deploymentTruth.state==='UNKNOWN'&&!r.deploymentTruth.attributionAllowed)},t);
  run('releases.unbound-deployment-claim-does-not-become-observed-truth',()=>{const a=new ReleasesDomainAdapter({candidates:[candidate({deployment:'NOT_DEPLOYED'})]});const r=a.inspect('cand-1');assert(r.ok&&r.candidate.deployment==='NOT_DEPLOYED'&&r.deploymentTruth.state==='UNKNOWN'&&r.deploymentTruth.rawCandidateClaim==='NOT_DEPLOYED'&&!r.deploymentTruth.attributionAllowed)},t);
  run('releases.deployment-observation-is-exact-candidate-bound',()=>{const a=new ReleasesDomainAdapter({candidates:[candidate()]});const observation={providerId:'deployment-observer.test',candidateRef:ref(),state:'DEPLOYED' as const,observedAt:'2026-09-26T12:00:00Z'};const r=a.observeDeployment('cand-1',observation);assert(r.deploymentTruth.state==='DEPLOYED'&&r.deploymentTruth.providerId==='deployment-observer.test'&&r.deploymentTruth.attributionAllowed)},t);
  run('releases.deployment-observation-mismatch-rejected',()=>{const a=new ReleasesDomainAdapter({candidates:[candidate()]});let failed=false;try{a.observeDeployment('cand-1',{providerId:'deployment-observer.test',candidateRef:ref('cand-2'),state:'DEPLOYED',observedAt:'2026-09-26T12:00:00Z'})}catch(e){failed=String((e as any).message).includes('DEPLOYMENT_OBSERVATION_CANDIDATE_BINDING_MISMATCH')}assert(failed)},t);
  run('releases.head-move-is-explicit-stale',()=>{const a=new ReleasesDomainAdapter({candidates:[candidate()]});a.select('cand-1');const r=a.compare({currentHeadCommitSHA:h('e')});assert(r.stale&&r.pinnedCommitSHA===h('a')&&!r.evidenceAttributionAllowed)},t);
  run('releases.plan-never-executes-deployment',()=>{const a=new ReleasesDomainAdapter({candidates:[candidate()]});const r=a.plan('cand-1');assert(r.ok&&r.executesDeployment===false&&r.grantsDeploymentAuthorization===false&&r.deploymentTruth.state==='UNKNOWN')},t);
  run('releases.command-unavailable-emits-no-receipt',()=>{const c=createReleasesSurfaceComposition({adapter:new ReleasesDomainAdapter({candidates:[candidate()]}),commands:new SemanticCommandBus()});c.adapter.select('cand-1');const before=c.commands.receipts.length;const r=c.commands.execute('releases.requestAuthorization',{});assert(r.ok===false&&c.commands.receipts.length===before)},t);
  run('releases.collection-is-shared-core-bound-domain-data',()=>{const c=createReleasesSurfaceComposition({adapter:new ReleasesDomainAdapter({candidates:[candidate()]}),commands:new SemanticCommandBus()});assert(c.collection.snapshot().totalRows===1&&c.slots.LEFT==='collection')},t);
  run('releases.context-exact-candidate-descriptor-valid',()=>{const a=new ReleasesDomainAdapter({candidates:[candidate()]});a.select('cand-1');const c=createReleasesSurfaceComposition({adapter:a,commands:new SemanticCommandBus()});const r=describeContextProvider(c.contextProvider,{id:'cand-1'});assert(r.ok&&r.descriptor.revisionToken===h('c')&&r.descriptor.summary.includes('deployment UNKNOWN'))},t);
  run('releases.deployment-execution-capability-not-owned',()=>{const c=createReleasesSurfaceComposition({commands:new SemanticCommandBus()});assert(c.providerTruth.deploymentExecution==='NOT_OWNED'&&c.providerTruth.deploymentProviderUnavailableEffectiveState==='UNKNOWN'&&c.truthCeiling.deploymentAuthorizationOwned===false)},t);
  run('releases.platform-truth-remains-unavailable-fallback',()=>{const c=createReleasesSurfaceComposition({commands:new SemanticCommandBus()});assert(c.platformTruth.activeKeyboardSource.includes('UNAVAILABLE')&&c.platformTruth.nativeWindow.includes('UNAVAILABLE'))},t);
  run('releases.compare-requires-controller-injected-owner',()=>{const a=new ReleasesDomainAdapter({candidates:[candidate(),candidate({candidateId:'cand-2',commitSHA:h('e'),treeSHA:h('f'),artifactDigest:h('1'),evidenceDigest:h('2')})]});const c=createReleasesSurfaceComposition({adapter:a,commands:new SemanticCommandBus()});const r=c.commands.execute('releases.compare',{leftId:'cand-1',rightId:'cand-2'});assert(r.ok===false&&r.code==='ANALYTICAL_COMPARE_INTEGRATION_REQUIRED'&&c.compareBinding.fallbackOwnerConstruction===false)},t);
  run('releases.exact-pair-uses-explicit-canonical-owner',()=>{const a=new ReleasesDomainAdapter({candidates:[candidate(),candidate({candidateId:'cand-2',commitSHA:h('e'),treeSHA:h('f'),artifactDigest:h('1'),evidenceDigest:h('2')})]});const owner=new AnalyticalCompareOwner();const c=createReleasesSurfaceComposition({adapter:a,commands:new SemanticCommandBus(),analyticalCompareOwner:owner});const r=c.commands.execute('releases.compare',{leftId:'cand-1',rightId:'cand-2'});assert(r.ok&&r.mode==='EXACT_PAIR'&&r.leftRef.candidateId==='cand-1'&&r.rightRef.candidateId==='cand-2'&&r.receipt.owner==='AnalyticalCompareOwner'&&c.compareBinding.available===true)},t);
  run('releases.evidence-package-cannot-cross-candidate-boundary',()=>{let failed=false;try{new ReleasesDomainAdapter({candidates:[candidate({evidenceBinding:{digest:h('d'),candidateRef:ref(),method:'TEST',packages:[{evidenceId:'pkg-1',candidateRef:ref('cand-2'),kind:'ci',producer:'test',check:'build',observedAt:'2026-09-26T12:00:00Z',artifactDigest:h('9'),result:'PASS'}]}})]})}catch(e){failed=String((e as any).message).includes('RELEASE_EVIDENCE_PACKAGE_CANDIDATE_BINDING_MISMATCH')}assert(failed)},t);
  run('releases.evidence-package-fields-remain-provenance-rich',()=>{const pkg={evidenceId:'pkg-1',candidateRef:ref(),kind:'ci',producer:'github-actions',check:'build-runtime',observedAt:'2026-09-26T12:00:00Z',artifactDigest:h('9'),result:'PASS' as const,reviewerDecisionRef:null,evidenceRefs:['log:1']};const a=new ReleasesDomainAdapter({candidates:[candidate({evidenceBinding:{digest:h('d'),candidateRef:ref(),method:'EXACT_PACKAGE_SET',packages:[pkg]}})]});const r=a.inspect('cand-1');assert(r.evidenceCoverage.bound&&r.evidenceCoverage.packageCount===1&&r.evidenceBinding.packages[0].producer==='github-actions')},t);
  run('releases.technically-ready-without-evidence-is-data-coverage-blocked',()=>{const a=new ReleasesDomainAdapter({candidates:[candidate({evidenceDigest:null,evidenceBinding:null})]});const r=a.inspect('cand-1');assert(r.ok&&r.candidate.state==='TECHNICALLY_READY'&&r.evidenceCoverage.state==='DATA_COVERAGE_BLOCKER'&&r.truth.technicalReadinessAttributionAllowed===false)},t);
  run('releases.workbench-keeps-truth-planes-independent',()=>{const c=createReleasesSurfaceComposition({commands:new SemanticCommandBus()});const p=c.centerProjection();assert(p.dataCoverage==='DATA_COVERAGE_BLOCKER'&&p.planes.technicalReadiness==='INDEPENDENT'&&p.planes.ownerAuthorization==='INDEPENDENT'&&p.planes.deploymentObservation==='INDEPENDENT'&&p.planes.deploymentExecution==='NOT_OWNED')},t);
  return t;
}
if(import.meta.url===new URL(process.argv[1],'file:').href){const tests=runReleasesSurfaceTests();console.log(JSON.stringify({surface:'releases',pass:tests.filter(x=>x.status==='PASS').length,fail:tests.filter(x=>x.status==='FAIL').length,tests},null,2));if(tests.some(x=>x.status==='FAIL'))process.exitCode=1;}
