import assert from 'node:assert/strict';
import {W03LabDomain} from '../../../adapters/labs/domain.js';
import {composeLabsSurface} from '../../../surfaces/labs/index.js';
const domain=new W03LabDomain({definition:{id:'LAB-1',revision:'3',title:'تحليل ويب / Web analysis',tasks:[{id:'T1',title:'Observe',validation:'event',expectedSignal:'signal'}],dependencies:[],requiredTools:[{id:'proxy',revision:'2',simulated:true}]}});
const surface=composeLabsSurface({domain,shared:{structuredHost:{owner:'StructuredSurfaceHost'},spatialRelation:{owner:'RelationInteractionOwner'}}});
const draftPreflight=surface.bus.execute('labs.preflight',{tools:{proxy:{revision:'2'}}});assert.equal(draftPreflight.status,'BLOCKED');assert.equal(draftPreflight.runStartAllowed,false);assert.equal(draftPreflight.simulationExplicit,true);
const draftHandoff=surface.bus.execute('labs.handoff',{tools:{proxy:{revision:'2'}}});assert.equal(draftHandoff.ok,false);assert.equal(draftHandoff.code,'LAB_REVISION_NOT_PUBLISHED');const directDraftHandoff=domain.handoff({tools:{proxy:{revision:'2'}}});assert.equal(directDraftHandoff.runCreated,false);assert.equal(directDraftHandoff.runtimeStateCreated,false);
const published=domain.publish({digest:'lab-1-r3'});assert.equal(published.ok,true);assert.equal(domain.snapshot().lifecycle,'PUBLISHED');
const ready=surface.bus.execute('labs.preflight',{tools:{proxy:{revision:'2'}}});assert.equal(ready.status,'READY');assert.equal(ready.runStartAllowed,true);assert.equal(ready.simulationExplicit,true);
const handoff=surface.bus.execute('labs.handoff',{tools:{proxy:{revision:'2'}}});assert.equal(handoff.ok,true);assert.equal(handoff.runCreated,false);assert.equal(handoff.runtimeStateCreated,false);assert.deepEqual(handoff.labRef,{id:'LAB-1',revision:'3'});
const before=domain.version;const blocked=surface.bus.execute('labs.handoff',{tools:{}});assert.equal(blocked.ok,false);assert.equal(blocked.code,'LAB_PREFLIGHT_BLOCKED');assert.equal(domain.version,before);
const revised=surface.bus.execute('labs.revise',{expectedVersion:domain.version});assert.equal(revised.snapshot.lifecycle,'DRAFT');domain.author({tasks:[{id:'T1',title:'Observe',validation:'UNBOUND',expectedSignal:''}]});assert.equal(domain.validate().ok,false);assert.equal(domain.snapshot().persistence.status,'UNAVAILABLE');console.log('labs surface: PASS');
