import {ReviewAuditFamilyHost} from '../../foundation/review/family-host.js';
import {createValidationConsumerAdapter,VALIDATION_RULESET_IDENTITY,VALIDATION_VALIDATOR_IDENTITY} from '../../adapters/validation.js';

const escape=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const sample=JSON.stringify({artifactRef:'artifact-local-001',artifactDigest:'a'.repeat(64),ruleset:VALIDATION_RULESET_IDENTITY,validator:VALIDATION_VALIDATOR_IDENTITY,payload:{note:'تحقق TCP/IP من العربية'}},null,2);
export function mountValidationSurface({stage,registry,workspace,adapter=createValidationConsumerAdapter()}={}){
  if(!stage||!registry)throw Error('VALIDATION_PRODUCT_COMPOSITION_REQUIRED');
  let host=null;
  const shell=document.createElement('section');shell.className='validation-product';shell.innerHTML=`<style>.validation-product{display:grid;gap:14px;min-height:100%;background:#08111d;color:#eaf2ff;padding:16px}.validation-runner{display:grid;gap:10px;padding:16px;border:1px solid #26364c;border-radius:16px;background:#0c1523}.validation-runner textarea{min-height:196px;resize:vertical;border:1px solid #38506d;border-radius:10px;background:#07101b;color:inherit;padding:12px;font:13px/1.5 ui-monospace,monospace}.validation-actions{display:flex;gap:8px;flex-wrap:wrap}.validation-runner button{border:1px solid #365276;border-radius:10px;background:#12253f;color:inherit;padding:9px 13px;cursor:pointer}.validation-runner button:focus-visible,.validation-runner textarea:focus-visible{outline:3px solid #79b8ff;outline-offset:2px}.validation-state{font-size:12px;color:#a9bad0}.validation-identity{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;font-size:12px}.validation-identity div{padding:8px;border:1px solid #26364c;border-radius:8px;min-width:0;overflow:hidden}.validation-identity bdi,.validation-identity small{display:block;max-width:100%;overflow-wrap:anywhere;word-break:break-all}.validation-identity small{font-size:10px;line-height:1.35;color:#9eb2ca}.technical-findings{display:grid;gap:8px}.technical-finding{padding:10px;border:1px solid #5b3d44;border-radius:10px;background:#201117}.technical-finding bdi{font-family:ui-monospace,monospace}.validation-family-host{min-height:0}@media(max-width:1050px){.validation-product{padding:10px}.validation-identity{grid-template-columns:1fr}}</style><section class="validation-runner" aria-labelledby="validation-runner-title"><h1 id="validation-runner-title">Technical Validation Workbench</h1><p>Validation is pinned to exact artifact, ruleset, and validator identities. TechnicalFinding stays in W05 and never becomes a W04 Review Finding.</p><textarea id="validationInput" dir="auto" aria-label="Validation JSON input">${escape(sample)}</textarea><div class="validation-actions"><button type="button" data-validation-run>Validate</button><button type="button" data-validation-inspect>Inspect result</button><button type="button" data-validation-findings>Technical findings</button></div><output class="validation-state" aria-live="polite">No validation run yet.</output><div class="validation-identity" data-validation-identity></div><div class="technical-findings" aria-label="Technical findings"></div></section><div class="validation-family-host" data-validation-family-host></div>`;stage.replaceChildren(shell);
  const familyRoot=shell.querySelector('[data-validation-family-host]'),stateNode=shell.querySelector('.validation-state'),identityNode=shell.querySelector('[data-validation-identity]'),findingNode=shell.querySelector('.technical-findings'),runButton=shell.querySelector('[data-validation-run]'),inspectButton=shell.querySelector('[data-validation-inspect]'),findingsButton=shell.querySelector('[data-validation-findings]'),input=shell.querySelector('#validationInput');
  const render=()=>{adapter.refresh();const run=adapter.state.last,snapshot=adapter.collection.snapshot();stateNode.textContent=adapter.state.processing?'Running technical validation…':run?`${run.status} · ${run.resultId||run.requestId}`:'No validation run yet.';identityNode.innerHTML=run?.identity?`<div><strong>Artifact</strong><br><bdi dir="ltr">${escape(run.identity.artifact.ref)}</bdi><br><small><bdi dir="ltr">${escape(run.identity.artifact.digest)}</bdi></small></div><div><strong>Ruleset</strong><br><bdi dir="ltr">${escape(run.identity.ruleset.id)}@${escape(run.identity.ruleset.revision)}</bdi><br><small><bdi dir="ltr">${escape(run.identity.ruleset.digest)}</bdi></small></div><div><strong>Validator</strong><br><bdi dir="ltr">${escape(run.identity.validator.id)}@${escape(run.identity.validator.version)}</bdi><br><small><bdi dir="ltr">${escape(run.identity.validator.digest)}</bdi></small></div>`:'<div>No exact input identity yet.</div>';findingNode.innerHTML=snapshot.visibleRows.length?snapshot.visibleRows.map(f=>`<article class="technical-finding" data-technical-finding="${escape(f.id)}"><strong>${escape(f.message)}</strong><div><bdi dir="ltr">${escape(f.code)}</bdi> · ${escape(f.locator||'')}</div><small>TechnicalFinding only · formalReviewFinding=false</small></article>`).join(''):'<p>No TechnicalFindings.</p>';if(!host){host=new ReviewAuditFamilyHost({consumer:adapter.consumerInput||adapter.consumer,onRefresh:async()=>{adapter.refresh();render()}});host.mount(familyRoot,{provenanceCore:adapter.provenance,reviewSnapshot:adapter.reviewSnapshot(),title:'Validation · Audit/Provenance inspection',summary:'Actual validation runs feed shared provenance inspection. Formal review findings remain a separate W04 governed domain.'})}else host.update({provenanceCore:adapter.provenance,reviewSnapshot:adapter.reviewSnapshot()});workspace?.status?.(run?`Validation ${run.status}`:'Validation ready','info');workspace?.region?.('LEFT',{html:run?`<section class="validation-runner"><h2>ValidationRequest</h2><p><bdi dir="ltr">${escape(run.requestId||run.resultId||'current')}</bdi></p><p>${escape(run.status||'OBSERVED')}</p></section>`:'<p>No ValidationRequest has been observed yet.</p>',label:'Validation requests'});if(familyRoot)workspace?.region?.('RIGHT',{node:familyRoot,label:'Validation provenance'});workspace?.region?.('BOTTOM',{html:findingNode.innerHTML,label:'Technical findings',summary:'TechnicalFinding remains distinct from W04 Review Finding.'});workspace?.refreshToolbar?.()};
  const run=async payload=>{runButton.disabled=true;stateNode.textContent='Running technical validation…';try{return await adapter.validate(payload?.raw??input.value)}finally{runButton.disabled=false;render()}};
  registry.register('validation.validate','ValidationConsumerAdapter','Validate exact artifact',run,()=>!adapter.state.processing||'Validation already processing');
  registry.register('validation.inspect','ValidationConsumerAdapter','Inspect validation result',payload=>{const result=adapter.inspect(payload||{});stateNode.textContent=result.ok?`${result.code} · no admission/review authority`:result.code;render();return result},()=>adapter.state.last?true:'No validation result');
  registry.register('validation.findings','ValidationConsumerAdapter','Inspect TechnicalFindings',payload=>{const result=adapter.findings(payload||{});stateNode.textContent=result.ok?`${result.technicalFindings.length} TechnicalFinding(s) · 0 W04 Finding(s)`:result.code;render();return result},()=>adapter.state.last?true:'No validation result');
  registry.register('validation.run','ValidationConsumerAdapter','Legacy alias · validate exact artifact',run,()=>!adapter.state.processing||'Validation already processing');
  runButton.addEventListener('click',()=>Promise.resolve(registry.execute('validation.validate',{raw:input.value,route:'validation-validate-button'})).catch(error=>{stateNode.textContent=`ERROR · ${String(error?.message||error)}`}));
  inspectButton.addEventListener('click',()=>registry.execute('validation.inspect',{route:'validation-inspect-button'}));
  findingsButton.addEventListener('click',()=>registry.execute('validation.findings',{route:'validation-findings-button'}));
  stage.dataset.surfaceComposition='validation-technical-workbench';render();workspace?.toolbar?.(['validation.validate','validation.inspect','validation.findings','foundation.settings']);
  return Object.freeze({owner:'ValidationProductComposition',adapter,host:()=>host,render,realProductConsumer:true,slots:{CENTER:'TechnicalValidationWorkbench',LEFT:'shared-collection',RIGHT:'shared-context/audit',BOTTOM:'shared-audit-provenance'}});
}
