// Exact v3.4 Enterprise inline script[7] nodes.
export const nodes={
 web:{name:"Web Application",id:"APP-WEB-01",type:"Application",source:"Enterprise-backed",sourceClass:"cyan",lifecycle:"ACTIVE",capabilities:["HTTP Service","Session State","Auth Integration"],behavior:"Application request/response rules",telemetry:"Enabled",validation:"Compatible",rels:[["PROTECTED_BY","CTL-WAF-01"],["DEPENDS_ON","DATA-SQL-01"],["AUTHENTICATES_WITH","ID-SVC-01"],["SENDS_LOGS","SVC-SIEM-01"]]},
 waf:{name:"Web Application Firewall",id:"CTL-WAF-01",type:"Security Control",source:"Enterprise-backed",sourceClass:"cyan",lifecycle:"ACTIVE",capabilities:["Request Filtering","Rule Evaluation","Event Generation"],behavior:"Control-policy behavior",telemetry:"Enabled",validation:"Compatible",rels:[["PROTECTS","APP-WEB-01"],["SENDS_LOGS","SVC-SIEM-01"]]},
 attacker:{name:"Attacker Workstation",id:"SIM-ATK-01",type:"Simulation-local Device",source:"Simulation-local",sourceClass:"red",lifecycle:"TRAINING_ONLY",capabilities:["Simulated Browser","Synthetic Requests","Scenario Bindings"],behavior:"Training-only behavior rules",telemetry:"Synthetic",validation:"Allowed with explicit local scope",rels:[["CONNECTS_TO","APP-WEB-01"]]},
 db:{name:"Database",id:"DATA-SQL-01",type:"Data Service",source:"Enterprise-backed",sourceClass:"cyan",lifecycle:"ACTIVE",capabilities:["Structured Data","Query Behavior","Access Rules"],behavior:"Database service behavior",telemetry:"Enabled",validation:"Compatible",rels:[["DEPENDED_ON_BY","APP-WEB-01"],["SENDS_LOGS","SVC-SIEM-01"]]},
 idp:{name:"Identity Service",id:"ID-SVC-01",type:"Identity Service",source:"Enterprise-backed",sourceClass:"cyan",lifecycle:"ACTIVE",capabilities:["Authentication","Identity Claims","Role Context"],behavior:"Authentication outcome rules",telemetry:"Enabled",validation:"Compatible",rels:[["AUTHENTICATES","APP-WEB-01"],["SENDS_LOGS","SVC-SIEM-01"]]},
 siem:{name:"SIEM / Monitoring",id:"SVC-SIEM-01",type:"Monitoring Service",source:"Enterprise-backed",sourceClass:"cyan",lifecycle:"ACTIVE",capabilities:["Event Intake","Telemetry View","Detection Rules"],behavior:"Telemetry generation + correlation",telemetry:"Enabled",validation:"Compatible",rels:[["RECEIVES_LOGS_FROM","APP-WEB-01"],["RECEIVES_LOGS_FROM","CTL-WAF-01"]]}
};
