import {clamp,PREFERENCE_DEFINITIONS} from './models.js';
import {TransientFocusOwner} from './global/transient-focus.js';
import {projectSaveStatus,projectToolbarModeState,composeToolbarSlots} from './global/toolbar-template.js';
import {eventTargetElement} from './global/input-ownership-contract.js';
import {StructuredActionSurfacePresentationHost} from './structured/action-surfaces/presentation-host.js';
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const button=(id,label,extra='')=>`<button class="btn" data-foundation-command="${esc(id)}" ${extra}>${esc(label)}</button>`;
export class ContextDescriptorProvider {
  constructor(id,describe){if(!id||typeof describe!=='function')throw Error('INVALID_CONTEXT_DESCRIPTOR_PROVIDER');this.id=id;this.describe=describe;}
}
export class ContextInspectorPresentation {
  render(provider){const descriptor=provider.describe();if(!descriptor?.subject)throw Error('CONTEXT_DESCRIPTOR_SUBJECT_REQUIRED');const fields=(descriptor.fields||[]).map(field=>`<div class="domain-card"><strong>${esc(field.label)}</strong><p ${field.technical?'dir="ltr"':''}>${esc(field.value)}</p></div>`).join('');const actions=(descriptor.actions||[]).map(action=>button(action.id,action.label)).join('');const details=descriptor.details?`<details><summary>${esc(descriptor.details.label||'Details')}</summary><pre dir="ltr">${esc(JSON.stringify(descriptor.details.value,null,2))}</pre></details>`:'';return `<header class="context-identity" data-context-provider="${esc(provider.id)}"><div class="context-eyebrow">${esc(descriptor.eyebrow||'Context')}</div><strong>${esc(descriptor.subject)}</strong><p>${esc(descriptor.summary||'')}</p></header>${fields}${actions}${descriptor.owner&&(()=>{try{const m=new URLSearchParams(location.search).get('diagnostics');return m==='foundation'||m==='1'}catch{return false}})()?`<p>Canonical owner: ${esc(descriptor.owner)}</p>`:''}${details}`;}
}
export class WorkspaceFoundation {
  constructor(api,commands,preferences,consumer,transientOwner=null){this.api=api;this.commands=commands;this.preferences=preferences;this.consumer=consumer;this.transients=transientOwner||api.transients||new TransientFocusOwner({fallbackFocus:()=>document.querySelector('#centerPane')});this.scope='global';this.popover=null;this.dialogInvoker=null;this.inspectorPresentation=new ContextInspectorPresentation();this.actionPresentation=new StructuredActionSurfacePresentationHost({transientFocus:this.transients,document,window});this.toolbarIds=[];this.toolbarContextProvider=null;this.toolbarContextSubscribe=null;this.toolbarContextUnsubscribe=null;this.regionHosts=new Map();this.dictionary={ar:{library:'المكتبة',learn:'التعلّم',visualize:'التصوّر',enterprise:'W03 المؤسسة',runs:'W03 التشغيل',golden:'منصة الاختبار',settings:'التفضيلات',focus:'تركيز',note:'ملاحظة',notes:'الملاحظات',exitFocus:'إنهاء التركيز',preferences:'التفضيلات',scope:'النطاق',search:'بحث',contextActions:'إجراءات السياق',close:'إغلاق',savePersisted:'تم الحفظ عبر حدود دائمة مؤكدة',saveUnavailable:'لم يتم الحفظ دائمًا — Save boundary غير متاحة',saveFailed:'فشل الحفظ الصريح؛ المسودة ما تزال محلية'},en:{library:'Library',learn:'Learn',visualize:'Visualize',enterprise:'W03 Enterprise',runs:'W03 Runs',golden:'Golden Harness',settings:'Settings',focus:'Focus',note:'Note',notes:'Notes',exitFocus:'Exit focus',preferences:'Preferences',scope:'Scope',search:'Search',contextActions:'Context Actions',close:'Close',savePersisted:'Saved through a confirmed durable boundary',saveUnavailable:'Not durably saved — Save boundary unavailable',saveFailed:'Explicit save failed; the draft remains local'}};this.saveStatusState=null;this.createChrome();this.bind();this.applyPreferences();}
  text(key){return this.dictionary[this.preferences.resolve('locale').preferredValue]?.[key]||key;}
  projectExplicitSaveStatus(state){
    const table={persisted:{state:'saved',key:'savePersisted'},unavailable:{state:'not-persisted',key:'saveUnavailable'},failed:{state:'failed',key:'saveFailed'}},entry=table[state];
    if(!entry)return null;this.saveStatusState=state;return projectSaveStatus(document,{state:entry.state,label:this.text(entry.key)});
  }
  createChrome(){
    document.body.dataset.consumer=this.consumer;document.querySelector('.global').hidden=true;document.querySelector('.w02nav').hidden=true;
    const shell=document.createElement('header');shell.className='foundation-shell';shell.dataset.shellHost='GlobalShellNavigationOwner';shell.setAttribute('aria-busy','true');document.querySelector('.app').prepend(shell);
    const family=this.api.binding?.family||null,documentSemantics=this.consumer==='library'?'library':family==='structured'?'structured':'neutral',identity=(this.consumer==='library'||this.consumer==='learn')?'visible':'hidden';
    composeToolbarSlots(document,{globalHTML:`${button('foundation.palette','⌘')}${button('foundation.focus',this.text('focus'),'data-i18n="focus"')}${button('foundation.note',this.text('note'),'data-i18n="note"')}${button('foundation.notes',this.text('notes'),'data-i18n="notes"')}`,documentSemantics,identity});
    this.applyCarrierPolicy({documentSemantics,identity});
    const menu=document.createElement('div');menu.id='foundationMenu';menu.className='popover';menu.setAttribute('role','menu');menu.hidden=true;document.body.append(menu);
    const bd=document.createElement('div');bd.id='foundationDialog';bd.className='backdrop';bd.hidden=true;bd.innerHTML='<section class="dialog" role="dialog" aria-modal="true" aria-labelledby="foundationDialogTitle"><header class="dialoghead"><h2 id="foundationDialogTitle"></h2><button class="btn" data-foundation-close="dialog" aria-label="Close dialog">×</button></header><div class="dialogbody"></div><footer class="dialogfoot"><button class="btn" data-foundation-close="dialog">Cancel / إلغاء</button></footer></section>';document.body.append(bd);
    // Explicit palette pointer reversal uses its original backdrop/focus owner.
    const command=document.querySelector('#commandBackdrop .cmdsearch');if(command&&!command.querySelector('[data-foundation-close]'))command.insertAdjacentHTML('beforeend','<button class="btn" data-foundation-close="palette" aria-label="Close command palette">×</button>');
    const context=document.createElement('div');context.id='domainContext';context.hidden=true;document.querySelector('#rightPane .pbody').append(context);
    const focusReturn=document.createElement('button');focusReturn.className='btn foundation-focus-return';focusReturn.textContent=this.text('exitFocus');focusReturn.dataset.i18n='exitFocus';focusReturn.dataset.foundationCommand='foundation.focus';document.body.append(focusReturn);
    const status=document.createElement('output');status.id='foundationStatus';status.className='foundation-status';status.setAttribute('aria-live','polite');document.body.append(status);
  }
  applyCarrierPolicy({documentSemantics='neutral',identity='hidden'}={}){
    document.body.dataset.carrierDocumentSemantics=documentSemantics;document.body.dataset.carrierIdentitySemantics=identity;
    const donorCompatible=this.consumer==='library'||this.consumer==='learn';
    if(!donorCompatible){
      document.querySelectorAll('#topBanner .crumbs,#topBanner .secondary,#topBanner .tags').forEach(node=>{node.hidden=true;node.inert=true;node.setAttribute('aria-hidden','true');node.dataset.donorSemantic='suppressed'});
    }
    if(documentSemantics==='neutral'){
      const selectors=['#leftPane .treesearch','#leftPane .fixture','#leftPane .treetitle','#leftPane #kuList','#leftPane .mapbtn','#rightPane .contextscope','#rightPane #inspectorContent','#bottomShelf .bottomtabs'];
      document.querySelectorAll(selectors.join(',')).forEach(node=>{node.hidden=true;node.inert=true;node.setAttribute('aria-hidden','true');node.dataset.donorSemantic='suppressed'});
    }
    return {documentSemantics,identity,donorCompatible};
  }
  toolbarContext(){
    if(typeof this.toolbarContextProvider!=='function')return {};
    try{const value=this.toolbarContextProvider();return value&&typeof value==='object'?value:{}}catch(error){this.status(`Toolbar context unavailable · ${String(error?.message||error)}`,'error');return {}}
  }
  refreshToolbar(){
    const host=document.querySelector('#domainToolbar');if(!host)return false;
    const payload=this.toolbarContext();
    host.innerHTML=this.toolbarIds.map(id=>{const command=this.commands.commands.get(id);if(!command)return '';const availability=this.commands.availability(id,payload);return button(id,command.label,`${availability.enabled?'':'disabled'} title="${esc(availability.reason||'')}" data-contextual-command="true"`)}).join('');
    host.dataset.contextBound=String(Boolean(this.toolbarContextProvider));return true;
  }
  bindToolbarContext({contextProvider=null,subscribe=null}={}){
    if(contextProvider!==null)this.toolbarContextProvider=typeof contextProvider==='function'?contextProvider:()=>contextProvider||{};
    if(subscribe!==this.toolbarContextSubscribe){
      this.toolbarContextUnsubscribe?.();this.toolbarContextUnsubscribe=null;this.toolbarContextSubscribe=subscribe;
      if(typeof subscribe==='function'){const cleanup=subscribe(()=>this.refreshToolbar());if(typeof cleanup==='function')this.toolbarContextUnsubscribe=cleanup;}
    }
    this.refreshToolbar();return {contextBound:Boolean(this.toolbarContextProvider),subscribed:Boolean(this.toolbarContextUnsubscribe)};
  }
  region(role,{html='',node=null,label='',summary='',open=null}={}){
    const key=String(role||'').toUpperCase();let host=null,pane=null;
    if(key==='LEFT'){pane=document.querySelector('#leftPane');host=document.querySelector('#domainLeftRegion');if(!host){host=document.createElement('div');host.id='domainLeftRegion';host.dataset.foundationRegion='LEFT';pane?.querySelector('.pbody')?.append(host)}}
    else if(key==='RIGHT'){pane=document.querySelector('#rightPane');host=document.querySelector('#domainContext');if(host)host.dataset.foundationRegion='RIGHT';}
    else if(key==='BOTTOM'){pane=document.querySelector('#bottomShelf');host=document.querySelector('#domainBottomRegion');if(!host){host=document.createElement('div');host.id='domainBottomRegion';host.dataset.foundationRegion='BOTTOM';document.querySelector('#bottomContent')?.append(host)}}
    else if(key==='TOOLBAR')host=document.querySelector('#domainToolbar');
    else if(key==='CENTER')host=document.querySelector('#foundationStage')||document.querySelector('#centerPane');
    if(!host)return null;
    if(key==='LEFT'||key==='RIGHT'){const pbody=pane?.querySelector('.pbody');if(pbody)[...pbody.children].forEach(child=>{if(child!==host&&child.dataset?.donorSemantic==='suppressed')child.hidden=true});}
    host.replaceChildren();if(node)host.append(node);else host.innerHTML=String(html||'');host.hidden=false;host.inert=false;host.removeAttribute('aria-hidden');host.dataset.regionBindingOwner='WorkspaceFoundationHost';
    if(label&&pane?.querySelector('.phead h2'))pane.querySelector('.phead h2').textContent=label;
    if(key==='BOTTOM'){const title=document.querySelector('#bottomShelf .bottomtitle'),sum=document.querySelector('#bottomSummary');if(label&&title)title.textContent=label;if(summary&&sum)sum.textContent=summary;if(open!==null){this.api.state.surface.bottomOpen=Boolean(open);document.querySelector('#bottomShelf').dataset.state=open?'open':'closed';const content=document.querySelector('#bottomContent');if(content){content.inert=!open;content.hidden=false}}}
    this.regionHosts.set(key,host);return host;
  }
  commandRoute(element){if(element?.closest?.('#foundationMenu'))return 'menu';if(element?.closest?.('#domainContext'))return 'context';if(element?.closest?.('#domainToolbar,.foundation-global,.toolbar'))return 'toolbar';return 'action-surface';}
  bind(){const structuredDocumentMode=this.api.hostKind==='DONOR_FREE_WORKSPACE_HOST'&&this.api.binding?.family==='structured'&&typeof this.api.binding?.setMode==='function';if(structuredDocumentMode){const canonicalSetMode=this.api.setMode.bind(this.api);this.api.setMode=mode=>{const result=canonicalSetMode(mode);projectToolbarModeState(document,{mode:this.api.state.surface.mode});return result};projectToolbarModeState(document,{mode:this.api.state.surface.mode})}document.addEventListener('click',e=>{const target=eventTargetElement(e.target);const toolbarAction=structuredDocumentMode?target?.closest?.('[data-action="set-mode"],[data-action="explicit-save"],[data-action="toolbar-more"]'):null;if(toolbarAction){e.preventDefault();try{const action=toolbarAction.dataset.action;if(action==='set-mode'){this.api.setMode(toolbarAction.dataset.value);return}if(action==='explicit-save'){const receipt=this.api.Commands.execute('document.commit',{route:'toolbar',reason:'explicit-save'});if(receipt?.persisted===true)this.projectExplicitSaveStatus('persisted');else if(receipt?.status==='SAVE_BOUNDARY_UNAVAILABLE')this.projectExplicitSaveStatus('unavailable');else this.projectExplicitSaveStatus('failed');return}if(action==='toolbar-more'){this.api.Commands.execute('foundation.settings',{route:'toolbar',invoker:toolbarAction});return}}catch(err){this.status(err.message,'error')}return}const cmd=target?.closest?.('[data-foundation-command]');if(cmd){if(cmd.closest?.('#commandResults'))return;e.preventDefault();const route=this.commandRoute(cmd);this.closeMenu(true,'command');try{const contextual=route==='toolbar'?this.toolbarContext():{};this.api.Commands.execute(cmd.dataset.foundationCommand,{...contextual,invoker:cmd,route})}catch(err){this.status(err.message,'error')}return}const close=target?.closest?.('[data-foundation-close]');if(close){if(close.dataset.foundationClose==='palette')this.closeCommandPalette('explicit');else this.closeDialog('explicit');return}if(e.target===document.querySelector('#foundationDialog')&&this.dialogOutsideSafe)this.closeDialog('outside');if(e.target===document.querySelector('#commandBackdrop')){const id=e.target.id;if(!this.transients.record(id)||this.transients.canDismiss(id,'outside'))this.closeCommandPalette('outside')}});
    document.addEventListener('pointerdown',e=>{if(this.popover&&!this.popover.contains(e.target)&&this.transients.canDismiss(this.popover.id,'outside'))this.closeMenu(false,'outside')},true);
    document.addEventListener('keydown',e=>{if(e.isComposing)return;if(e.key==='Escape'){const dialog=document.querySelector('#foundationDialog');if(!dialog.hidden&&this.transients.canDismiss(dialog.id,'escape')){e.preventDefault();e.stopImmediatePropagation();this.closeDialog('escape');return}if(this.popover&&this.transients.canDismiss(this.popover.id,'escape')){e.preventDefault();e.stopImmediatePropagation();this.closeMenu(true,'escape');return}const command=document.querySelector('#commandBackdrop');if(command&&!command.hidden&&(!this.transients.record(command.id)||this.transients.canDismiss(command.id,'escape'))){e.preventDefault();e.stopImmediatePropagation();this.closeCommandPalette('escape');return}}if(this.popover&&['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const a=[...this.popover.querySelectorAll('button:not(:disabled)')];let i=a.indexOf(document.activeElement);i=e.key==='Home'?0:e.key==='End'?a.length-1:(i+(e.key==='ArrowDown'?1:-1)+a.length)%a.length;a[i]?.focus()}},true);
  }
  openCommandPalette(){this.closeMenu(false,'replace');const bd=document.querySelector('#commandBackdrop'),invoker=document.activeElement;if(!bd)return false;const shared=this.api.transients===this.transients;if(!shared&&!this.transients.record(bd.id))this.transients.open(bd.id,{invoker,element:bd,kind:'command-palette',modal:true,outsideDismiss:true,escapeDismiss:true,fallbackFocus:()=>document.querySelector('#centerPane')});this.api.openCommandPalette();return true;}
  closeCommandPalette(reason='explicit'){const bd=document.querySelector('#commandBackdrop');if(!bd)return false;const shared=this.api.transients===this.transients;this.api.closeBackdrop(bd,{reason});if(!shared&&this.transients.record(bd.id))this.transients.close(bd.id,{restore:true,reason});return true;}
  status(message,tone='info'){const el=document.querySelector('#foundationStatus');el.textContent=message;el.dataset.tone=tone;clearTimeout(this.statusTimer);this.statusTimer=setTimeout(()=>el.textContent='',6000);}
  menu(ids,x,y){this.api.closePrimaryTransients();this.closeMenu(false,'replace');const el=document.querySelector('#foundationMenu');this.menuInvoker=document.activeElement;const items=ids.map(id=>{const c=this.commands.commands.get(id);if(!c)return null;const a=this.commands.availability(id);return {id,label:c.label,enabled:a.enabled,reason:a.reason||''}}).filter(Boolean);el.innerHTML=this.actionPresentation.renderGenericMenu({title:this.text('contextActions'),items,dismissLabel:this.text('close')});el.hidden=false;el.querySelector('[data-menu-dismiss]').onclick=()=>this.closeMenu(true,'explicit');this.popover=el;this.actionPresentation.openGenericMenu({element:el,invoker:this.menuInvoker,anchorRect:{left:x,right:x,top:y,bottom:y,width:0,height:0},fallbackFocus:()=>document.querySelector('#centerPane'),actionOwner:'SemanticCommandBus',onClose:()=>{el.hidden=true;if(this.popover===el)this.popover=null}});el.querySelector('button:not(:disabled)')?.focus();}
  closeMenu(focus=true,reason='explicit'){if(this.popover){const el=this.popover;this.popover=null;el.hidden=true;return this.actionPresentation.close('pw08:generic-action-menu',{restore:focus,reason})}return false;}
  dialog(title,body,{safeOutside=false,onMount=null}={}){this.closeMenu(false,'replace');this.api.closePrimaryTransients();const command=document.querySelector('#commandBackdrop');if(command&&!command.hidden)this.api.closeBackdrop(command,{restore:false,reason:'primary-reset'});const bd=document.querySelector('#foundationDialog');this.dialogOutsideSafe=safeOutside;document.querySelector('#foundationDialogTitle').textContent=title;bd.querySelector('.dialogbody').innerHTML=body;const invoker=document.activeElement;if(this.api.transients!==this.transients)this.transients.open(bd.id,{invoker,element:bd,kind:'dialog',modal:true,outsideDismiss:safeOutside,escapeDismiss:true,fallbackFocus:()=>document.querySelector('#centerPane')});this.api.openBackdrop(bd,invoker,{outsideDismiss:safeOutside,escapeDismiss:true});onMount?.(bd);return bd;}
  closeDialog(reason='explicit'){const bd=document.querySelector('#foundationDialog');const shared=this.api.transients===this.transients;this.api.closeBackdrop(bd,{reason});if(!shared&&this.transients.record(bd.id))this.transients.close(bd.id,{restore:true,reason});}
  toolbar(ids,options={}){this.toolbarIds=[...new Set(ids||[])];this.bindToolbarContext(options);return this.refreshToolbar();}
  inspector(html){const d=this.region('RIGHT',{html,label:'Context'});if(!d)return;const payload=this.toolbarContext();d.querySelectorAll('[data-foundation-command]').forEach(b=>{const a=this.commands.availability(b.dataset.foundationCommand,payload);b.disabled=!a.enabled;b.title=a.reason||''});}
  inspectorDescriptor(provider){this.inspector(this.inspectorPresentation.render(provider));}
  restoreInspector(){const p=document.querySelector('#rightPane .pbody');[...p.children].forEach(c=>c.hidden=c.id==='domainContext');this.api.renderInspector();}
  applyPreferences(){const p=this.preferences.values();this.api.applyPreferenceSnapshot({preferences:p},{persist:false});const direction=p.chromeDirection==='auto'?(p.locale==='ar'?'rtl':'ltr'):p.chromeDirection;document.documentElement.dir=direction;document.documentElement.lang=p.locale;document.body.dataset.foundationDirection=direction;document.body.dataset.foundationToolbar=p.toolbar;document.body.dataset.toolbarOrder=p.toolbarOrder;document.documentElement.style.setProperty('--foundation-scale',String(p.scale));document.documentElement.style.setProperty('--ui',`${p.font},system-ui,Arial,sans-serif`);document.querySelector('#editorDocument').style.textAlign=p.alignment;document.body.dataset.contentDirection=p.contentDirection;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=this.text(el.dataset.i18n));if(this.saveStatusState)this.projectExplicitSaveStatus(this.saveStatusState);this.onPreferences?.(p);this.api.renderCommandResults('');}
  settings(){return this.commands.execute('foundation.settings',{route:'workspace-foundation-settings-delegate',invoker:document.activeElement});}
}
