import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {CommandRegistry} from '../../../foundation/models.js';
import {createLibraryRuntimeComposition,assertGenuineLibrarySource} from '../../../surfaces/library/runtime-composition.js';
import {bindLibrarySurface} from '../../../surfaces/library/surface.js';
import {createLearnRuntimeComposition} from '../../../adapters/learn.js';
import {bindLearnSurface} from '../../../surfaces/learn/surface.js';
import {createLibraryStructuredContextProvider} from '../../../adapters/context-library-structured.js';

const assert=(value,message)=>{if(!value)throw Error(message)};
const run=(id,fn)=>{try{return {id,status:'PASS',detail:fn()}}catch(error){return {id,status:'FAIL',error:String(error?.message||error)}}};
const sourceRoot=process.env.CEP_SOURCE_ROOT?path.resolve(process.env.CEP_SOURCE_ROOT):path.resolve(process.cwd(),'stack/native-typescript');
const read=relative=>fs.readFileSync(path.join(sourceRoot,relative),'utf8');
const genuineSource=()=>({
  classification:'PRODUCT_RUNTIME_LOCAL_SOURCE',truth:'REAL_LIBRARY_PRODUCT_SOURCE',providerRef:'local-test-provider',
  document:{id:'LIB-REAL-001',revision:'r17',title:'Real Library working document',tags:['Knowledge'],blocks:[{id:'lib-p1',type:'paragraph',html:'Canonical real-consumer test block.'}]},
  sources:[{id:'source-1',title:'Provider source',kind:'ProviderRecord',status:'BOUND'}],
  context:{relations:[],labs:[],projects:[],evidence:[],notes:[]},lifecycle:{state:'PUBLISHED',sourceRevision:'r17'}
});

const learnSource={classification:'PRODUCT_RUNTIME_BOUND_SOURCE',truth:'BOUND_CANONICAL_LEARNING_SOURCE',providerRef:'s08-learning-provider',activity:{id:'activity-identity-01',revision:1,title:'Trust boundaries',kind:'practice',editable:true,prerequisiteState:'INCOMPLETE'},document:{id:'learn-doc-1',revision:'r1',title:'Trust boundaries',blocks:[{id:'learn-h1',type:'h2',html:'Trust boundaries'},{id:'learn-p1',type:'paragraph',html:'Explain the trust boundary.'}]}};

export function runS08Falsification(){
  const results=[];
  results.push(run('S08.library.fixture-source-hard-rejected',()=>{let code='';try{assertGenuineLibrarySource({...genuineSource(),classification:'FIXTURE_ONLY'})}catch(error){code=error.message}assert(code==='LIBRARY_FIXTURE_SOURCE_FORBIDDEN','fixture source was not rejected');return {code}}));
  results.push(run('S08.library.real-composition-single-structured-owner',()=>{const c=createLibraryRuntimeComposition({source:genuineSource()}),d=c.descriptor();assert(d.sourceIdentity.truth==='REAL_LIBRARY_PRODUCT_SOURCE'&&d.fixtureFallback===false,'real source truth missing');assert(d.structuredOwner==='LibraryDomainAdapter'&&d.transactionOwner==='StructuredTransactionHistoryRecoveryOwner','canonical Structured owner lost');return d}));
  results.push(run('S08.library.context-never-promotes-fixture-bundle',()=>{const c=createLibraryRuntimeComposition({source:genuineSource()});c.structured.fixtureBundle=()=>{throw Error('FIXTURE_PROMOTED')};const p=createLibraryStructuredContextProvider(c.structured),d=p.describe();const text=JSON.stringify(d);assert(text.includes('REAL_LIBRARY_PRODUCT_SOURCE'),'real source truth not projected');assert(text.includes('Provider source'),'real source binding not projected');return {providerId:d.providerId,subject:d.subject}}));
  results.push(run('S08.library.insert-preserves-neighbours-selection-and-undo',()=>{const source=genuineSource();source.document.blocks=[{id:'lib-b1',type:'bullet',html:'First',children:[]},{id:'lib-b2',type:'bullet',html:'Second',children:[]}];const c=createLibraryRuntimeComposition({source}),registry=new CommandRegistry();bindLibrarySurface({commands:registry,structured:c.structured,libraryRuntime:c});c.structured.selectBlocks(['lib-b2']);const before=c.structured.snapshot(),txBefore=c.structured.transactionDescriptor(),r=registry.execute('library.insert',{block:{id:'lib-insert',type:'bullet',html:'Inserted',children:[]},index:1}),after=c.structured.snapshot(),selection=c.structured.selectedFragmentIdentity(),txAfter=c.structured.transactionDescriptor();assert(r.ok===true&&after.blocks.map(b=>b.id).join(',')==='lib-b1,lib-insert,lib-b2','insert did not preserve neighbours');assert(selection.blockIds.join(',')==='lib-b2','selection drifted after insertion');assert(txAfter.historyLength===txBefore.historyLength+1,'insert did not create one history frame');c.structured.undo();const undone=c.structured.snapshot(),selectionAfterUndo=c.structured.selectedFragmentIdentity();assert(JSON.stringify(undone)===JSON.stringify(before),'undo did not restore exact pre-insert document');assert(selectionAfterUndo.blockIds.join(',')==='lib-b2','selection drifted after undo');return {afterIds:after.blocks.map(b=>b.id),selection:selection.blockIds,historyDelta:txAfter.historyLength-txBefore.historyLength,undoExact:true}}));
  results.push(run('S08.library.save-conflict-retains-draft-but-shared-receipt-loses-server-ref',()=>{const source=genuineSource();source.services={saveBoundary:()=>({ok:false,code:'STALE_BASE',currentRevision:'r18',reason:'Concurrent update'})};const c=createLibraryRuntimeComposition({source}),registry=new CommandRegistry();bindLibrarySurface({commands:registry,structured:c.structured,libraryRuntime:c});c.structured.updateBlock('lib-p1',{html:'Local dirty draft'});const beforeSave=c.structured.snapshot(),availability=registry.availability('library.save'),receipt=registry.execute('library.save'),afterSave=c.structured.snapshot();assert(availability.enabled===true,'real save boundary should enable save');assert(receipt.ok===false&&receipt.status==='SAVE_FAILED'&&receipt.error==='Concurrent update','conflict not surfaced as failed save');assert(c.structured.dirty===true&&JSON.stringify(afterSave)===JSON.stringify(beforeSave),'local draft was not retained after conflict');assert(receipt.currentRevision==='r18','shared transaction owner lost exact server revision conflict truth');return {availability:availability.code||'AVAILABLE',status:receipt.status,error:receipt.error,localDraftRetained:true,serverRevisionPreserved:true,currentRevision:receipt.currentRevision,classification:'SHARED_CONFLICT_RECEIPT_TRUTH_PRESERVED'}}));
  results.push(run('S08.library.revise-does-not-fake-title-edit',()=>{const c=createLibraryRuntimeComposition({source:genuineSource()}),registry=new CommandRegistry();bindLibrarySurface({commands:registry,structured:c.structured,libraryRuntime:c});const before=c.structured.snapshot().title,a=registry.availability('library.revise'),r=registry.execute('library.revise',{title:'must-not-overwrite'});assert(a.enabled===false&&r.ok===false,'revision should be unavailable without successor provider');assert(c.structured.snapshot().title===before,'published source was mutated');return {availability:a.code,status:r.status,title:before}}));
  results.push(run('S08.library.history-requires-exact-revision-provider',()=>{const c=createLibraryRuntimeComposition({source:genuineSource()}),registry=new CommandRegistry();bindLibrarySurface({commands:registry,structured:c.structured,libraryRuntime:c});const a=registry.availability('library.history',{leftRevision:'r16',rightRevision:'r17'}),r=registry.execute('library.history',{leftRevision:'latest',rightRevision:'r17'});assert(a.enabled===false&&r.ok===false,'history must not fabricate compare');return {availability:a.code,status:r.code||r.status}}));
  results.push(run('S08.learn.real-source-no-fixture-claim',()=>{const c=createLearnRuntimeComposition({source:learnSource});assert(c.descriptor.realConsumer===true&&c.descriptor.fixtureFallback===false,'Learn real-consumer descriptor missing');assert(c.structured.sourceBinding.truth==='BOUND_CANONICAL_LEARNING_SOURCE','Learn source truth missing');return c.descriptor}));
  results.push(run('S08.learn.open-no-prerequisite-navigation-lock',()=>{const c=createLearnRuntimeComposition({source:learnSource}),registry=new CommandRegistry();bindLearnSurface({commands:registry,learn:c.learn,structured:c.structured});const before=c.learn.learningProgress().state,r=registry.execute('learn.open');assert(r.ok&&r.prerequisiteNavigationLocked===false&&r.progressBefore===before&&r.progressAfter===before,'open incorrectly gated or progress mutated');return r}));
  results.push(run('S08.learn.editability-follows-object-capability',()=>{const c=createLearnRuntimeComposition({source:learnSource}),registry=new CommandRegistry();bindLearnSurface({commands:registry,learn:c.learn,structured:c.structured});c.learn.activity.editable=false;const a=registry.availability('learn.edit',{blockId:'learn-p1',patch:{html:'x'}});assert(a.enabled===false&&a.code==='LEARN_ACTIVITY_NOT_EDITABLE','actual object editability not honored');return a}));
  results.push(run('S08.learn.completed-attempt-source-immutable-across-document-edit',()=>{const c=createLearnRuntimeComposition({source:learnSource}),registry=new CommandRegistry();bindLearnSurface({commands:registry,learn:c.learn,structured:c.structured});registry.execute('learn.practice');const submitted=registry.execute('learn.practice',{action:'submit',answer:'trust boundary answer'}).attempt,sourceBefore=JSON.stringify(submitted.sourceSnapshot);const edit=registry.execute('learn.edit',{blockId:'learn-p1',patch:{html:'new working explanation'}});assert(edit.ok===true,'Learn structured edit failed');assert(JSON.stringify(c.learn.attempt.sourceSnapshot)===sourceBefore,'completed attempt source was rewritten');return {attemptId:submitted.id,dirty:c.structured.dirty}}));
  results.push(run('S08.learn.duplicate-submit-idempotent-no-mastery',()=>{const c=createLearnRuntimeComposition({source:learnSource}),registry=new CommandRegistry();bindLearnSurface({commands:registry,learn:c.learn,structured:c.structured});registry.execute('learn.practice');const a=registry.execute('learn.practice',{action:'submit',answer:'A'}),b=registry.execute('learn.practice',{action:'submit',answer:'B'});assert(a.attempt.id===b.attempt.id&&a.attempt.answer===b.attempt.answer,'duplicate submit changed attempt');assert(c.learn.learningProgress().mastery==='NOT_INFERRED','completion inferred Mastery');return {attemptId:a.attempt.id,answer:b.attempt.answer,mastery:c.learn.learningProgress().mastery}}));
  results.push(run('S08.learn.review-never-creates-w04-decision-or-mastery',()=>{const c=createLearnRuntimeComposition({source:learnSource}),registry=new CommandRegistry();bindLearnSurface({commands:registry,learn:c.learn,structured:c.structured});registry.execute('learn.practice');const sub=registry.execute('learn.practice',{action:'submit',answer:'A'}),r=registry.execute('learn.review',{attemptId:sub.attempt.id});assert(r.ok&&r.masteryWrite===false&&r.formalReviewCreated===false&&r.w04DecisionCreated===false&&r.mastery==='NOT_INFERRED','review crossed W04/Mastery boundary');return r}));
  results.push(run('S08.learn.lab-never-creates-w03-runtime',()=>{const c=createLearnRuntimeComposition({source:learnSource}),d=c.learn.labDescriptor();assert(d.runtime==='NOT_CREATED'&&d.w03RuntimeCreated===false,'Learn created W03 runtime');return d}));
  results.push(run('S08.learn.stale-revision-does-not-count-completion',()=>{const c=createLearnRuntimeComposition({source:learnSource});c.learn.start();c.learn.submit('A');c.learn.activity.revision++;const p=c.learn.learningProgress();assert(p.state==='INCOMPLETE'&&p.attemptTruth==='STALE_REVISION_ATTEMPT'&&p.mastery==='NOT_INFERRED','stale attempt counted for current completion');return p}));
  results.push(run('S08.od054.shared-owner-correction-survives-replay',()=>{const host=read('foundation/structured/surface-host.ts'),workspace=read('foundation/workspace-host.ts'),main=read('main.ts');const leftClick=/insertion-trigger="true"[\s\S]{0,900}_activateGap|_activateGap\(root,gap\)/.test(host),keyboard=/keydown[\s\S]{0,1400}insertion-trigger="true"[\s\S]{0,500}_activateGap/.test(host),contextBlock=/addEventListener\('contextmenu'[\s\S]{0,900}block-handle/.test(host),contextGap=/addEventListener\('contextmenu'[\s\S]{0,700}secondary-direct-paragraph/.test(host),chooserBound=/structured-insertion-request[\s\S]{0,700}openInsertionChooser/.test(workspace),libraryLockedFixture=/consumer==='library'\?await import\('\.\/adapters\/library-fixtures\.js'\)/.test(main),learnUnbound=/consumer==='learn'\?createLearnRuntimeComposition\(\)/.test(main);assert(leftClick&&keyboard&&contextBlock&&contextGap,'OD-054 canonical routes were lost during replay');assert(chooserBound===true,'shared insertion chooser is not bound');assert(libraryLockedFixture===true,'final Library physical route cutover moved outside R6');assert(learnUnbound===true,'R6 Learn source binding dependency changed unexpectedly');return {leftClickChooser:true,keyboardChooser:true,rightClickDirectParagraph:true,canonicalChooserPresentationOnSharedConsumer:true,status:'OD054_REPLAY_CLEAN',libraryCurrentLockedRoute:'FIXTURE_BACKED__R6_CUTOVER_REQUIRED',learnCurrentRoute:'UNBOUND_SOURCE__R6_BINDING_REQUIRED'}}));
  results.push(run('S08.no-local-structured-owner-fork',()=>{const files=['surfaces/library/surface.ts','surfaces/library/runtime-composition.ts','surfaces/learn/surface.ts','adapters/learn.ts','adapters/context-library-structured.ts'];const forbidden=[];for(const file of files){const s=read(file);if(/class\s+StructuredSurfaceHost|function\s+StructuredSurfaceHost/.test(s))forbidden.push(file)}assert(forbidden.length===0,'local StructuredSurfaceHost fork detected');return {forbidden}}));
  return results;
}

const results=runS08Falsification(),fail=results.filter(row=>row.status==='FAIL');
console.log(JSON.stringify({lane:'S08_W01_W02_LIBRARY_LEARN',pass:results.length-fail.length,fail:fail.length,od054Closure:true,remainingDependency:'R6_REAL_LIBRARY_AND_LEARN_SOURCE_BINDING',results},null,2));
if(fail.length)process.exitCode=1;
