import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import net from 'node:net';
const require=createRequire(import.meta.url);
const {chromium}=require('playwright');
const root='/workspaces/cep-writer-baseline-repo';
const freePort=()=>new Promise(r=>{const s=net.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>r(p))})});
const port=await freePort();
console.log('port',port);
const server=spawn(process.execPath,[root+'/tools/serve.mjs','--port',String(port)],{cwd:root,stdio:'ignore'});
await new Promise(r=>setTimeout(r,1500));
const browser=await chromium.launch();
console.log('browser up');
const page=await browser.newPage({viewport:{width:1505,height:1045}});
page.on('pageerror',e=>console.log('PAGEERROR:',String(e.message).slice(0,400)));
page.on('console',m=>{if(m.type()==='error')console.log('CONSOLE:',String(m.text()).slice(0,400))});
await page.goto(`http://127.0.0.1:${port}/?surface=labs`,{waitUntil:'domcontentloaded',timeout:20000});
console.log('loaded');
await page.waitForTimeout(4000);
const info=await page.evaluate(()=>({consumer:window.CEPFoundation?.consumer||null,host:!!document.querySelector('#m0StructuredSpatial'),w03l:!!document.querySelector('.w03l'),left:!!document.querySelector('#domainLeftRegion'),body:(document.body.innerText||'').slice(0,200)}));
console.log(JSON.stringify(info));
await browser.close();server.kill();process.exit(0);
