import {WindowMotion,WINDOW_RESIZE_EDGES,constrainWindowGeometry} from '../../../foundation/window-motion.js';
import {StickyNoteWindowOwner} from '../../../foundation/notes/sticky-note-window.js';
import {OperationalSessionOwner} from '../../../foundation/operational/session-owner.js';
import {OperationalTerminalHost} from '../../../foundation/operational/terminal-host.js';
import {XtermOperationalTerminalRenderer} from '../../../foundation/operational/xterm-renderer.js';
import {W03V34RunsAdapter} from '../../../adapters/w03-runs.js';

const assert=(value,message='assertion failed')=>{if(!value)throw Error(message)};
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const test=(rows,id,run)=>{try{rows.push({id,status:'PASS',detail:run()??null})}catch(error){rows.push({id,status:'FAIL',error:String(error?.message||error)})}};
const viewport={width:1024,height:768,left:8,top:8,right:1016,bottom:760};
const fakeElement=()=>({style:{},setPointerCapture(){},releasePointerCapture(){}});
const pointer=(target,x,y,id=31)=>({button:0,target,clientX:x,clientY:y,pointerId:id,preventDefault(){}});
const providerFixture=()=>{const runtime=new W03V34RunsAdapter(),session=runtime.open(runtime.devices[0].id);return {runtime,session}};
const fakeRoot=()=>({className:'',hidden:false,dataset:{},style:{},innerHTML:'',removeAttribute(name){if(name==='style')this.style={}},querySelectorAll(){return []},querySelector(){return null}});

export function runS04SharedNotesOperationalTests(){
  const rows=[];
  test(rows,'s04.window-motion.constrain-explicit-geometry',()=>{const g=constrainWindowGeometry({x:2000,y:2000,width:1600,height:1200},{bounds:viewport,minWidth:320,minHeight:200,keepFullyVisible:true});assert(g.x===8&&g.y===8&&g.width===1008&&g.height===752);return g});
  test(rows,'s04.operational.keyboard-dialog-geometry-stays-reachable',()=>{const owner=new OperationalSessionOwner({viewport:()=>viewport});owner.setGeometry({x:5000,y:5000,width:4000,height:3000});const g=owner.snapshot().chrome.geometry;assert(g.x>=viewport.left&&g.y>=viewport.top&&g.x+g.width<=viewport.right&&g.y+g.height<=viewport.bottom);assert(owner.snapshot().lastTransition.viewportContained===true);return g});
  test(rows,'s04.operational.pointer-all-edge-corner-window-motion',()=>{const {runtime,session}=providerFixture(),owner=new OperationalSessionOwner({viewport:()=>viewport}),tab=owner.attachProviderSession(runtime,session.id);owner.setPlacement('floating');for(const edge of WINDOW_RESIZE_EDGES){owner.setGeometry({x:220,y:180,width:500,height:360});const element=fakeElement(),motion=new WindowMotion(()=>owner.motionBinding(tab.presentationId,element,{resizeEdge:edge})),e=pointer(element,400,300);assert(motion.down(e),edge);motion.move({...e,clientX:edge.includes('left')?440:edge.includes('right')?450:400,clientY:edge.includes('top')?335:edge.includes('bottom')?350:300});assert(motion.up(),edge);const g=owner.snapshot().chrome.geometry;assert(g.x>=viewport.left&&g.y>=viewport.top&&g.x+g.width<=viewport.right&&g.y+g.height<=viewport.bottom,edge)}return {edges:[...WINDOW_RESIZE_EDGES]}});
  test(rows,'s04.pin-semantics-shared-but-not-os-topmost',()=>{const sticky=new StickyNoteWindowOwner({viewport:()=>({width:1024,height:768,leftInset:8,rightInset:8,topInset:8,bottomInset:8})});sticky.register('n1');sticky.setPinned('n1',true);const {runtime,session}=providerFixture(),operational=new OperationalSessionOwner();operational.attachProviderSession(runtime,session.id);operational.setPinned(true);assert(sticky.presentation('n1').actions.pin.scope==='CEP_PRESENTATION_ONLY');assert(operational.snapshot().chrome.pinned===true&&operational.snapshot().lastTransition.scope==='CEP_PRESENTATION_ONLY');assert(sticky.window('n1').platform.alwaysOnTop.active===false);return {stickyPin:sticky.window('n1').pinned,operationalPin:operational.snapshot().chrome.pinned,osTopmostClaimed:false}});
  test(rows,'s04.sticky-separate-is-owning-surface-focus-intent',()=>{const calls=[],bridge={id:'s04-test-bridge',capabilities:()=>({alwaysOnTop:false,separateWindow:true}),requestSeparateWindow:req=>{calls.push(req);return {ok:true,active:true,code:'TEST_ONLY'}}},owner=new StickyNoteWindowOwner({capabilityBridge:bridge});owner.register('note-1');const result=owner.requestSeparateWindow('note-1');assert(result.ok===true&&result.detachScope==='OWNING_SURFACE'&&result.focusContext.kind==='STICKY_NOTE');assert(calls[0].detachScope==='OWNING_SURFACE'&&calls[0].focusContext.noteId==='note-1');assert(owner.presentation('note-1').actions.separateWindow.scope==='OWNING_SURFACE');return {request:calls[0],platformProofClaimed:false}});
  test(rows,'s04.operational-separate-is-owning-surface-and-preserves-provider-session',()=>{const calls=[],bridge={requestSeparateWindow:req=>{calls.push(req);return {ok:true,active:true,code:'TEST_ONLY'}}},{runtime,session}=providerFixture(),owner=new OperationalSessionOwner({platformWindowBridge:bridge}),tab=owner.attachProviderSession(runtime,session.id),before=runtime.session(session.id);const result=owner.detachWindow();assert(result.ok===true&&result.detachScope==='OWNING_SURFACE'&&result.focusContext.kind==='OPERATIONAL_TERMINAL');assert(result.providerSessionPreserved===true&&runtime.session(session.id)===before&&owner.tab(tab.presentationId));assert(calls[0].runtimeSessionId===session.id&&calls[0].detachScope==='OWNING_SURFACE');return {detachScope:result.detachScope,runtimeSessionId:result.runtimeSessionId,providerSessionPreserved:true}});
  test(rows,'s04.operational-separate-unavailable-does-not-fake-detached-state',()=>{const {runtime,session}=providerFixture(),owner=new OperationalSessionOwner(),tab=owner.attachProviderSession(runtime,session.id),result=owner.detachWindow(),snapshot=owner.snapshot();assert(result.ok===false&&result.code==='PLATFORM_WINDOW_UNAVAILABLE'&&result.detachScope==='OWNING_SURFACE');assert(snapshot.chrome.detached===false&&snapshot.chrome.detachedPresentationId===null);assert(owner.tab(tab.presentationId)?.runtimeSessionId===session.id);return {code:result.code,detached:snapshot.chrome.detached,providerSessionPreserved:result.providerSessionPreserved}});
  test(rows,'s04.recorded-readonly-terminal-remains-visible',()=>{const {runtime,session}=providerFixture(),owner=new OperationalSessionOwner(),tab=owner.attachProviderSession(runtime,session.id);runtime.session(session.id).recorded=true;const root=fakeRoot(),renderer={id:'S04ReadOnlyRenderer',kind:'TEST_RENDERER',descriptor(){return {id:this.id,kind:this.kind}},render(){return '<div data-proof="recorded"></div>'}},host=new OperationalTerminalHost(root,owner,{renderer});host.setReadOnly(true,{render:false});host.render();assert(root.hidden===false&&root.dataset.readOnly==='true');assert(root.innerHTML.includes('Read only')&&root.innerHTML.includes('data-proof="recorded"'));assert(owner.tab(tab.presentationId)?.runtimeSessionId===session.id);return {hidden:root.hidden,readOnly:root.dataset.readOnly,runtimeSessionPreserved:true}});
  test(rows,'s04.xterm-recorded-render-is-visible-and-readonly',()=>{const renderer=new XtermOperationalTerminalRenderer(),markup=renderer.render({session:{id:'recorded-1',recorded:true,lines:[{command:'show status',output:'UP'}]},provider:{id:'recorded',label:'Recorded provider',connected:true},presentationId:'p-recorded',readOnly:true});assert(markup.includes('data-xterm-presentation="p-recorded"')&&markup.includes('aria-readonly="true"'));assert(markup.includes('data-terminal-state="read-only"'));return {readOnly:true,providerProcessClaimed:false}});
  test(rows,'s04.close-hide-do-not-delete-or-terminate',()=>{const domain={content:{blocks:[{id:'b1',html:'keep'}]},binding:{documentId:'KU-1'}},before=JSON.stringify(domain),sticky=new StickyNoteWindowOwner();sticky.register('n-close');const hidden=sticky.hide('n-close');const {runtime,session}=providerFixture(),owner=new OperationalSessionOwner(),tab=owner.attachProviderSession(runtime,session.id);owner.closeChrome();assert(JSON.stringify(domain)===before&&hidden.window.lifecycle==='hidden');assert(runtime.session(session.id)===session&&owner.tab(tab.presentationId)?.runtimeSessionId===session.id);return {noteContentPreserved:true,runtimeSessionPreserved:true}});
  test(rows,'s04.geometry-cancel-remains-exact',()=>{const {runtime,session}=providerFixture(),owner=new OperationalSessionOwner({viewport:()=>viewport}),tab=owner.attachProviderSession(runtime,session.id);owner.setPlacement('floating');owner.setGeometry({x:200,y:160,width:520,height:360});const before=owner.snapshot().chrome.geometry,element=fakeElement(),motion=new WindowMotion(()=>owner.motionBinding(tab.presentationId,element,{resizeEdge:'bottom-right'})),e=pointer(element,300,300);assert(motion.down(e));motion.move({...e,clientX:380,clientY:370});assert(!same(owner.snapshot().chrome.geometry,before));assert(motion.cancel('Escape'));assert(same(owner.snapshot().chrome.geometry,before));return {before,after:owner.snapshot().chrome.geometry}});
  const failures=rows.filter(row=>row.status==='FAIL');return {schemaVersion:1,kind:'OD057_S04_SHARED_NOTES_WINDOW_OPERATIONAL_FOCUSED_TESTS',classification:'SPECIALIST_CANDIDATE_EVIDENCE_ONLY__NO_SELF_PROMOTION',status:failures.length?'FAIL':'PASS',caseCount:rows.length,passCount:rows.length-failures.length,failCount:failures.length,rows};
}

const invoked=typeof process!=='undefined'&&process.argv?.[1]&&import.meta.url===new URL(`file://${process.argv[1]}`).href;
if(invoked){const result=runS04SharedNotesOperationalTests();console.log(JSON.stringify(result,null,2));if(result.status!=='PASS')process.exitCode=1;}
