import assert from 'node:assert/strict';
import {CommandRegistry} from '../../../dist/foundation/models.js';
import {VisualizeDomainAdapter} from '../../../dist/adapters/visualize/domain.js';
import {bindVisualizeSurface} from '../../../dist/surfaces/visualize/surface.js';
const adapter=new VisualizeDomainAdapter({representations:[{representationId:'rep-a',canonicalRef:{id:'obj-a',revision:'r1'},x:0,y:0},{representationId:'rep-b',canonicalRef:{id:'obj-b',revision:'r1'},x:100,y:50}]});
assert.equal(adapter.canonicalProjection().status,'VISUALIZE_CANONICAL_DATA_PROVIDER_UNAVAILABLE');
assert.equal(adapter.descriptor().fixtureIsCanonical,false);
const before=JSON.stringify(adapter.model.edges);
assert.equal(adapter.move(['rep-a'],20,10).ok,true);
assert.equal(JSON.stringify(adapter.model.edges),before);
const snapshot=JSON.stringify(adapter.representationProjection());
assert.equal(adapter.move(['rep-a'],Number.POSITIVE_INFINITY,0).ok,false);
assert.equal(JSON.stringify(adapter.representationProjection()),snapshot);
adapter.model.selection=new Set(['rep-a','rep-b']);
assert.equal(adapter.align('x').ok,true);
const commands=new CommandRegistry();const bound=bindVisualizeSurface({commands,adapter});
assert.equal(bound.canonicalDataProvider,'UNAVAILABLE');
assert.equal(bound.spatialOwner,'SpatialInteractionKernel');
console.log(JSON.stringify({surface:'visualize',status:'PASS',cases:9,canonicalProvider:'UNAVAILABLE'}));
