import {normalizeOperationalTerminalState,operationalStateData} from './presentation.js';
import {TERMINAL_RENDERER_PORT_CONTRACT} from './terminal-renderer-port.js';
const html=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let modulePromise=null;function ensureCss(){if(globalThis.document&&!document.querySelector('link[data-cep-xterm]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/vendor/xterm/xterm.css';l.dataset.cepXterm='true';document.head.append(l)}}
async function module(){ensureCss();if(modulePromise)return modulePromise;if(typeof globalThis.window==='undefined'){try{return modulePromise=import(new URL('../../vendor/xterm/xterm.mjs',import.meta.url).href);}catch{}}return modulePromise=import('/vendor/xterm/xterm.mjs');}
export class XtermOperationalTerminalRenderer{
 constructor(){this.id='XtermOperationalTerminalRenderer';this.kind='XTERM_JS';this.contract=TERMINAL_RENDERER_PORT_CONTRACT;this.instances=new Map();this.buffers=new Map();}
 descriptor(){return {id:this.id,kind:this.kind,contract:this.contract,package:'@xterm/xterm',rendererOnly:true,semanticCommandOwnership:false,canonicalStateOwnership:false,processLifecycleOwnership:false};}
 render({session,provider,presentationId,readOnly=false}){const state=normalizeOperationalTerminalState(provider,session),inputReadOnly=readOnly||session?.recorded===true||state.state==='read-only';return `<div class="terminal-state"><span class="state-token" data-state="${html(operationalStateData(state.state))}" role="status" aria-live="polite">${html(state.label)}</span>${state.detail?`<span>${html(state.detail)}</span>`:''}</div><div class="terminal-output xterm-host" role="application" aria-label="${html(provider.label||provider.id||'Runtime')} terminal" aria-readonly="${inputReadOnly}" tabindex="0" dir="ltr" data-xterm-presentation="${html(presentationId)}" data-terminal-state="${html(state.state)}"></div>`;}
 async mount({root,session,provider,providerRuntime=null,presentationId,readOnly=false,routeInput,routeResize}){const escCss=v=>globalThis.CSS?.escape?globalThis.CSS.escape(v):String(v).replace(/["\\]/g,'\\$&');const host=root.querySelector(`[data-xterm-presentation="${escCss(presentationId)}"]`);if(!host)return;const {Terminal}=await module();const state=normalizeOperationalTerminalState(provider,session),inputReadOnly=readOnly||session?.recorded===true||state.state==='read-only';let entry=this.instances.get(presentationId);const bindInput=(term,target)=>{target.disposables.push(term.onData(data=>{if(target.readOnly)return;if(target.provider.rawTerminal||target.provider.pty||target.provider.conpty){target.routeInput?.({presentationId,rawInput:data,rawStream:true});return}let b=this.buffers.get(presentationId)||'';for(const ch of data){if(ch==='\r'){const command=b;this.buffers.set(presentationId,'');term.write('\r\n');if(command.trim()){const receipt=target.routeInput?.({presentationId,rawInput:command,rawStream:false});if(receipt&&typeof receipt==='object'&&'output' in receipt)term.writeln(String(receipt.output??''));}}else if(ch==='\u007f'){b=b.slice(0,-1);this.buffers.set(presentationId,b);term.write('\b \b');}else if(ch>=' '){b+=ch;this.buffers.set(presentationId,b);term.write(ch);}}}));target.disposables.push(term.onResize(size=>target.routeResize?.({presentationId,cols:size.cols,rows:size.rows})));};if(!entry){const term=new Terminal({convertEol:true,cursorBlink:true,scrollback:5000,allowProposedApi:false,disableStdin:inputReadOnly});term.open(host);entry={term,disposables:[],lastOutputBytes:0,lastLineCount:0,generation:Number(session?.outputGeneration??session?.restartCount??0),readOnly:inputReadOnly,provider,routeInput,routeResize};this.instances.set(presentationId,entry);bindInput(term,entry);}else if(!entry.term.element?.isConnected){for(const d of entry.disposables)d.dispose?.();entry.term.dispose();this.instances.delete(presentationId);entry=null;const term=new Terminal({convertEol:true,cursorBlink:true,scrollback:5000,allowProposedApi:false,disableStdin:inputReadOnly});term.open(host);entry={term,disposables:[],lastOutputBytes:0,lastLineCount:0,generation:Number(session?.outputGeneration??session?.restartCount??0),readOnly:inputReadOnly,provider,routeInput,routeResize};this.instances.set(presentationId,entry);bindInput(term,entry);}else{entry.readOnly=inputReadOnly;entry.provider=provider;entry.routeInput=routeInput;entry.routeResize=routeResize;entry.term.options.disableStdin=inputReadOnly;host.setAttribute('aria-readonly',String(inputReadOnly));}
    if(provider.rawTerminal||provider.pty||provider.conpty){const generation=Number(session?.outputGeneration??session?.restartCount??0);if(generation!==entry.generation){entry.term.reset();entry.lastOutputBytes=0;entry.generation=generation}if(providerRuntime?.subscribe&&!entry.streamSubscription){entry.streamSubscription=providerRuntime.subscribe(session.id,event=>{if(event?.type==='reset'){entry.term.reset();entry.lastOutputBytes=0;entry.generation=Number(event.generation)||0;return}if(event?.type==='output'&&event.data){entry.term.write(event.data);entry.lastOutputBytes+=event.data.length}if(event?.type==='error')entry.term.writeln(`\r\n[provider error] ${String(event.error||'unknown')}`)});entry.disposables.push(entry.streamSubscription)}const raw=session?.rawOutputBase64?Uint8Array.from(atob(session.rawOutputBase64),c=>c.charCodeAt(0)):null;if(raw&&raw.length>entry.lastOutputBytes){const chunk=raw.slice(entry.lastOutputBytes);entry.term.write(chunk);entry.lastOutputBytes=raw.length;}}
   else {const lines=Array.isArray(session?.lines)?session.lines:[];for(let i=entry.lastLineCount;i<lines.length;i++){const line=lines[i];entry.term.writeln(`${line.command}`);entry.term.writeln(String(line.output??''));}entry.lastLineCount=lines.length;if(!lines.length&&provider.help&&entry.lastLineCount===0)entry.term.writeln(provider.help);}
   queueMicrotask(()=>entry.term.focus());
 }
 dispose(presentationId){const e=this.instances.get(presentationId);if(e){for(const d of e.disposables)d.dispose?.();e.term.dispose();this.instances.delete(presentationId);this.buffers.delete(presentationId)}}
}
