import http from 'node:http';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {resolve,join,basename} from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {CepSqlitePersistenceProvider,canonicalJson} from './persistence/sqlite-persistence-provider.mjs';
import {WindowsPlatformSidecar} from './platform/windows-sidecar.mjs';
import {ConptyTerminalManager} from './terminal/conpty-terminal-manager.mjs';
import {BackupRestoreCapability} from './backup/backup-restore-capability.mjs';
import {HealthCapability} from './health/health-capability.mjs';
import {ProcessingCapability} from './processing/processing-capability.mjs';
import {AuditEventProvider} from './audit/audit-event-provider.mjs';
const DEFAULT_RUNTIME_ROOT=fileURLToPath(new URL('./runtime-data/',import.meta.url));
const HOST=process.env.CEP_LOCAL_RUNTIME_HOST||'127.0.0.1',PORT=process.env.CEP_LOCAL_RUNTIME_PORT===undefined?4174:Number(process.env.CEP_LOCAL_RUNTIME_PORT),ROOT=resolve(process.env.CEP_LOCAL_RUNTIME_ROOT||DEFAULT_RUNTIME_ROOT),DB=resolve(process.env.CEP_SQLITE_PATH||join(ROOT,'cep.sqlite')),STAGING=resolve(process.env.CEP_STAGING_ROOT||join(ROOT,'staging'));
mkdirSync(ROOT,{recursive:true});mkdirSync(STAGING,{recursive:true});
const provider=new CepSqlitePersistenceProvider({databasePath:DB,faultMode:process.env.CEP_PERSISTENCE_FAULT_MODE||'none'});
const platformSidecar=new WindowsPlatformSidecar();
const detachContexts=new Map(),DETACH_CONTEXT_TTL_MS=5*60*1000;
const terminalManager=new ConptyTerminalManager();
const audit=new AuditEventProvider({root:join(ROOT,'audit')});
const backupRestore=new BackupRestoreCapability({persistenceProvider:provider,root:join(ROOT,'backup-restore'),auditProvider:audit});
const processing=new ProcessingCapability({statePath:join(ROOT,'processing','state.json'),auditProvider:audit});
const processingHealthFacts=()=>processing.healthFacts({freshnessMs:5000});
const health=new HealthCapability({root:join(ROOT,'health'),sources:[
  {sourceId:'health.local-runtime',kind:'Observation',freshnessMs:10000,observe:()=>({status:'AVAILABLE',observedAt:new Date().toISOString(),freshnessMs:10000,sourceIdentity:'CEP_LOCAL_RUNTIME',value:{node:process.version,host:HOST,driverId:'node:sqlite'},providerEvidence:{actualProbe:true}})},
  {sourceId:'health.persistence.sqlite',kind:'Observation',freshnessMs:10000,observe:()=>{const integrity=provider.integrityCheck(),foreignKeys=provider.foreignKeyCheck(),integrityOk=integrity.every(row=>String(row.integrity_check??Object.values(row)[0]).toLowerCase()==='ok'),foreignKeysOk=foreignKeys.length===0;return {status:integrityOk&&foreignKeysOk?'AVAILABLE':'ERROR',observedAt:new Date().toISOString(),freshnessMs:10000,sourceIdentity:'CepSqlitePersistenceProvider:node:sqlite',value:{integrityOk,foreignKeysOk,driverId:'node:sqlite'},error:integrityOk&&foreignKeysOk?null:'PERSISTENCE_VALIDATION_FAILED',providerEvidence:{actualProbe:true}}}},
  {sourceId:'health.processing.worker',kind:'WorkerLiveness',freshnessMs:5000,observe:()=>{const facts=processingHealthFacts(),worker=facts.workers.sort((a,b)=>String(b.observedAt).localeCompare(String(a.observedAt)))[0];return worker?{status:worker.state==='ALIVE'?'AVAILABLE':'STALE',observedAt:worker.observedAt,freshnessMs:worker.freshnessMs,sourceIdentity:facts.sourceId,value:{workerId:worker.workerId,state:worker.state,ageMs:worker.ageMs,providerId:facts.provider.id},providerEvidence:{actualWorkerHeartbeat:true}}:{status:'UNAVAILABLE',observedAt:new Date().toISOString(),freshnessMs:5000,sourceIdentity:facts.sourceId,value:{state:'UNKNOWN',workerId:null},error:'NO_WORKER_HEARTBEAT',providerEvidence:{actualWorkerHeartbeat:false}}}},
  {sourceId:'health.processing.queue',kind:'QueueMetric',freshnessMs:5000,observe:()=>{const facts=processingHealthFacts();return {status:'AVAILABLE',observedAt:facts.queue.observedAt,freshnessMs:5000,sourceIdentity:facts.sourceId,value:{queueId:facts.queue.queueId,depth:facts.queue.depth},providerEvidence:{actualQueueRead:true}}}}
]});
const sha256=value=>createHash('sha256').update(value).digest('hex'),safeLabel=value=>basename(String(value||'artifact')).replace(/[^A-Za-z0-9._-]+/g,'_').slice(0,80)||'artifact';
function headers(req,extra={}){const origin=req.headers.origin;return {'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...(origin?{'access-control-allow-origin':origin,'vary':'Origin'}:{}),...extra}}
function json(req,res,status,body){const payload=JSON.stringify(body);res.writeHead(status,{...headers(req),'content-length':Buffer.byteLength(payload)});res.end(payload)}
async function body(req){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>2*1024*1024)throw Object.assign(new Error('REQUEST_TOO_LARGE'),{status:413});chunks.push(chunk)}const text=Buffer.concat(chunks).toString('utf8');return text?JSON.parse(text):{}}
const capabilities=()=>Object.freeze({persistence:{availability:'AVAILABLE',driverId:'node:sqlite',semanticOwner:'StructuredTransactionHistoryRecoveryOwner'},backup:{availability:'AVAILABLE',boundedDestination:true},backupRestore:backupRestore.descriptor(),auditEventProvider:audit.descriptor(),healthDomain:health.descriptor(),processing:processing.descriptor(),importExport:{availability:'AVAILABLE',stagedOnly:true,canonicalPublication:false},platformWindow:{availability:platformSidecar.windowAvailable()?'AVAILABLE':'UNAVAILABLE',providerId:'cep-win32-sidecar',providerEpoch:platformSidecar.epoch,prerequisite:'EDGE_APP_RUNTIME'},activeKeyboardSource:{availability:platformSidecar.available()?'AVAILABLE':'UNAVAILABLE',providerId:'cep-win32-sidecar',providerEpoch:platformSidecar.epoch},terminalRuntime:{...terminalManager.descriptor()},shell:{availability:terminalManager.available()?'AVAILABLE_VIA_TERMINAL_RUNTIME':'UNAVAILABLE'},processExecution:{availability:terminalManager.available()?'AVAILABLE_VIA_TERMINAL_RUNTIME':'UNAVAILABLE'},ssh:{availability:terminalManager.available()?'AVAILABLE_VIA_OWNER_SELECTED_PROFILE':'UNAVAILABLE'},pty:{availability:terminalManager.available()?'AVAILABLE':'UNAVAILABLE'},powerShell:{availability:terminalManager.available()?'AVAILABLE_AS_PROFILE':'UNAVAILABLE'},docker:{availability:'UNAVAILABLE'},vmWsl:{availability:'UNAVAILABLE'}});
const server=http.createServer(async(req,res)=>{try{
  if(req.method==='OPTIONS'){res.writeHead(204,{...headers(req),'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type'});return res.end()}
  const url=new URL(req.url||'/','http://127.0.0.1');const p=url.pathname;
  if(req.method==='GET'&&p==='/v1/capabilities')return json(req,res,200,{ok:true,node:process.version,host:HOST,capabilities:capabilities()});
  if(req.method==='POST'&&p==='/v1/platform/detach-context'){const b=await body(req),token=randomUUID(),createdAt=Date.now();detachContexts.set(token,{kind:String(b.kind||'DETACHED_CONTEXT'),payload:b.payload??null,createdAt,expiresAt:createdAt+DETACH_CONTEXT_TTL_MS});return json(req,res,200,{ok:true,token,ephemeral:true,canonicalPersistence:false,expiresAt:new Date(createdAt+DETACH_CONTEXT_TTL_MS).toISOString()})}
  if(req.method==='GET'&&p.startsWith('/v1/platform/detach-context/')){const token=decodeURIComponent(p.slice('/v1/platform/detach-context/'.length)),entry=detachContexts.get(token);if(!entry)return json(req,res,404,{ok:false,code:'DETACH_CONTEXT_NOT_FOUND'});detachContexts.delete(token);if(entry.expiresAt<Date.now())return json(req,res,410,{ok:false,code:'DETACH_CONTEXT_EXPIRED'});return json(req,res,200,{ok:true,kind:entry.kind,payload:entry.payload,ephemeral:true,consumed:true,canonicalPersistence:false})}

if(req.method==='GET'&&p==='/v1/platform/describe'){const result=await platformSidecar.describe();return json(req,res,result.ok===false?503:200,{...result,availability:result.ok===false?'UNAVAILABLE':'AVAILABLE'})}
if(req.method==='GET'&&p==='/v1/platform/input-direction'){const result=await platformSidecar.inputDirection();return json(req,res,result.ok===false?503:200,result)}
if(req.method==='POST'&&p==='/v1/platform/window/open'){const b=await body(req);const result=await platformSidecar.openDetached(b.presentationId,b.url);return json(req,res,result.ok===false?503:200,result)}
if(req.method==='POST'&&p==='/v1/platform/window/focus'){const b=await body(req),result=await platformSidecar.focus(b.presentationId);return json(req,res,result.ok===false?503:200,result)}
if(req.method==='POST'&&p==='/v1/platform/window/close'){const b=await body(req),result=await platformSidecar.close(b.presentationId);return json(req,res,result.ok===false?503:200,result)}
if(req.method==='POST'&&p==='/v1/platform/window/bounds'){const b=await body(req),result=await platformSidecar.bounds(b.presentationId);return json(req,res,result.ok===false?503:200,result)}
if(req.method==='POST'&&p==='/v1/platform/window/topmost'){const b=await body(req),result=await platformSidecar.topmost(b.presentationId,b.requested===true);return json(req,res,result.ok===false?503:200,result)}
if(req.method==='POST'&&p==='/v1/terminal/open'){const b=await body(req);try{const session=terminalManager.open(b);return json(req,res,200,{ok:true,session})}catch(error){return json(req,res,503,{ok:false,code:String(error?.message||error)})}}
if(req.method==='GET'&&p.startsWith('/v1/terminal/session/')){const id=decodeURIComponent(p.slice('/v1/terminal/session/'.length)),cursor=Number(url.searchParams.get('cursor')||0),session=terminalManager.session(id);if(!session)return json(req,res,404,{ok:false,code:'TERMINAL_SESSION_NOT_FOUND'});return json(req,res,200,{ok:true,session,...terminalManager.output(id,cursor)})}
if(req.method==='POST'&&p==='/v1/terminal/input'){const b=await body(req);try{const data=Buffer.from(String(b.dataBase64||''),'base64');return json(req,res,200,{ok:true,...await terminalManager.write(b.sessionId,data)})}catch(error){return json(req,res,422,{ok:false,code:String(error?.message||error)})}}
if(req.method==='POST'&&p==='/v1/terminal/resize'){const b=await body(req);try{return json(req,res,200,{ok:true,...await terminalManager.resize(b.sessionId,b.cols,b.rows)})}catch(error){return json(req,res,422,{ok:false,code:String(error?.message||error)})}}
if(req.method==='POST'&&p==='/v1/terminal/close'){const b=await body(req);try{return json(req,res,200,{ok:true,...await terminalManager.close(b.sessionId)})}catch(error){return json(req,res,422,{ok:false,code:String(error?.message||error)})}}
if(req.method==='POST'&&p==='/v1/terminal/restart'){const b=await body(req);try{const session=await terminalManager.restart(b.sessionId);return json(req,res,200,{ok:true,session})}catch(error){return json(req,res,422,{ok:false,code:String(error?.message||error)})}}


  if(req.method==='POST'&&p==='/v1/backup/package'){const b=await body(req),result=await backupRestore.createPackage({label:b.label,correlationId:b.correlationId});return json(req,res,result.ok?200:422,result)}
  if(req.method==='POST'&&p==='/v1/backup/preview'){const b=await body(req),result=backupRestore.previewPackage(b.packageId);return json(req,res,result.ok?200:422,result)}
  if(req.method==='POST'&&p==='/v1/backup/drill'){const b=await body(req),result=backupRestore.drill({packageId:b.packageId,correlationId:b.correlationId});return json(req,res,result.ok?200:422,result)}
  if(req.method==='GET'&&p.startsWith('/v1/backup/drill/')){const id=decodeURIComponent(p.slice('/v1/backup/drill/'.length)),result=backupRestore.readDrill(id);return result?json(req,res,200,{ok:true,...result}):json(req,res,404,{ok:false,code:'DRILL_NOT_FOUND'})}
  if(req.method==='GET'&&p==='/v1/backup/attempts')return json(req,res,200,{ok:true,attempts:backupRestore.listAttempts({operation:url.searchParams.get('operation')||null,packageId:url.searchParams.get('packageId')||null})});
  if(req.method==='GET'&&p.startsWith('/v1/backup/attempt/')){const id=decodeURIComponent(p.slice('/v1/backup/attempt/'.length)),attempt=backupRestore.readAttempt(id);return attempt?json(req,res,200,{ok:true,attempt}):json(req,res,404,{ok:false,code:'BACKUP_ATTEMPT_NOT_FOUND'})}
  if(req.method==='POST'&&p==='/v1/backup/activation-request'){const b=await body(req),result=backupRestore.requestActivation({drillId:b.drillId,reason:b.reason,correlationId:b.correlationId});return json(req,res,result.ok?200:422,result)}
  if(req.method==='POST'&&p==='/v1/audit/events'){const b=await body(req),result=audit.append(b);return json(req,res,result.ok?201:422,result)}
  if(req.method==='GET'&&p==='/v1/audit/events'){const result=audit.search({actor:url.searchParams.get('actor')||undefined,action:url.searchParams.get('action')||undefined,target:url.searchParams.get('target')||undefined,outcome:url.searchParams.get('outcome')||undefined,correlationId:url.searchParams.get('correlationId')||undefined,from:url.searchParams.get('from')||undefined,to:url.searchParams.get('to')||undefined,limit:url.searchParams.get('limit')||undefined,cursor:url.searchParams.get('cursor')||undefined});return json(req,res,200,result)}
  if(req.method==='GET'&&p==='/v1/audit/verify')return json(req,res,200,audit.verify());
  if(req.method==='POST'&&p==='/v1/audit/annotations'){const b=await body(req),result=audit.annotate({eventId:b.eventId,actor:b.actor,note:b.note});return json(req,res,result.ok?201:422,result)}
  {const match=p.match(/^\/v1\/audit\/events\/([^/]+)\/annotations$/);if(req.method==='GET'&&match){const eventId=decodeURIComponent(match[1]);return json(req,res,200,{ok:true,eventId,annotations:audit.listAnnotations(eventId)})}}
  if(req.method==='POST'&&p==='/v1/health/refresh'){const result=await health.refresh();return json(req,res,200,result)}
  if(req.method==='GET'&&p==='/v1/health/observations')return json(req,res,200,health.observations());
  if(req.method==='POST'&&p==='/v1/health/diagnostic'){const b=await body(req),result=await health.runDiagnostic({requestedBy:b.requestedBy||'health-surface'});return json(req,res,200,result)}
  if(req.method==='POST'&&p==='/v1/processing/jobs'){const b=await body(req),result=processing.createJob({requestId:b.requestId,correlationId:b.correlationId,input:b.input,taskKind:b.taskKind||'SHA256_JSON'});return json(req,res,result.ok?200:422,result)}
  if(req.method==='GET'&&p==='/v1/processing/jobs')return json(req,res,200,{ok:true,jobs:processing.listJobs()});
  if(req.method==='GET'&&p.startsWith('/v1/processing/jobs/')){const id=decodeURIComponent(p.slice('/v1/processing/jobs/'.length)),job=processing.readJob(id);return job?json(req,res,200,{ok:true,job}):json(req,res,404,{ok:false,code:'JOB_NOT_FOUND'})}
  if(req.method==='POST'&&p==='/v1/processing/worker/run-once'){const b=await body(req),result=await processing.runOnce({workerId:b.workerId||'local-processing-worker',leaseMs:b.leaseMs});return json(req,res,result.ok?200:result.code==='TASK_KIND_NOT_SUPPORTED'?422:500,result)}
  {const match=p.match(/^\/v1\/processing\/jobs\/([^/]+)\/(retry|cancel-request|validation-handoff)$/);if(req.method==='POST'&&match){const id=decodeURIComponent(match[1]),action=match[2],b=await body(req);const result=action==='retry'?processing.retry(id,{idempotencyKey:b.idempotencyKey}):action==='cancel-request'?processing.requestCancel(id,{requestId:b.requestId}):processing.requestValidationHandoff(id,{consumerId:b.consumerId||'processing-safety-validator'});return json(req,res,result.ok?200:422,result)}}
  if(req.method==='POST'&&p==='/v1/processing/validation-ack'){const b=await body(req),result=processing.acknowledgeValidation({handoffId:b.handoffId,consumerId:b.consumerId||'processing-safety-validator',accepted:b.accepted!==false});return json(req,res,result.ok?200:422,result)}
  if(req.method==='GET'&&p==='/v1/persistence/health')return json(req,res,200,{ok:true,node:process.version,driverId:'node:sqlite',host:HOST,integrity:provider.integrityCheck(),foreignKeys:provider.foreignKeyCheck(),semanticOwner:'StructuredTransactionHistoryRecoveryOwner'});
  if(req.method==='POST'&&p==='/v1/persistence/bootstrap'){const b=await body(req);if(!b.document?.id)return json(req,res,422,{ok:false,code:'DOCUMENT_REQUIRED'});return json(req,res,200,provider.bootstrap(b.document,{domainKind:b.domainKind,surface:b.surface,provenance:b.provenance||b.document?.provenance||{},sourceKind:b.sourceKind||b.domainKind}))}
  if(req.method==='GET'&&p.startsWith('/v1/persistence/document/')){const id=decodeURIComponent(p.slice('/v1/persistence/document/'.length)),found=provider.readCommitted(id);return found?json(req,res,200,{ok:true,...found}):json(req,res,404,{ok:false,code:'DOCUMENT_NOT_FOUND'})}
  if(req.method==='POST'&&p==='/v1/persistence/save'){const b=await body(req);if(b.operation!=='EXPLICIT_SAVE')return json(req,res,422,{ok:false,code:'EXPLICIT_SAVE_OPERATION_REQUIRED'});const result=provider.saveStructuredDocument(b.document,{...b.context,requestId:b.requestId});return json(req,res,result.ok?200:result.code==='STALE_BASE'?409:500,result)}
  if(req.method==='POST'&&p==='/v1/persistence/autosave'){const b=await body(req);if(b.operation!=='AUTOSAVE_DRAFT_ONLY')return json(req,res,422,{ok:false,code:'AUTOSAVE_OPERATION_REQUIRED'});return json(req,res,200,provider.autosaveWorkingDraft({document:b.document,baseRevisionId:b.context?.baseRevisionId,workingRevision:b.context?.workingRevision,dirty:b.context?.dirty!==false}))}
  if(req.method==='POST'&&p==='/v1/persistence/recovery'){const b=await body(req);if(b.operation!=='RECOVERY_POINT_ONLY')return json(req,res,422,{ok:false,code:'RECOVERY_OPERATION_REQUIRED'});return json(req,res,200,provider.captureRecovery({recoveryId:b.context?.recoveryId,document:b.document,baseRevisionId:b.context?.baseRevisionId,workingRevision:b.context?.workingRevision,reason:b.context?.reason}))}
  if(req.method==='GET'&&p.startsWith('/v1/persistence/recovery-point/')){const id=decodeURIComponent(p.slice('/v1/persistence/recovery-point/'.length)),found=provider.readRecovery(id);return found?json(req,res,200,{ok:true,...found}):json(req,res,404,{ok:false,code:'RECOVERY_NOT_FOUND'})}
  if(req.method==='GET'&&p.startsWith('/v1/persistence/recovery/')){const id=decodeURIComponent(p.slice('/v1/persistence/recovery/'.length));return json(req,res,200,{ok:true,documentId:id,recovery:provider.listRecovery(id)})}
  if(req.method==='POST'&&p==='/v1/backup/stage'){const b=await body(req);if(b.packageId){const result=backupRestore.stage({packageId:b.packageId,correlationId:b.correlationId});return json(req,res,result.ok?200:422,result)}const fileName=`${safeLabel(b.label)}-${Date.now()}.sqlite`,target=join(STAGING,fileName),receipt=await provider.backupTo(target);return json(req,res,200,{ok:true,operationKind:'LEGACY_BOUNDED_SNAPSHOT_STAGE',fileName,targetRootBounded:true,driverId:'node:sqlite',receipt:{...receipt,targetPath:undefined}})}
  if(req.method==='POST'&&p==='/v1/export/stage'){const b=await body(req),payload=canonicalJson({schema:'CEP_PSC_EXPORT_STAGE_V1',canonicalPublication:false,stagedOnly:true,provenance:b.provenance||null,payload:b.payload??null}),digest=sha256(payload),fileName=`${safeLabel(b.label)}-${digest.slice(0,12)}.json`;writeFileSync(join(STAGING,fileName),payload,'utf8');return json(req,res,200,{ok:true,fileName,sha256:digest,targetRootBounded:true,stagedOnly:true,canonicalPublication:false})}
  if(req.method==='POST'&&p==='/v1/import/validate'){const b=await body(req),payload=canonicalJson(b.payload??null),computed=sha256(payload),claimed=String(b.sourceSha256||''),identity=String(b.sourceIdentity||''),valid=/^[a-f0-9]{64}$/i.test(claimed)&&claimed===computed&&!!identity&&!/^\d+$/.test(identity),importId=String(b.importId||randomUUID()),result=provider.stageImport({importId,sourceIdentity:identity||'invalid',sourceSha256:claimed||'0'.repeat(64),targetKind:String(b.targetKind||'structured'),payload:b.payload,valid});return json(req,res,valid?200:422,{...result,computedSha256:computed,reason:valid?null:'IMPORT_VALIDATION_FAILED'})}
  return json(req,res,404,{ok:false,code:'NOT_FOUND'});
}catch(error){return json(req,res,error?.status||500,{ok:false,code:'LOCAL_RUNTIME_ERROR',message:String(error?.message||error)})}});
server.listen(PORT,HOST,()=>{const address=server.address(),port=typeof address==='object'&&address?address.port:PORT;console.log(JSON.stringify({ok:true,host:HOST,port,baseUrl:`http://${HOST}:${port}`,node:process.version,driverId:'node:sqlite',databasePath:DB,stagingRoot:STAGING}))});
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>server.close(()=>{try{platformSidecar.stop();provider.close()}finally{process.exit(0)}}));
