import {VISUALIZE_DOMAIN_OWNER,VISUALIZE_VIEW_MODES} from '../../adapters/visualize/domain.js';
const hasCommand=(registry,id)=>registry?.commands instanceof Map&&registry.commands.has(id);
const register=(registry,id,label,run,available=()=>true)=>{if(!hasCommand(registry,id))registry.register(id,VISUALIZE_DOMAIN_OWNER,label,run,available);return id;};
const SHARED_SPATIAL_COMMANDS=Object.freeze(['spatial.connect','spatial.relation.commit','relation.edit','relation.undo','relation.redo','spatial.fit','spatial.align','spatial.distribute']);
const VIEW_COMMANDS=Object.freeze(Object.fromEntries(VISUALIZE_VIEW_MODES.map(mode=>[mode,`visualize.view.${mode.toLowerCase()}`])));
const normalizeMode=value=>VISUALIZE_VIEW_MODES.includes(String(value||'').toUpperCase())?String(value).toUpperCase():null;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

export function bindVisualizeSurface({commands,adapter,workspace=null,initialView='TREE',contextProvider=null,onViewChange=null,onRepresentationChange=null}={}){
  if(!commands||!adapter)throw Error('VISUALIZE_SURFACE_BINDING_REQUIRED');
  let activeView=normalizeMode(initialView)||'TREE';
  const baseContext=()=>{try{const value=typeof contextProvider==='function'?contextProvider():{};return value&&typeof value==='object'?value:{}}catch{return {}}};
  const payloadWithView=(payload={})=>{const explicit=String(payload?.mode||'').trim();return {...baseContext(),...(payload||{}),mode:explicit?explicit.toUpperCase():activeView};};
  const setView=(mode,{route='view-selector'}={})=>{
    const next=normalizeMode(mode);if(!next)return {ok:false,status:'VISUALIZE_VIEW_MODE_REQUIRED',canonicalMutation:false};
    const activated=adapter.activateView(next);if(activated.ok!==true)return activated;
    activeView=next;workspace?.refreshToolbar?.();onViewChange?.({...activated,route});return {...activated,route};
  };
  const notify=(id,result,payload)=>{onRepresentationChange?.({id,result,payload:payloadWithView(payload)});return result};
  const viewIds=VISUALIZE_VIEW_MODES.map(mode=>register(commands,VIEW_COMMANDS[mode],mode[0]+mode.slice(1).toLowerCase(),payload=>setView(mode,{route:payload?.route||'view-command'})));
  const ids=[
    register(commands,'visualize.select','Select representation',payload=>{const p=payloadWithView(payload);return notify('visualize.select',adapter.select(p),p)},payload=>adapter.selectionAvailability(payloadWithView(payload))),
    register(commands,'visualize.link','Link canonical objects',payload=>adapter.link(payload),payload=>adapter.linkAvailability(payload)),
    register(commands,'visualize.move','Move representations',payload=>{const p=payloadWithView(payload);return notify('visualize.move',adapter.view(p.mode).move(p),p)},payload=>adapter.moveAvailability(payloadWithView(payload))),
    register(commands,'visualize.edit','Edit canonical object',payload=>adapter.edit(payload),payload=>adapter.editAvailability(payload)),
    register(commands,'visualize.viewport','Fit active spatial view',payload=>{const p=payloadWithView(payload);return notify('visualize.viewport',adapter.view(p.mode).viewport(p),p)},payload=>adapter.viewportAvailability(payloadWithView(payload)))
  ];
  setView(activeView,{route:'surface-bind'});
  const canonical=adapter.canonicalProjection(),providerTruth=adapter.providerTruth(),sharedCommandOwners=Object.fromEntries(SHARED_SPATIAL_COMMANDS.filter(id=>hasCommand(commands,id)).map(id=>[id,commands.commands.get(id).owner])),missingSharedCommands=SHARED_SPATIAL_COMMANDS.filter(id=>!hasCommand(commands,id));
  workspace?.status?.(canonical.ok?(canonical.canonical===true?'Visualize · canonical provider bound · one shared Spatial engine':`Visualize · ${providerTruth.authority} · canonical:false · READ_ONLY · one shared Spatial engine`):'Visualize · canonical data unavailable · local graph is SYNTHETIC representation only');
  return {surface:'visualize',owner:adapter.owner,registeredCommands:ids,viewCommands:viewIds,viewCommandIds:{...VIEW_COMMANDS},activeView:()=>activeView,setView,context:(payload={})=>payloadWithView(payload),requiredSharedCommands:[...SHARED_SPATIAL_COMMANDS],sharedCommandOwners,missingSharedCommands,spatialOwner:adapter.model.interactionKernel.ownerId,viewAdapters:adapter.viewDescriptors(),providerId:providerTruth.providerId,providerAuthority:providerTruth.authority,providerEditability:providerTruth.editability,relationMutation:providerTruth.relationMutation,objectEdit:providerTruth.objectEdit,canonical:providerTruth.canonical,canonicalDataProvider:canonical.ok?(canonical.canonical===true?'BOUND_CANONICAL':'BOUND_LOCAL_ACCEPTANCE_PROJECTION'):'UNAVAILABLE',canonicalTruth:canonical.ok?(canonical.canonical===true?'PROVIDER_BOUND_CANONICAL':'LOCAL_ACCEPTANCE_PROJECTION_ONLY'):'UNAVAILABLE',localGraphTruth:canonical.ok?(canonical.canonical===true?'REPRESENTATION_ONLY':'LOCAL_ACCEPTANCE_REPRESENTATION_ONLY'):'SYNTHETIC_REPRESENTATION_ONLY',fixtureIsCanonical:false,universalVirtualizationOwner:false};
}

function ensureVisualizeStyle(){
  if(document.querySelector('#visualizeFourViewStyle'))return;
  const style=document.createElement('style');style.id='visualizeFourViewStyle';style.textContent=`
  .m0-visualize-four-view{display:grid;grid-template-rows:auto auto minmax(0,1fr);overflow:hidden;padding:0!important}
  .m0-visualize-four-view .domain-heading{display:flex;align-items:center;gap:12px;flex-wrap:wrap;padding:10px 52px 10px 14px;border-bottom:1px solid var(--line);min-width:0}
  .m0-visualize-four-view .domain-heading strong{margin-inline-end:auto;min-width:180px}
  .visualize-view-switcher{display:flex;gap:6px;flex-wrap:wrap;direction:ltr;margin-right:56px}
  .visualize-view-switcher .btn[aria-selected="true"]{border-color:var(--accent);background:color-mix(in srgb,var(--accent) 18%,var(--panel));color:var(--text)}
  .visualize-view-meta{display:flex;gap:10px;align-items:center;flex-wrap:wrap;padding:8px 14px;border-bottom:1px solid var(--line);background:color-mix(in srgb,var(--panel) 92%,transparent);font-size:12px;color:var(--text2)}
  .visualize-view-meta strong{color:var(--text)}.visualize-view-meta .truth{margin-inline-start:auto;font-family:var(--mono);direction:ltr;unicode-bidi:isolate}
  .m0-visualize-four-view #spatialHost,.m0-visualize-four-view #domainView{min-height:0;height:100%;overflow:auto}
  .m0-visualize-four-view #spatialHost[data-visualize-view="GRAPH"]{background:radial-gradient(circle at 50% 45%,color-mix(in srgb,var(--accent) 8%,transparent),transparent 46%)}
  .m0-visualize-four-view #spatialHost[data-visualize-view="CANVAS"]{background:color-mix(in srgb,var(--panel) 78%,transparent)}
  .visualize-tree,.visualize-path{padding:14px;min-height:100%;box-sizing:border-box;direction:rtl}
  .visualize-tree-intro,.visualize-path-intro{border:1px solid var(--line);border-radius:10px;padding:10px 12px;margin-bottom:12px;background:rgba(255,255,255,.02);color:var(--text2)}
  .visualize-tree-groups{display:grid;gap:10px}.visualize-tree-group{border:1px solid var(--line);border-radius:10px;overflow:hidden;background:color-mix(in srgb,var(--panel) 94%,transparent)}
  .visualize-tree-group>header{padding:9px 12px;border-bottom:1px solid var(--line);font-weight:700;display:flex;justify-content:space-between;gap:8px}.visualize-tree-rows{display:grid;padding:4px}
  .visualize-tree-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:center;text-align:start;border:1px solid transparent;border-radius:8px;background:transparent;color:inherit;padding:9px 12px;cursor:pointer}
  .visualize-tree-row:hover,.visualize-tree-row[aria-pressed="true"]{border-color:var(--accent);background:color-mix(in srgb,var(--accent) 10%,transparent)}.visualize-tree-row small{color:var(--text3);direction:ltr;unicode-bidi:isolate}
  .visualize-path-lanes{display:grid;gap:12px;overflow:auto}.visualize-path-lane{display:grid;grid-template-columns:112px minmax(560px,1fr);gap:10px;align-items:stretch;direction:ltr}.visualize-path-label{display:grid;place-items:center;border:1px solid var(--line);border-radius:10px;font:700 12px var(--mono);color:var(--accent)}
  .visualize-path-track{display:flex;align-items:center;gap:24px;min-width:max-content;padding:10px;border:1px solid var(--line);border-radius:10px;background:color-mix(in srgb,var(--panel) 94%,transparent)}.visualize-path-node{position:relative;width:190px;min-height:78px;text-align:start;border:1px solid var(--line);border-radius:9px;background:var(--panel);color:inherit;padding:10px;direction:ltr}.visualize-path-node:not(:last-child)::after{content:'→';position:absolute;inset-inline-end:-20px;top:50%;transform:translateY(-50%);color:var(--accent);font-weight:800}.visualize-path-node[aria-pressed="true"]{border-color:var(--accent);box-shadow:0 0 0 1px color-mix(in srgb,var(--accent) 40%,transparent)}.visualize-path-node strong{display:block;white-space:normal}.visualize-path-node small{display:block;color:var(--text3);margin-top:5px}
  .visualize-left{display:grid;gap:10px}.visualize-left .view-chip{display:flex;justify-content:space-between;gap:8px;align-items:center;padding:9px;border:1px solid var(--line);border-radius:9px}.visualize-object-list{display:grid;gap:5px}.visualize-object-list button{text-align:start;white-space:normal}.visualize-object-list button[aria-pressed="true"]{border-color:var(--accent)}
  .visualize-context{display:grid;gap:10px}.visualize-context .truth-card{border:1px solid var(--line);border-radius:10px;padding:10px}.visualize-context dl{margin:0;display:grid;gap:7px}.visualize-context dl>div{display:grid;grid-template-columns:minmax(100px,.55fr) minmax(0,1fr);gap:8px;border-bottom:1px solid color-mix(in srgb,var(--line) 60%,transparent);padding-bottom:6px}.visualize-context dt{font-weight:650;color:var(--text2)}.visualize-context dd{margin:0;overflow-wrap:anywhere}.visualize-context bdi{direction:ltr;unicode-bidi:isolate}
  @media(max-width:1100px){.m0-visualize-four-view .domain-heading{padding-inline:10px}.visualize-view-switcher{width:100%;justify-content:stretch}.visualize-view-switcher .btn{flex:1}.visualize-view-meta{padding-inline:10px}.visualize-view-meta .truth{margin-inline-start:0;width:100%}.visualize-path-lane{grid-template-columns:90px minmax(520px,1fr)}}
  `;document.head.append(style);
}

const groupKey=representation=>{const id=String(representation?.canonicalRef?.objectId||'');return id.match(/^KU-(D\d+)-/)?.[1]||'LOCAL';};
const selectedSet=adapter=>new Set([...adapter.model.selection]);
const selectedRecords=adapter=>{const ids=selectedSet(adapter);return adapter.representationProjection().representations.filter(item=>ids.has(item.representationId));};

export function mountVisualizeFourViewComposition({stage,workspace,registry,adapter,binding,spatialView,providerTruth=null,refreshContext=null}={}){
  if(!stage||!workspace||!registry||!adapter||!binding||!spatialView)throw Error('VISUALIZE_FOUR_VIEW_COMPOSITION_REQUIRED');
  if(spatialView.model!==adapter.model)throw Error('VISUALIZE_SHARED_SPATIAL_ENGINE_REQUIRED');
  ensureVisualizeStyle();stage.classList.add('m0-visualize-four-view');stage.dataset.visualizeSharedSpatialOwner=adapter.model.interactionKernel.ownerId;
  const heading=stage.querySelector('.domain-heading'),spatialHost=stage.querySelector('#spatialHost'),body=stage.querySelector('#domainView');
  if(!heading||!spatialHost||!body)throw Error('VISUALIZE_CARRIER_STAGE_REQUIRED');
  heading.innerHTML=`<strong>Spatial representation workspace</strong><nav class="visualize-view-switcher" role="tablist" aria-label="Visualize representation view">${VISUALIZE_VIEW_MODES.map(mode=>`<button type="button" class="btn" role="tab" data-foundation-command="${binding.viewCommandIds[mode]}" data-visualize-view-tab="${mode}">${mode[0]+mode.slice(1).toLowerCase()}</button>`).join('')}</nav>`;
  let meta=stage.querySelector('#visualizeViewMeta');if(!meta){meta=document.createElement('div');meta.id='visualizeViewMeta';meta.className='visualize-view-meta';heading.insertAdjacentElement('afterend',meta)}
  const truth=providerTruth||adapter.providerTruth();
  const projectionFor=mode=>adapter.representationProjection(mode).representations;
  const selectionText=()=>{const rows=selectedRecords(adapter);return rows.length?rows.map(row=>row.label||row.representationId).join(' · '):'No representation selected';};
  const renderMeta=()=>{const mode=binding.activeView(),descriptor=adapter.view(mode).descriptor();meta.innerHTML=`<strong>${esc(mode)} view</strong><span>${mode==='TREE'?'Grouped representation hierarchy':mode==='PATH'?'Display-order path lanes':mode==='GRAPH'?'Focused relation projection':'Freeform representation canvas'}</span><span>Selection: ${adapter.model.selection.size}</span><span class="truth">${esc(truth.authority)} · canonical:false · ${esc(truth.editability)} · ${esc(descriptor.engineOwner)}</span>`;};
  const renderRight=()=>{const mode=binding.activeView(),view=adapter.view(mode).descriptor(),rows=selectedRecords(adapter),selection=rows.length?rows.map(row=>`<div><dt>Representation</dt><dd><bdi>${esc(row.representationId)}</bdi><br>${esc(row.label||'')}</dd></div>`).join(''):'<div><dt>Selection</dt><dd>No representation selected</dd></div>';workspace.region('RIGHT',{html:`<section class="visualize-context"><h2>Visualize · ${esc(mode)} context</h2><p>Representation-only view context. Canonical object/relation truth is unchanged.</p><div class="truth-card"><dl><div><dt>Authority</dt><dd><bdi>${esc(truth.authority)}</bdi></dd></div><div><dt>Canonical</dt><dd><bdi>false</bdi></dd></div><div><dt>Editability</dt><dd><bdi>${esc(truth.editability)}</bdi></dd></div><div><dt>Active view</dt><dd><bdi>${esc(mode)}</bdi></dd></div><div><dt>Spatial owner</dt><dd><bdi>${esc(view.engineOwner)}</bdi></dd></div><div><dt>Move</dt><dd>${view.capabilities.move?'Canvas representation geometry only':'Unavailable in this view'}</dd></div><div><dt>Viewport</dt><dd>${view.capabilities.viewport?'Representation camera only':'Unavailable in this view'}</dd></div>${selection}</dl></div></section>`,label:`Visualize · ${mode} context`});};
  const bindSelectionHost=host=>{if(!host)return;host.onclick=event=>{const button=event.target?.closest?.('[data-visualize-select]');if(!button)return;event.preventDefault();const id=button.dataset.visualizeSelect,add=event.shiftKey||event.ctrlKey||event.metaKey;registry.execute('visualize.select',{representationIds:add?[...adapter.model.selection,id]:[id],action:'replace',route:`${binding.activeView().toLowerCase()}-projection`});spatialView.render();refreshSelection();};};
  const renderLeft=()=>{const mode=binding.activeView(),rows=projectionFor(mode),selection=selectedSet(adapter),host=workspace.region('LEFT',{html:`<section class="visualize-left"><div class="view-chip"><strong>Active view</strong><bdi dir="ltr">${esc(mode)}</bdi></div><p>One shared Spatial engine. Tree, Path, Graph and Canvas are representation projections only.</p><h3>Representations</h3><div class="visualize-object-list">${rows.map(row=>`<button type="button" class="btn" data-visualize-select="${esc(row.representationId)}" aria-pressed="${selection.has(row.representationId)}"><span>${esc(row.label||row.representationId)}</span></button>`).join('')}</div></section>`,label:'Visualize views & representations'});bindSelectionHost(host);};
  const renderTree=()=>{const rows=projectionFor('TREE'),selection=selectedSet(adapter),groups=new Map();for(const row of rows){const key=groupKey(row);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row)}body.innerHTML=`<section class="visualize-tree" data-visualize-projection="TREE"><div class="visualize-tree-intro"><strong>Tree representation</strong><br>Grouped by source identity family for navigation only; this grouping is not a canonical hierarchy.</div><div class="visualize-tree-groups">${[...groups].map(([key,items])=>`<section class="visualize-tree-group"><header><span>${esc(key)} representation group</span><small>${items.length} item${items.length===1?'':'s'}</small></header><div class="visualize-tree-rows">${items.map(row=>`<button type="button" class="visualize-tree-row" data-visualize-select="${esc(row.representationId)}" aria-pressed="${selection.has(row.representationId)}"><span>${esc(row.label||row.representationId)}</span><small>${esc(row.canonicalRef?.objectId||row.representationId)}</small></button>`).join('')}</div></section>`).join('')}</div></section>`;bindSelectionHost(body);};
  const renderPath=()=>{const rows=projectionFor('PATH'),selection=selectedSet(adapter),groups=new Map();for(const row of rows){const key=groupKey(row);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row)}body.innerHTML=`<section class="visualize-path" data-visualize-projection="PATH"><div class="visualize-path-intro"><strong>Path representation</strong><br>Lane order is a display projection only; it does not assert canonical prerequisites, progress or Mastery.</div><div class="visualize-path-lanes">${[...groups].map(([key,items])=>`<section class="visualize-path-lane"><div class="visualize-path-label">${esc(key)}</div><div class="visualize-path-track">${items.map(row=>`<button type="button" class="visualize-path-node" data-visualize-select="${esc(row.representationId)}" aria-pressed="${selection.has(row.representationId)}"><strong>${esc(row.label||row.representationId)}</strong><small>${esc(row.canonicalRef?.objectId||row.representationId)}</small></button>`).join('')}</div></section>`).join('')}</div></section>`;bindSelectionHost(body);};
  const updateSelectionStyles=()=>{const selection=selectedSet(adapter);stage.querySelectorAll('[data-visualize-select]').forEach(button=>button.setAttribute('aria-pressed',String(selection.has(button.dataset.visualizeSelect))));const left=workspace.regionHosts?.get?.('LEFT');left?.querySelectorAll?.('[data-visualize-select]').forEach(button=>button.setAttribute('aria-pressed',String(selection.has(button.dataset.visualizeSelect))));};
  const refreshSelection=()=>{renderMeta();renderLeft();renderRight();updateSelectionStyles();refreshContext?.();return {mode:binding.activeView(),selection:[...adapter.model.selection],selectionText:selectionText()};};
  let lastRenderedMode=null;
  const render=()=>{
    const mode=binding.activeView(),enteringSpatial=(mode==='GRAPH'||mode==='CANVAS')&&!(lastRenderedMode==='GRAPH'||lastRenderedMode==='CANVAS');stage.dataset.visualizeActiveView=mode;stage.querySelectorAll('[data-visualize-view-tab]').forEach(button=>{const active=button.dataset.visualizeViewTab===mode;button.setAttribute('aria-selected',String(active));button.setAttribute('aria-pressed',String(active));button.tabIndex=active?0:-1});
    const spatialMode=mode==='GRAPH'||mode==='CANVAS';spatialHost.hidden=!spatialMode;body.hidden=spatialMode;spatialHost.dataset.visualizeView=mode;
    spatialView.grid=mode==='CANVAS';spatialView.minimap=mode==='CANVAS';
    if(mode==='TREE')renderTree();else if(mode==='PATH')renderPath();else spatialView.render();
    if(enteringSpatial)requestAnimationFrame(()=>{if(spatialView.svg?.clientWidth>0&&spatialView.svg?.clientHeight>0){spatialView.fit();refreshSelection();}});
    lastRenderedMode=mode;
    workspace.toolbar(['visualize.viewport','foundation.note'],{contextProvider:()=>binding.context({representationIds:[...adapter.model.selection],width:spatialView.svg?.clientWidth||0,height:spatialView.svg?.clientHeight||0,action:'fit'})});
    refreshSelection();return {mode,engineOwner:adapter.model.interactionKernel.ownerId,selection:[...adapter.model.selection],canonical:false,providerAuthority:truth.authority};
  };
  if(!spatialView.__visualizeFourViewCallbacks){const originalSelect=spatialView.callbacks.select,originalChange=spatialView.callbacks.change;spatialView.callbacks.select=ids=>{const result=originalSelect?.(ids);try{registry.execute('visualize.select',{representationIds:[...(ids||[])],action:'replace',route:`${binding.activeView().toLowerCase()}-shared-spatial`})}catch{}refreshSelection();return result};spatialView.callbacks.change=(...args)=>{const result=originalChange?.(...args);refreshSelection();return result};spatialView.__visualizeFourViewCallbacks=true;}
  render();
  return {render,refresh:refreshSelection,activeView:binding.activeView,sharedSpatialOwner:adapter.model.interactionKernel.ownerId,spatialViewId:spatialView.instanceId};
}
