const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const bdi=value=>`<bdi dir="ltr">${esc(value)}</bdi>`;
const itemTitle=(item,lang)=>String(item?.title?.[lang]||item?.title||item?.label?.[lang]||item?.label||item?.id||'');
const itemSummary=(item,lang)=>String(item?.summary?.[lang]||item?.summary||item?.description?.[lang]||item?.description||'');
const byKind=(projection,kind)=>projection.items.filter(item=>item.kind===kind);
const stateTone=state=>['FAILED','UNAVAILABLE'].includes(state)?'danger':state==='STALE'?'warning':state==='PARTIAL'?'warning':['UNOBSERVED','OBSERVED_EMPTY'].includes(state)?'muted':'ok';

const COPY=Object.freeze({
  ar:{eyebrow:'إسقاط يومي من مصادره الأصلية',title:'اليوم',subtitle:'استأنف ما كنت تعمل عليه، وراجع الإجراء التالي والانتباه والسياق والتقدم دون إنشاء حقيقة جديدة.',continue:'متابعة الجلسة الحالية',resume:'متابعة',next:'الإجراء التالي الموصى به',why:'لماذا الآن؟',attention:'يحتاج انتباهك',recent:'السياق الأخير',progress:'توقع التقدم',refresh:'تحديث',all:'الكل',empty:'لا توجد عناصر مرصودة في هذا الإسقاط.',filtered:'لا توجد عناصر مطابقة للمرشح، بينما تبقى إجماليات المصدر كما هي.',unobserved:'لم تُرصد مصادر Today بعد.',unavailable:'مصادر Today غير متاحة حاليًا.',failed:'فشل رصد مصادر Today.',stale:'البيانات المرصودة قديمة.',partial:'الإسقاط جزئي؛ بعض المصادر لم تُرصد بنجاح.',source:'المصدر',version:'الإصدار',noRationale:'لا يوجد تفسير موثوق لهذا الإصدار.',open:'فتح',noSession:'لا توجد جلسة قابلة للاستئناف في الإسقاط الحالي.',noAttention:'لا توجد عناصر انتباه مرصودة.',noRecent:'لا يوجد سياق حديث مرصود.',noProgress:'لا يوجد إسقاط تقدم مرصود.'},
  en:{eyebrow:'Daily projection from canonical owners',title:'Today',subtitle:'Resume work and inspect next action, attention, recent context and progress without creating a second truth store.',continue:'Continue current session',resume:'Resume',next:'Next recommended action',why:'Why now?',attention:'Needs attention',recent:'Recent context',progress:'Progress projection',refresh:'Refresh',all:'All',empty:'No observed items in this projection.',filtered:'No items match this filter; source totals are unchanged.',unobserved:'Today providers have not been observed yet.',unavailable:'Today providers are currently unavailable.',failed:'Today provider observation failed.',stale:'Observed data is stale.',partial:'Projection is partial; one or more sources were not observed successfully.',source:'Source',version:'Version',noRationale:'No trustworthy rationale is available for this version.',open:'Open',noSession:'No resumable session is present in the current projection.',noAttention:'No observed attention items.',noRecent:'No observed recent context.',noProgress:'No observed progress projection.'}
});

export function todayProjectionStateCopy(projection,lang='ar'){
  const c=COPY[lang==='en'?'en':'ar'];
  if(projection.filteredEmpty)return c.filtered;
  return ({UNOBSERVED:c.unobserved,UNAVAILABLE:c.unavailable,FAILED:c.failed,STALE:c.stale,PARTIAL:c.partial,OBSERVED_EMPTY:c.empty}[projection.state]||'');
}

export function buildTodayOrchestrationViewModel(projection,{lang='ar',adapter=null}={}){
  const l=lang==='en'?'en':'ar',c=COPY[l],recommendations=byKind(projection,'RECOMMENDATION'),selected=recommendations[0]||null;
  const selectedVersion=selected?.recommendation?.version||'';
  const whyAvailability=selected&&adapter?.canExplain?adapter.canExplain(selected.id,selectedVersion):{enabled:!!(selected?.recommendation?.sourceRef&&selectedVersion&&(selected.recommendation.reasonCode||selected.recommendation.rationale)),reason:c.noRationale};
  const continuation=byKind(projection,'CONTINUE_SESSION')[0]||null;
  const resumeAvailability=continuation&&adapter?.canResume?adapter.canResume(continuation.id):{enabled:!!continuation?.continuation};
  return Object.freeze({
    owner:'TodayOrchestrationPresentation',lang:l,dir:l==='ar'?'rtl':'ltr',copy:c,projection,
    continuation,resumeAvailability,recommendation:selected,whyAvailability,
    attention:byKind(projection,'ATTENTION'),recent:byKind(projection,'RECENT_CONTEXT'),progress:byKind(projection,'PROGRESS'),
    statusMessage:todayProjectionStateCopy(projection,l),statusTone:stateTone(projection.state)
  });
}

const style=`<style data-today-orchestration-style>
.today-orchestration{font-family:var(--ui,system-ui);display:grid;gap:16px;color:var(--fg,#e8f2ff);min-height:100%;padding:18px;background:radial-gradient(circle at 35% 0%,rgba(10,121,172,.12),transparent 38%)}
.today-orchestration *{box-sizing:border-box}.today-head{display:flex;align-items:flex-end;justify-content:space-between;gap:16px}.today-head h1{margin:3px 0;font-size:clamp(24px,3vw,38px)}.today-head p{margin:0;color:var(--muted,#93a8bf);max-width:78ch}.today-eyebrow{font-size:12px;color:#67d9ff;letter-spacing:.04em}.today-status{border:1px solid color-mix(in srgb,currentColor 30%,transparent);border-radius:10px;padding:8px 12px;font-size:12px}.today-status[data-tone=muted]{color:#9aabc0}.today-status[data-tone=warning]{color:#ffc85c}.today-status[data-tone=danger]{color:#ff7b82}.today-status[data-tone=ok]{color:#65dda4}
.today-layout{display:grid;grid-template-columns:minmax(0,2fr) minmax(300px,.95fr);gap:14px;align-items:start}.today-main{display:grid;gap:14px}.today-grid-2{display:grid;grid-template-columns:1.35fr .85fr;gap:14px}.today-card{border:1px solid rgba(118,160,201,.35);border-radius:14px;background:linear-gradient(180deg,rgba(7,28,48,.94),rgba(5,21,38,.96));box-shadow:0 12px 32px rgba(0,0,0,.14);overflow:hidden}.today-card-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:16px 18px 10px}.today-card-head h2{font-size:18px;margin:0}.today-card-body{padding:8px 18px 18px}.today-session{min-height:230px}.today-session .today-session-title{font-size:24px;margin:8px 0}.today-meta{display:flex;gap:10px;flex-wrap:wrap;color:#a9bdd2;font-size:13px}.today-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}.today-action{border:1px solid rgba(96,184,224,.5);border-radius:9px;background:#092b46;color:#e9f8ff;padding:9px 14px;cursor:pointer}.today-action[data-primary=true]{background:linear-gradient(135deg,#09b5e7,#12d2f0);color:#002333;border-color:#21d7ff;font-weight:700}.today-action:disabled{opacity:.45;cursor:not-allowed}.today-recommendation-title{font-size:21px;line-height:1.4;margin:6px 0 10px}.today-rationale-list{display:grid;gap:8px;margin:0;padding:0;list-style:none}.today-rationale-list li{display:grid;grid-template-columns:18px 1fr;gap:8px;align-items:start;color:#c6d5e4}.today-rationale-list li::before{content:'✓';color:#54d59c}.today-attention{display:grid;gap:10px}.today-attention-item{border:1px solid rgba(120,158,194,.28);border-radius:10px;padding:12px;display:grid;gap:5px}.today-attention-item strong{font-size:14px}.today-attention-item p{margin:0;color:#a9bdd2;font-size:12px}.today-list{display:grid;gap:0}.today-row{display:grid;grid-template-columns:minmax(100px,.75fr) minmax(140px,1.5fr) auto;gap:10px;padding:10px 0;border-bottom:1px solid rgba(130,160,190,.18);align-items:center}.today-row:last-child{border-bottom:0}.today-row small{color:#9db0c3}.today-progress{display:grid;gap:10px}.today-progress-item{display:grid;grid-template-columns:1fr auto;gap:10px;padding:9px 0;border-bottom:1px solid rgba(130,160,190,.18)}.today-empty{padding:24px 18px;color:#9fb1c4;text-align:center}.today-source{font-size:11px;color:#7892aa;margin-top:6px}.today-source bdi,.today-rationale-list bdi{white-space:nowrap}.today-filterbar{display:flex;gap:6px;flex-wrap:wrap}.today-filter{border:1px solid rgba(126,160,190,.3);background:rgba(12,40,64,.8);color:#bcd0e3;border-radius:999px;padding:6px 10px;cursor:pointer}.today-filter[aria-pressed=true]{border-color:#26c9f1;color:#75ddfb;background:rgba(16,104,134,.35)}
@media(max-width:1120px){.today-layout{grid-template-columns:1fr}.today-grid-2{grid-template-columns:1fr 1fr}.today-attention-side{order:2}}
@media(max-width:760px){.today-orchestration{padding:12px}.today-grid-2{grid-template-columns:1fr}.today-row{grid-template-columns:1fr}.today-head{align-items:flex-start;flex-direction:column}}
</style>`;

const empty=(text)=>`<div class="today-empty">${esc(text)}</div>`;
const sourceLine=(item,c)=>item?.providerId?`<div class="today-source">${esc(c.source)} · ${bdi(item.providerId)}${item?.recommendation?.version?` · ${esc(c.version)} ${bdi(item.recommendation.version)}`:''}</div>`:'';

export function renderTodayOrchestrationProjection({host,projection,adapter=null,lang=null,onAction=null}={}){
  if(!host||!projection)throw Error('TODAY_PRESENTATION_HOST_AND_PROJECTION_REQUIRED');
  const l=lang||(document.documentElement.lang==='en'?'en':'ar');
  const primaryRecommendation=projection.items.find(item=>item.kind==='RECOMMENDATION');
  if(adapter?.selectRecommendation&&primaryRecommendation?.recommendation?.version)adapter.selectRecommendation(primaryRecommendation.id,primaryRecommendation.recommendation.version);
  const vm=buildTodayOrchestrationViewModel(projection,{lang:l,adapter}),c=vm.copy;
  const session=vm.continuation?`<div class="today-card-body"><div class="today-session-title">${esc(itemTitle(vm.continuation,l))}</div><p>${esc(itemSummary(vm.continuation,l))}</p>${sourceLine(vm.continuation,c)}<div class="today-actions"><button class="today-action" data-primary="true" data-today-action="resume" data-item-id="${esc(vm.continuation.id)}" ${vm.resumeAvailability.enabled?'':'disabled'}>${esc(c.resume)}</button></div></div>`:empty(c.noSession);
  const recommendation=vm.recommendation?`<div class="today-card-body"><div class="today-recommendation-title">${esc(itemTitle(vm.recommendation,l))}</div><p>${esc(itemSummary(vm.recommendation,l))}</p>${sourceLine(vm.recommendation,c)}<div class="today-actions"><button class="today-action" data-today-action="why" data-item-id="${esc(vm.recommendation.id)}" data-recommendation-version="${esc(vm.recommendation.recommendation?.version||'')}" ${vm.whyAvailability.enabled?'':'disabled'}>${esc(c.why)}</button></div></div>`:empty(c.empty);
  const rationale=vm.recommendation&&vm.whyAvailability.enabled?`<div class="today-card-body"><ul class="today-rationale-list"><li>${esc(vm.recommendation.recommendation?.rationale||vm.recommendation.recommendation?.reasonCode||c.noRationale)}</li><li>${esc(c.source)}: ${bdi(vm.recommendation.recommendation?.sourceRef||'')}</li></ul></div>`:empty(c.noRationale);
  const attention=vm.attention.length?vm.attention.map(item=>`<article class="today-attention-item"><strong>${esc(itemTitle(item,l))}</strong><p>${esc(itemSummary(item,l))}</p>${sourceLine(item,c)}${item.continuation?`<button class="today-action" data-today-action="resume" data-item-id="${esc(item.id)}">${esc(c.open)}</button>`:''}</article>`).join(''):empty(c.noAttention);
  const recent=vm.recent.length?vm.recent.map(item=>`<div class="today-row"><small>${esc(item.timeLabel?.[l]||item.timeLabel||item.sourceObservedAt||'')}</small><span>${esc(itemTitle(item,l))}</span>${item.providerId?bdi(item.providerId):''}</div>`).join(''):empty(c.noRecent);
  const progress=vm.progress.length?vm.progress.map(item=>`<div class="today-progress-item"><span>${esc(itemTitle(item,l))}</span><strong>${bdi(item.value??item.summary??'')}</strong></div>`).join(''):empty(c.noProgress);
  const filterLabels=l==='ar'?{ALL:c.all,CONTINUE_SESSION:'الجلسة',RECOMMENDATION:'الموصى به',ATTENTION:'الانتباه',RECENT_CONTEXT:'السياق الأخير',PROGRESS:'التقدم'}:{ALL:c.all,CONTINUE_SESSION:'Session',RECOMMENDATION:'Recommendation',ATTENTION:'Attention',RECENT_CONTEXT:'Recent context',PROGRESS:'Progress'};
  const filters=['ALL',...['CONTINUE_SESSION','RECOMMENDATION','ATTENTION','RECENT_CONTEXT','PROGRESS']].map(kind=>`<button class="today-filter" data-today-action="filter" data-filter="${kind}" aria-pressed="${projection.filter===kind}">${esc(filterLabels[kind])}</button>`).join('');
  host.innerHTML=`${style}<section class="today-orchestration" dir="${vm.dir}" data-owner="${vm.owner}" data-projection-state="${esc(projection.state)}" data-provider-truth="read-side"><header class="today-head"><div><div class="today-eyebrow">${esc(c.eyebrow)}</div><h1 tabindex="-1">${esc(c.title)}</h1><p>${esc(c.subtitle)}</p></div><div><div class="today-filterbar">${filters}<button class="today-filter" data-today-action="refresh">↻ ${esc(c.refresh)}</button></div>${vm.statusMessage?`<div class="today-status" data-tone="${vm.statusTone}" role="status">${esc(vm.statusMessage)}</div>`:''}</div></header><div class="today-layout"><div class="today-main"><article class="today-card today-session"><header class="today-card-head"><h2>${esc(c.continue)}</h2></header>${session}</article><div class="today-grid-2"><article class="today-card"><header class="today-card-head"><h2>${esc(c.next)}</h2></header>${recommendation}</article><article class="today-card"><header class="today-card-head"><h2>${esc(c.why)}</h2></header>${rationale}</article></div><div class="today-grid-2"><article class="today-card"><header class="today-card-head"><h2>${esc(c.recent)}</h2></header><div class="today-card-body today-list">${recent}</div></article><article class="today-card"><header class="today-card-head"><h2>${esc(c.progress)}</h2></header><div class="today-card-body today-progress">${progress}</div></article></div></div><aside class="today-card today-attention-side"><header class="today-card-head"><h2>${esc(c.attention)}</h2><span>${vm.attention.length}</span></header><div class="today-card-body today-attention">${attention}</div></aside></div></section>`;
  host.querySelectorAll('[data-today-action]').forEach(button=>button.addEventListener('click',()=>{
    if(button.disabled)return;
    const action=button.dataset.todayAction,itemId=button.dataset.itemId||'',version=button.dataset.recommendationVersion||'';
    if(action==='why'&&adapter?.selectRecommendation)adapter.selectRecommendation(itemId,version);
    onAction?.({action,itemId,version,filter:button.dataset.filter||null,invoker:button});
  }));
  return Object.freeze({owner:vm.owner,state:projection.state,viewState:projection.viewState,sourceTotalCount:projection.sourceTotalCount,visibleCount:projection.visibleCount,canonicalWrites:false});
}
