import assert from 'node:assert/strict';
import {W03LabDomain} from '../../../adapters/labs/domain.js';
import {composeLabsSurface} from '../../../surfaces/labs/index.js';

const shared={structuredHost:{owner:'StructuredSurfaceHost'},spatialRelation:{owner:'RelationInteractionOwner'}};
const domain=new W03LabDomain({definition:{id:'LAB-S11',revision:'3',title:'Non-linear Lab',environment:{capabilities:['SIM_NET'],revision:'ENV-2'},requiredTools:[{id:'terminal',revision:'1',simulated:true},{id:'proxy',revision:'2',simulated:false}],tasks:[{id:'T1',title:'Observe',nodeType:'objective',validation:'event',expectedSignal:'alert',toolRefs:['proxy']},{id:'T2',title:'Exploit',nodeType:'action',validation:'event',expectedSignal:'request',toolRefs:['proxy']},{id:'T3',title:'Validate',nodeType:'check',validation:'event',expectedSignal:'finding',toolRefs:['terminal']}],dependencies:[{id:'E1',from:'T1',to:'T2',type:'depends'},{id:'E2',from:'T1',to:'T3',type:'branch',condition:'safe-path'}]}});
const surface=composeLabsSurface({domain,shared});assert.equal(domain.validate().ok,true);assert.equal(domain.validate().graph.nonLinear,true);
const selectionVersion=domain.version;domain.select({kind:'task',id:'T3'});assert.equal(domain.selectionContext().title,'Validate');domain.select({kind:'edge',id:'E2'});assert.equal(domain.selectionContext().kind,'branch');assert.equal(domain.version,selectionVersion);

const noTerminal=surface.bus.execute('labs.preflight',{tools:{proxy:{revision:'2'}},environmentBinding:{capabilities:['SIM_NET'],revision:'ENV-2'}});assert.equal(noTerminal.status,'BLOCKED');assert.equal(noTerminal.runStartAllowed,false);assert.equal(noTerminal.checks.filter(x=>x.status==='UNAVAILABLE').length,1);assert.equal(noTerminal.checks.find(x=>x.id==='terminal').status,'UNAVAILABLE');assert.equal(noTerminal.checks.find(x=>x.id==='proxy').status,'READY');
const readyContext={tools:{terminal:{revision:'1'},proxy:{revision:'2'}},environmentBinding:{capabilities:['SIM_NET'],revision:'ENV-2'}};const draftReady=surface.bus.execute('labs.preflight',readyContext);assert.equal(draftReady.status,'BLOCKED');assert.equal(draftReady.runStartAllowed,false);assert.equal(surface.bus.execute('labs.handoff',{...readyContext,executionContext:'STANDALONE'}).code,'LAB_REVISION_NOT_PUBLISHED');domain.publish({digest:'lab-digest-3'});const ready=surface.bus.execute('labs.preflight',readyContext);assert.equal(ready.status,'READY');assert.equal(ready.simulationExplicit,true);
const standalone=surface.bus.execute('labs.handoff',{...readyContext,executionContext:'STANDALONE'});const module=surface.bus.execute('labs.handoff',{...readyContext,executionContext:'SCENARIO_MODULE',scenarioRef:{id:'SC-7',revision:'4'}});assert.deepEqual(standalone.labRef,module.labRef);assert.equal(standalone.inputManifest.executionContext,'STANDALONE');assert.equal(module.inputManifest.executionContext,'SCENARIO_MODULE');assert.deepEqual(module.inputManifest.scenarioRef,{id:'SC-7',revision:'4'});assert.equal(module.runIdentityAllocation,'DELEGATED_TO_RUNS');assert.equal(module.runCreated,false);assert.equal(module.runtimeStateCreated,false);assert.equal(domain.owner,'W03LabDomain');

const successor=surface.bus.execute('labs.revise',{expectedVersion:domain.version});assert.equal(successor.snapshot.lifecycle,'DRAFT');surface.bus.execute('labs.author',{op:'addTask',task:{id:'T4',title:'Report',nodeType:'evidence',validation:'event',expectedSignal:'artifact'}});surface.bus.execute('labs.author',{op:'connect',edge:{id:'E3',from:'T2',to:'T4',type:'optional',condition:'evidence-ready'}});assert.equal(domain.graphProjection().tasks.some(x=>x.id==='T4'),true);assert.equal(domain.graphProjection().edges.some(x=>x.id==='E3'&&x.type==='optional'),true);

const published=new W03LabDomain({status:'PUBLISHED',definition:{id:'LAB-PUB',revision:'8',digest:'lab-digest',title:'Published',environment:{capabilities:[]},requiredTools:[],tasks:[{id:'T1',title:'Task',validation:'event',expectedSignal:'ok'}],dependencies:[]}});const pubSurface=composeLabsSurface({domain:published,shared});const sourceBefore=JSON.stringify(published.snapshot().definition);const denied=pubSurface.bus.execute('labs.author',{title:'mutate'});assert.equal(denied.ok,false);assert.equal(denied.code,'PUBLISHED_REVISION_IMMUTABLE');const revised=pubSurface.bus.execute('labs.revise',{expectedVersion:published.version});assert.equal(revised.snapshot.lifecycle,'DRAFT');assert.deepEqual(revised.snapshot.sourceLineage,{id:'LAB-PUB',revision:'8',digest:'lab-digest',lifecycle:'PUBLISHED'});assert.equal(JSON.stringify(revised.source),sourceBefore);assert.equal(revised.snapshot.definition.revision,'9');

console.log('S11 lab task graph: PASS');
