import {assertCanonicalSemanticCommandBus} from '../../foundation/global/commands.js';
import {CollectionTableMatrixPresentationCore,type CollectionTableMatrixDomainAdapter} from '../../foundation/collection/table-matrix.js';
import {defineContextDescriptorProvider} from '../../foundation/global/context-descriptor-contract.js';
import {createFamilyWorkspaceBinding} from '../../foundation/workspace-host.js';
import {ManualAiDomainAdapter,MANUAL_AI_COMMANDS} from '../../adapters/manual_ai/domain-adapter.js';
export const MANUAL_AI_SURFACE_ID='manual_ai';
export function createManualAiSurfaceComposition({adapter=new ManualAiDomainAdapter(),commands=null}={}){
  commands=assertCanonicalSemanticCommandBus(commands,'manual_ai.composition');
  adapter.bindCommands(commands);
  const tableAdapter:CollectionTableMatrixDomainAdapter<any>={adapterId:'manual_ai.proposals',rows:()=>adapter.rows(),rowId:r=>r.proposalId,rowLabel:r=>r.proposalId,searchableText:r=>`${r.proposalId} ${r.revision} ${r.state} ${r.provenance.sourceId} ${r.provenance.sourceRevisionId} ${r.provenance.sourceDigest}`,columns:[{id:'proposal',label:'Proposal',cell:r=>({text:r.proposalId,secondary:r.revision,direction:'ltr'})},{id:'state',label:'State',cell:r=>({text:r.state,tone:r.state==='PROVENANCE_INVALID'?'danger':r.state==='ACCEPTED_AS_DRAFT'?'success':r.state==='DEFERRED'?'warning':'default'})},{id:'source',label:'Provenance',cell:r=>({text:r.provenance.sourceId,secondary:`${r.provenance.sourceRevisionId} · ${r.provenance.sourceDigest}`,direction:'auto'})}],actions:r=>[{id:'manual_ai.export',label:'Export packet',enabled:adapter.availability('manual_ai.export',{id:r.proposalId})===true},{id:'manual_ai.import',label:'Import result',enabled:adapter.availability('manual_ai.import',{id:r.proposalId})===true},{id:'manual_ai.review',label:'Review',enabled:adapter.availability('manual_ai.review',{id:r.proposalId,disposition:'DEFER'})===true}]};
  const collection=new CollectionTableMatrixPresentationCore(tableAdapter);
  const contextProvider=defineContextDescriptorProvider({id:'manual_ai.context',family:'manual_ai',owner:adapter.owner,describe:({id}:any={})=>{const row=adapter.rows().find(item=>item.proposalId===(id??adapter.selected()?.proposalId));const capabilities=adapter.capabilityTruth();return {id:`manual-ai:${row?.proposalId||'empty'}`,providerId:'manual_ai.context',family:'manual_ai',subject:row?.proposalId||'No ManualProposal selected',eyebrow:'Manual AI Bridge',summary:row?`${row.state} · ${row.draftState}`:'Provider-neutral manual workflow. No automatic generation or provider call.',domainOwner:adapter.owner,revisionToken:row?.revision||null,lenses:[{id:'identity',label:'Identity',tabs:[{id:'provenance',label:'Provenance',fields:row?[{id:'source',label:'Source',value:row.provenance.sourceId},{id:'source-revision',label:'Source revision',value:row.provenance.sourceRevisionId,technical:true},{id:'source-digest',label:'Source digest',value:row.provenance.sourceDigest,technical:true},{id:'package-digest',label:'Export package digest',value:row.provenance.exportedPackageDigest||'Not exported',technical:true},{id:'mode',label:'Acquisition',value:row.provenance.obtainedBy},{id:'export-helper',label:'Export helper',value:capabilities.exportHelperAvailable?'BOUND':'UNAVAILABLE'},{id:'draft-sink',label:'Draft sink',value:capabilities.draftSinkAvailable?'BOUND':'UNAVAILABLE'},{id:'history-persistence',label:'Review history persistence',value:'IN_MEMORY_ONLY'},{id:'draft',label:'Draft state',value:row.draftState}]:[{id:'mode',label:'Mode',value:'MANUAL_ONLY_PROVIDER_NEUTRAL'},{id:'export-helper',label:'Export helper',value:capabilities.exportHelperAvailable?'BOUND':'UNAVAILABLE'},{id:'draft-sink',label:'Draft sink',value:capabilities.draftSinkAvailable?'BOUND':'UNAVAILABLE'},{id:'history-persistence',label:'Review history persistence',value:'IN_MEMORY_ONLY'}]}]}]};}});
  return {surface:MANUAL_AI_SURFACE_ID,workspaceBinding:createFamilyWorkspaceBinding({id:'manual_ai.workspace',family:'global',domainKind:'manual_ai',label:'Manual AI Bridge'}),adapter,commands,collection,tableAdapter,contextProvider,toolbarCommandIds:[...MANUAL_AI_COMMANDS],bottomProjection:()=>adapter.diagnosticProjection(),providerTruth:{mode:'MANUAL_ONLY_PROVIDER_NEUTRAL',hiddenProviderCalls:0,providerNetworkCalls:0,backgroundCompletion:false,automaticCanonicalPublication:false,historyPersistence:'IN_MEMORY_ONLY',appendOnlyDurableHistory:false,importRequiresDeclaredExport:true,provenanceEquality:'SOURCE_ID+SOURCE_REVISION+SOURCE_DIGEST+EXPORTED_PACKAGE_DIGEST',...adapter.capabilityTruth()},platformTruth:{activeKeyboardSource:'UNAVAILABLE_OR_FALLBACK',nativeWindow:'UNAVAILABLE_OR_SEPARATE_PLATFORM_CAPABILITY'},slots:{TOP:'shared',TOOLBAR:'shared',LEFT:'collection',CENTER:'ManualProposalAdjudicationWorkbench',RIGHT:'shared-context-inspector',BOTTOM:'shared-bottom-shell/domain-projection',TRANSIENT:'shared'}};
}
