import {ManualAiDomainAdapter} from '../../../adapters/manual_ai/domain-adapter.js';
import {createManualAiSurfaceComposition} from '../../../surfaces/manual_ai/composition.js';
import {createValidationConsumerAdapter,VALIDATION_RULESET_IDENTITY,VALIDATION_VALIDATOR_IDENTITY} from '../../../adapters/validation.js';
const assert=(value:any,message='assertion failed')=>{if(!value)throw Error(message)};
const run=async(name:string,fn:()=>any,out:any[])=>{try{await fn();out.push({name,status:'PASS'})}catch(error){out.push({name,status:'FAIL',error:String((error as any)?.message||error)})}};
const sourceDigest='a'.repeat(64),packageDigest='b'.repeat(64),artifactDigest='c'.repeat(64);
export async function runS17Tests(){const tests:any[]=[];
 await run('manual-ai.no-hidden-provider-execution',()=>{const a=new ManualAiDomainAdapter();a.prepare({proposalId:'p1',revision:'r1',sourceDigest,sourceId:'source-A'});assert(a.diagnosticProjection().hiddenProviderCalls===0)},tests);
 await run('manual-ai.export-binds-exact-source-revision-digest',()=>{const a=new ManualAiDomainAdapter({io:{exportPackage:()=>({artifactId:'pkg-1',digest:packageDigest})}});a.prepare({proposalId:'p1',revision:'r1',sourceDigest,sourceId:'source-A'});const r=a.export('p1');assert(r.ok&&r.packet.sourceId==='source-A'&&r.packet.sourceRevisionId==='r1'&&r.packet.sourceDigest===sourceDigest&&r.artifact.digest===packageDigest)},tests);
 await run('manual-ai.import-mismatch-fails-closed-and-preserves-request',()=>{const a=new ManualAiDomainAdapter({io:{exportPackage:()=>({artifactId:'pkg-1',digest:packageDigest})}});a.prepare({proposalId:'p1',revision:'r1',sourceDigest,sourceId:'source-A'});a.export('p1');const r=a.import({proposalId:'p1',sourceId:'source-B',sourceRevisionId:'r2',sourceDigest:'d'.repeat(64),packageDigest,content:'external result'});assert(!r.ok&&r.code==='PROVENANCE_INVALID');const row=a.selected();assert(row?.provenance.sourceId==='source-A'&&row?.provenance.sourceRevisionId==='r1'&&row?.sourceDigest===sourceDigest)},tests);
 await run('manual-ai.import-equality-is-required',()=>{const a=new ManualAiDomainAdapter({io:{exportPackage:()=>({artifactId:'pkg-1',digest:packageDigest})}});a.prepare({proposalId:'p1',revision:'r1',sourceDigest,sourceId:'source-A'});a.export('p1');const r=a.import({proposalId:'p1',sourceId:'source-A',sourceRevisionId:'r1',sourceDigest,packageDigest,content:'external result'});assert(r.ok&&r.provenanceEqual===true&&r.proposal.state==='IMPORTED')},tests);
 await run('manual-ai.unknown-import-cannot-create-authority',()=>{const a=new ManualAiDomainAdapter();const r=a.import({proposalId:'unknown',sourceId:'source-A',sourceRevisionId:'r1',sourceDigest,content:'x'});assert(!r.ok&&r.code==='DECLARED_REQUEST_NOT_FOUND'&&a.rows().length===0)},tests);
 await run('manual-ai.accept-creates-idempotent-draft-only',()=>{let calls=0;const a=new ManualAiDomainAdapter({io:{exportPackage:()=>({artifactId:'pkg-1',digest:packageDigest})},draftSink:{createWorkingDraft:()=>{calls+=1;return {draftId:'draft-1',status:'CREATED'}}}});a.prepare({proposalId:'p1',revision:'r1',sourceDigest,sourceId:'source-A'});a.export('p1');a.import({proposalId:'p1',sourceId:'source-A',sourceRevisionId:'r1',sourceDigest,packageDigest,content:'external result'});const first=a.review({id:'p1',disposition:'ACCEPT'}),second=a.review({id:'p1',disposition:'ACCEPT'});assert(first.ok&&first.code==='ACCEPTED_AS_DRAFT'&&first.canonicalPublication===false&&second.idempotent===true&&calls===1)},tests);
 await run('manual-ai.shared-collection-and-context-remain-bound',()=>{const c=createManualAiSurfaceComposition();assert(c.slots.LEFT==='collection'&&c.slots.CENTER==='ManualProposalAdjudicationWorkbench'&&c.providerTruth.hiddenProviderCalls===0)},tests);
 await run('validation.exact-identities-produce-technical-valid-only',async()=>{const a=createValidationConsumerAdapter();const r=await a.validate(JSON.stringify({artifactRef:'artifact-A',artifactDigest,ruleset:VALIDATION_RULESET_IDENTITY,validator:VALIDATION_VALIDATOR_IDENTITY,payload:{ok:true}}));assert(r.status==='TECHNICALLY_VALID'&&r.identity.artifact.digest===artifactDigest&&a.truth().formalReviewAuthority===false)},tests);
 await run('validation.changed-artifact-cannot-reuse-result',async()=>{const a=createValidationConsumerAdapter();const r=await a.validate(JSON.stringify({artifactRef:'artifact-A',artifactDigest,ruleset:VALIDATION_RULESET_IDENTITY,validator:VALIDATION_VALIDATOR_IDENTITY,payload:{ok:true}}));const inspected=a.inspect({resultId:r.resultId,currentIdentity:{artifactRef:'artifact-B',artifactDigest:'d'.repeat(64),ruleset:VALIDATION_RULESET_IDENTITY,validator:VALIDATION_VALIDATOR_IDENTITY}});assert(inspected.code==='STALE_FOR_CURRENT_ARTIFACT'&&inspected.currentIdentityMatches===false&&inspected.acceptance===null)},tests);
 await run('validation.missing-validator-is-unavailable-never-pass',async()=>{const a=createValidationConsumerAdapter();const r=await a.validate(JSON.stringify({artifactRef:'artifact-A',artifactDigest,ruleset:VALIDATION_RULESET_IDENTITY,payload:{ok:true}}));assert(r.status==='UNAVAILABLE'&&r.technicalFindings.some((f:any)=>f.code==='VALIDATOR_IDENTITY_MISSING'))},tests);
 await run('validation.technical-finding-never-becomes-w04-finding',async()=>{const a=createValidationConsumerAdapter();const r=await a.validate('{');const f=a.findings({resultId:r.resultId});const review=a.reviewSnapshot();assert(f.formalReviewFindings.length===0&&f.technicalFindings.every((x:any)=>x.formalReviewFinding===false)&&review.findings.length===0)},tests);
 await run('validation.shared-collection-is-real-technical-finding-projection',async()=>{const a=createValidationConsumerAdapter();await a.validate('{');assert(a.collection.snapshot().totalRows>0&&a.collection.snapshot().visibleRows.every((x:any)=>x.formalReviewFinding===false))},tests);
 return tests;}
if(import.meta.url===new URL(process.argv[1],'file:').href){const tests=await runS17Tests();const report={lane:'S17_W05_VALIDATION_MANUAL_AI',pass:tests.filter(t=>t.status==='PASS').length,fail:tests.filter(t=>t.status==='FAIL').length,tests};console.log(JSON.stringify(report,null,2));if(report.fail)process.exitCode=1;}
