#define UNICODE
#define _UNICODE
#define WIN32_LEAN_AND_MEAN
#include <winsock2.h>
#include <ws2tcpip.h>
#include <windows.h>
#include <shellapi.h>
#include <string>
#include <vector>
#include <map>
#include <thread>
#include <atomic>
#include <sstream>
#include <iostream>
#include <algorithm>
#include <cwctype>

static std::wstring widen(const std::string& s){ if(s.empty()) return {}; int n=MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),nullptr,0); std::wstring w(n,L'\0'); MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),w.data(),n); return w; }
static std::string narrow(const std::wstring& w){ if(w.empty()) return {}; int n=WideCharToMultiByte(CP_UTF8,0,w.data(),(int)w.size(),nullptr,0,nullptr,nullptr); std::string s(n,'\0'); WideCharToMultiByte(CP_UTF8,0,w.data(),(int)w.size(),s.data(),n,nullptr,nullptr); return s; }
static std::string jesc(const std::string& s){ std::string o; for(unsigned char c: s){ if(c=='\\'||c=='\"'){o+='\\';o+=char(c);} else if(c=='\n')o+="\\n"; else if(c=='\r')o+="\\r"; else if(c=='\t')o+="\\t"; else if(c<0x20){char b[7]; sprintf_s(b,"\\u%04x",c);o+=b;} else o+=char(c);} return o; }
static std::wstring quoteArg(const std::wstring& s){ if(s.find_first_of(L" \t\"")==std::wstring::npos) return s; std::wstring o=L"\""; unsigned slash=0; for(wchar_t c:s){ if(c==L'\\'){slash++;continue;} if(c==L'\"'){o.append(slash*2+1,L'\\');o+=L'\"';slash=0;continue;} o.append(slash,L'\\');slash=0;o+=c;} o.append(slash*2,L'\\');o+=L'\"'; return o; }
static std::string epoch(){ return std::to_string(GetCurrentProcessId())+"-"+std::to_string(GetTickCount64()); }

struct Args{ std::wstring mode,session,exe,cwd; short cols=120,rows=30; std::vector<std::wstring> args,env; };
static Args parseArgs(){ Args a; int n=0; LPWSTR* av=CommandLineToArgvW(GetCommandLineW(),&n); if(n>1)a.mode=av[1]; for(int i=2;i<n;i++){std::wstring k=av[i]; auto take=[&](){return i+1<n?std::wstring(av[++i]):L"";}; if(k==L"--session-id")a.session=take(); else if(k==L"--exe")a.exe=take(); else if(k==L"--cwd")a.cwd=take(); else if(k==L"--cols")a.cols=(short)_wtoi(take().c_str()); else if(k==L"--rows")a.rows=(short)_wtoi(take().c_str()); else if(k==L"--arg")a.args.push_back(take()); else if(k==L"--env")a.env.push_back(take()); } LocalFree(av); return a; }

static std::vector<wchar_t> envBlock(const std::vector<std::wstring>& overrides){
  std::map<std::wstring,std::wstring> m; LPWCH raw=GetEnvironmentStringsW(); if(raw){ for(LPWCH p=raw;*p;){std::wstring e=p; p+=e.size()+1; auto q=e.find(L'='); if(q>0){std::wstring k=e.substr(0,q); std::transform(k.begin(),k.end(),k.begin(),::towupper);m[k]=e.substr(q+1);} } FreeEnvironmentStringsW(raw);} for(auto&e:overrides){auto q=e.find(L'=');if(q>0){auto k=e.substr(0,q);std::transform(k.begin(),k.end(),k.begin(),::towupper);m[k]=e.substr(q+1);}}
  std::vector<wchar_t> out; for(auto&[k,v]:m){std::wstring e=k+L"="+v;out.insert(out.end(),e.begin(),e.end());out.push_back(0);} out.push_back(0); return out;
}
static void emitErr(const std::string&s){ DWORD n; WriteFile(GetStdHandle(STD_ERROR_HANDLE),s.data(),(DWORD)s.size(),&n,nullptr); WriteFile(GetStdHandle(STD_ERROR_HANDLE),"\n",1,&n,nullptr); }

static int terminalMode(const Args&a){
  if(a.session.empty()||a.exe.empty()){emitErr("{\"event\":\"error\",\"code\":\"PROFILE_REQUIRED\"}");return 2;}
  HANDLE inRead=nullptr,inWrite=nullptr,outRead=nullptr,outWrite=nullptr;
  if(!CreatePipe(&inRead,&inWrite,nullptr,0)||!CreatePipe(&outRead,&outWrite,nullptr,0)){emitErr("{\"event\":\"error\",\"code\":\"PIPE_CREATE_FAILED\"}");return 3;}
  HPCON pc=nullptr; COORD size{(SHORT)std::max<short>(1,a.cols),(SHORT)std::max<short>(1,a.rows)}; HRESULT hr=CreatePseudoConsole(size,inRead,outWrite,0,&pc); if(FAILED(hr)){CloseHandle(inRead);CloseHandle(outWrite);emitErr("{\"event\":\"error\",\"code\":\"CREATE_PSEUDOCONSOLE_FAILED\",\"hresult\":"+std::to_string((long)hr)+"}");return 4;}
  CloseHandle(inRead); inRead=nullptr; CloseHandle(outWrite); outWrite=nullptr;
  SIZE_T bytes=0; InitializeProcThreadAttributeList(nullptr,1,0,&bytes); auto attrs=(PPROC_THREAD_ATTRIBUTE_LIST)HeapAlloc(GetProcessHeap(),0,bytes); if(!attrs||!InitializeProcThreadAttributeList(attrs,1,0,&bytes)||!UpdateProcThreadAttribute(attrs,0,PROC_THREAD_ATTRIBUTE_PSEUDOCONSOLE,pc,sizeof(pc),nullptr,nullptr)){emitErr("{\"event\":\"error\",\"code\":\"PSEUDOCONSOLE_ATTRIBUTE_FAILED\"}");return 5;}
  STARTUPINFOEXW si{};si.StartupInfo.cb=sizeof(si);si.lpAttributeList=attrs;PROCESS_INFORMATION pi{};
  std::wstring cmd=quoteArg(a.exe); for(auto&x:a.args){cmd+=L" "+quoteArg(x);} auto eb=envBlock(a.env); std::vector<wchar_t> mutableCmd(cmd.begin(),cmd.end());mutableCmd.push_back(0);
  BOOL ok=CreateProcessW(a.exe.c_str(),mutableCmd.data(),nullptr,nullptr,FALSE,EXTENDED_STARTUPINFO_PRESENT|CREATE_UNICODE_ENVIRONMENT,eb.data(),a.cwd.empty()?nullptr:a.cwd.c_str(),&si.StartupInfo,&pi);
  DeleteProcThreadAttributeList(attrs);HeapFree(GetProcessHeap(),0,attrs); if(!ok){ClosePseudoConsole(pc); emitErr("{\"event\":\"error\",\"code\":\"CREATE_PROCESS_FAILED\",\"win32\":"+std::to_string(GetLastError())+"}");return 6;}
  CloseHandle(pi.hThread);
  WSADATA wsa{}; if(WSAStartup(MAKEWORD(2,2),&wsa)!=0){ClosePseudoConsole(pc);TerminateProcess(pi.hProcess,1);CloseHandle(pi.hProcess);emitErr("{\"event\":\"error\",\"code\":\"WSA_STARTUP_FAILED\"}");return 7;}
  SOCKET controlSocket=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP); if(controlSocket==INVALID_SOCKET){WSACleanup();ClosePseudoConsole(pc);TerminateProcess(pi.hProcess,1);CloseHandle(pi.hProcess);emitErr("{\"event\":\"error\",\"code\":\"CONTROL_SOCKET_CREATE_FAILED\"}");return 8;}
  SOCKET inputSocket=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP); if(inputSocket==INVALID_SOCKET){closesocket(controlSocket);WSACleanup();ClosePseudoConsole(pc);TerminateProcess(pi.hProcess,1);CloseHandle(pi.hProcess);emitErr("{\"event\":\"error\",\"code\":\"INPUT_SOCKET_CREATE_FAILED\"}");return 8;}
  sockaddr_in controlAddr{}; controlAddr.sin_family=AF_INET; controlAddr.sin_addr.s_addr=htonl(INADDR_LOOPBACK); controlAddr.sin_port=0;
  sockaddr_in inputAddr{}; inputAddr.sin_family=AF_INET; inputAddr.sin_addr.s_addr=htonl(INADDR_LOOPBACK); inputAddr.sin_port=0;
  if(bind(controlSocket,(sockaddr*)&controlAddr,sizeof(controlAddr))==SOCKET_ERROR||listen(controlSocket,4)==SOCKET_ERROR){closesocket(inputSocket);closesocket(controlSocket);WSACleanup();ClosePseudoConsole(pc);TerminateProcess(pi.hProcess,1);CloseHandle(pi.hProcess);emitErr("{\"event\":\"error\",\"code\":\"CONTROL_SOCKET_BIND_FAILED\"}");return 9;}
  if(bind(inputSocket,(sockaddr*)&inputAddr,sizeof(inputAddr))==SOCKET_ERROR||listen(inputSocket,4)==SOCKET_ERROR){closesocket(inputSocket);closesocket(controlSocket);WSACleanup();ClosePseudoConsole(pc);TerminateProcess(pi.hProcess,1);CloseHandle(pi.hProcess);emitErr("{\"event\":\"error\",\"code\":\"INPUT_SOCKET_BIND_FAILED\"}");return 9;}
  int controlAddrLen=sizeof(controlAddr);getsockname(controlSocket,(sockaddr*)&controlAddr,&controlAddrLen);unsigned controlPort=ntohs(controlAddr.sin_port);
  int inputAddrLen=sizeof(inputAddr);getsockname(inputSocket,(sockaddr*)&inputAddr,&inputAddrLen);unsigned inputPort=ntohs(inputAddr.sin_port);
  std::atomic<bool> closing=false;
  std::thread output([&](){char buf[8192];DWORD got=0,wrote=0;HANDLE stdOut=GetStdHandle(STD_OUTPUT_HANDLE);while(ReadFile(outRead,buf,sizeof(buf),&got,nullptr)&&got){if(!WriteFile(stdOut,buf,got,&wrote,nullptr))break;}});
  std::thread input([&](){while(!closing){SOCKET client=accept(inputSocket,nullptr,nullptr);if(client==INVALID_SOCKET)break;char b[8192];int n=0;DWORD wrote=0;while((n=recv(client,b,sizeof(b),0))>0){BOOL okWrite=WriteFile(inWrite,b,(DWORD)n,&wrote,nullptr);emitErr("{\"event\":\"input-write\",\"bytes\":"+std::to_string(n)+",\"written\":"+std::to_string(wrote)+",\"ok\":"+std::string(okWrite?"true":"false")+"}");if(!okWrite||wrote!=(DWORD)n)break;}shutdown(client,SD_BOTH);closesocket(client);}});
  std::thread control([&](){while(!closing){SOCKET client=accept(controlSocket,nullptr,nullptr);if(client==INVALID_SOCKET)break;char b[4096];int n=recv(client,b,sizeof(b)-1,0);if(n>0){b[n]=0;std::istringstream ss(std::string(b,n));std::string op;ss>>op;if(op=="RESIZE"){int c=0,r=0;ss>>c>>r;COORD z{(SHORT)std::max(1,c),(SHORT)std::max(1,r)};HRESULT rr=ResizePseudoConsole(pc,z);emitErr("{\"event\":\"resize\",\"ok\":"+std::string(SUCCEEDED(rr)?"true":"false")+",\"cols\":"+std::to_string(c)+",\"rows\":"+std::to_string(r)+"}");}else if(op=="CLOSE"){closing=true;TerminateProcess(pi.hProcess,130);}}shutdown(client,SD_BOTH);closesocket(client);}});
  emitErr("{\"event\":\"ready\",\"providerId\":\"cep-win32-conpty\",\"providerVersion\":\"1.0.0\",\"providerEpoch\":\""+jesc(epoch())+"\",\"sessionId\":\""+jesc(narrow(a.session))+"\",\"controlHost\":\"127.0.0.1\",\"controlPort\":"+std::to_string(controlPort)+",\"inputHost\":\"127.0.0.1\",\"inputPort\":"+std::to_string(inputPort)+",\"executable\":\""+jesc(narrow(a.exe))+"\"}");
  WaitForSingleObject(pi.hProcess,INFINITE);DWORD code=0;GetExitCodeProcess(pi.hProcess,&code);closing=true;CloseHandle(inWrite);ClosePseudoConsole(pc);CloseHandle(pi.hProcess);
  closesocket(controlSocket); closesocket(inputSocket); if(control.joinable())control.join(); if(input.joinable())input.join(); WSACleanup();
  if(output.joinable())output.join(); CloseHandle(outRead);
  emitErr("{\"event\":\"exit\",\"sessionId\":\""+jesc(narrow(a.session))+"\",\"exitCode\":"+std::to_string(code)+"}"); return (int)code;
}

struct WindowRef{std::wstring id,url,profile;PROCESS_INFORMATION pi{};HWND hwnd=nullptr;}; static std::map<std::wstring,WindowRef> windows;
static BOOL CALLBACK enumPid(HWND h,LPARAM p){auto* pair=(std::pair<DWORD,HWND*>*)p;DWORD pid=0;GetWindowThreadProcessId(h,&pid);if(pid==pair->first&&IsWindowVisible(h)&&GetWindow(h,GW_OWNER)==nullptr){*pair->second=h;return FALSE;}return TRUE;}
static HWND findWindow(DWORD pid,int ms=8000){HWND h=nullptr;for(int i=0;i<ms/100&&!h;i++){std::pair<DWORD,HWND*> x{pid,&h};EnumWindows(enumPid,(LPARAM)&x);if(!h)Sleep(100);}return h;}
static std::wstring edgePath(){wchar_t p[MAX_PATH];DWORD n=GetEnvironmentVariableW(L"ProgramFiles(x86)",p,MAX_PATH);std::vector<std::wstring> roots;if(n)roots.emplace_back(p);n=GetEnvironmentVariableW(L"ProgramFiles",p,MAX_PATH);if(n)roots.emplace_back(p);for(auto&r:roots){auto e=r+L"\\Microsoft\\Edge\\Application\\msedge.exe";if(GetFileAttributesW(e.c_str())!=INVALID_FILE_ATTRIBUTES)return e;}return L"";}
static std::string dirHint(){HWND h=GetForegroundWindow();DWORD tid=h?GetWindowThreadProcessId(h,nullptr):0;HKL layout=GetKeyboardLayout(tid);LANGID lid=LOWORD((UINT_PTR)layout);LCID lcid=MAKELCID(lid,SORT_DEFAULT);wchar_t name[LOCALE_NAME_MAX_LENGTH]{};if(!LCIDToLocaleName(lcid,name,LOCALE_NAME_MAX_LENGTH,0))return "unknown";wchar_t buf[8]{};if(!GetLocaleInfoEx(name,LOCALE_IREADINGLAYOUT,buf,8))return "unknown";int v=_wtoi(buf);return v==1?"rtl":v==0?"ltr":"unknown";}
static std::vector<std::wstring> splitTabs(const std::wstring&s){std::vector<std::wstring>v;size_t p=0;while(true){auto q=s.find(L'\t',p);v.push_back(s.substr(p,q==std::wstring::npos?s.size()-p:q-p));if(q==std::wstring::npos)break;p=q+1;}return v;}
static std::wstring b64decode(const std::wstring& in){ static const std::wstring A=L"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"; std::string src=narrow(in),out;int val=0,bits=-8;for(unsigned char c:src){if(c=='=')break;auto p=A.find((wchar_t)c);if(p==std::wstring::npos)continue;val=(val<<6)+(int)p;bits+=6;if(bits>=0){out.push_back(char((val>>bits)&0xff));bits-=8;}}return widen(out);}
static void platformMode(){std::wstring ep=widen(epoch());std::wstring line;while(std::getline(std::wcin,line)){auto f=splitTabs(line);if(f.empty())continue;auto op=f[0];if(op==L"QUIT")break;if(op==L"DESCRIBE"){bool edgeReady=!edgePath().empty();std::cout<<"{\"ok\":true,\"providerId\":\"cep-win32-sidecar\",\"providerVersion\":\"1.0.0\",\"providerEpoch\":\""<<jesc(narrow(ep))<<"\",\"platform\":\"windows-x64\",\"prerequisites\":{\"edgeAppRuntime\":"<<(edgeReady?"true":"false")<<"},\"capabilities\":{\"separateWindow\":"<<(edgeReady?"true":"false")<<",\"alwaysOnTop\":"<<(edgeReady?"true":"false")<<",\"activeInputDirection\":true,\"conpty\":true}}\n"<<std::flush;continue;}if(op==L"INPUT_DIRECTION"){auto d=dirHint();std::cout<<"{\"ok\":true,\"hint\":\""<<d<<"\",\"recognized\":"<<(d=="unknown"?"false":"true")<<",\"semanticInference\":false,\"contentInspectedForLanguage\":false}\n"<<std::flush;continue;}
    if(op==L"WINDOW_OPEN"&&f.size()>=3){auto id=b64decode(f[1]),url=b64decode(f[2]);if(windows.count(id)&&IsWindow(windows[id].hwnd)){std::cout<<"{\"ok\":true,\"code\":\"REUSED\",\"presentationId\":\""<<jesc(narrow(id))<<"\"}\n"<<std::flush;continue;}auto edge=edgePath();if(edge.empty()){std::cout<<"{\"ok\":false,\"code\":\"EDGE_RUNTIME_UNAVAILABLE\"}\n"<<std::flush;continue;}wchar_t temp[MAX_PATH];GetTempPathW(MAX_PATH,temp);auto prof=std::wstring(temp)+L"cep-detached-"+std::to_wstring(GetCurrentProcessId())+L"-"+std::to_wstring(GetTickCount64());CreateDirectoryW(prof.c_str(),nullptr);std::wstring cmd=quoteArg(edge)+L" --app="+quoteArg(url)+L" --user-data-dir="+quoteArg(prof)+L" --no-first-run";std::vector<wchar_t> m(cmd.begin(),cmd.end());m.push_back(0);STARTUPINFOW si{sizeof(si)};PROCESS_INFORMATION pi{};BOOL ok=CreateProcessW(edge.c_str(),m.data(),nullptr,nullptr,FALSE,0,nullptr,nullptr,&si,&pi);if(!ok){std::cout<<"{\"ok\":false,\"code\":\"DETACHED_LAUNCH_FAILED\",\"win32\":"<<GetLastError()<<"}\n"<<std::flush;continue;}CloseHandle(pi.hThread);HWND h=findWindow(pi.dwProcessId);if(!h){TerminateProcess(pi.hProcess,1);CloseHandle(pi.hProcess);std::cout<<"{\"ok\":false,\"code\":\"DETACHED_HWND_NOT_OBSERVED\"}\n"<<std::flush;continue;}windows[id]=WindowRef{id,url,prof,pi,h};RECT r{};GetWindowRect(h,&r);std::cout<<"{\"ok\":true,\"code\":\"OPEN\",\"presentationId\":\""<<jesc(narrow(id))<<"\",\"nativeId\":\""<<(unsigned long long)(UINT_PTR)h<<"\",\"bounds\":{\"x\":"<<r.left<<",\"y\":"<<r.top<<",\"width\":"<<(r.right-r.left)<<",\"height\":"<<(r.bottom-r.top)<<"}}\n"<<std::flush;continue;}
    if((op==L"WINDOW_FOCUS"||op==L"WINDOW_CLOSE"||op==L"WINDOW_BOUNDS"||op==L"WINDOW_TOPMOST")&&f.size()>=2){auto id=b64decode(f[1]);auto it=windows.find(id);if(it==windows.end()){std::cout<<"{\"ok\":false,\"code\":\"STALE_OR_UNKNOWN_PRESENTATION\"}\n"<<std::flush;continue;}if(!IsWindow(it->second.hwnd)){if(it->second.pi.hProcess)CloseHandle(it->second.pi.hProcess);windows.erase(it);std::cout<<"{\"ok\":false,\"code\":\"STALE_OR_UNKNOWN_PRESENTATION\",\"lifecycle\":\"closed\",\"closedExternally\":true}\n"<<std::flush;continue;}HWND h=it->second.hwnd;if(op==L"WINDOW_FOCUS"){ShowWindow(h,SW_RESTORE);SetForegroundWindow(h);std::cout<<"{\"ok\":true,\"focused\":"<<(GetForegroundWindow()==h?"true":"false")<<"}\n"<<std::flush;}else if(op==L"WINDOW_TOPMOST"&&f.size()>=3){bool on=f[2]==L"1";SetWindowPos(h,on?HWND_TOPMOST:HWND_NOTOPMOST,0,0,0,0,SWP_NOMOVE|SWP_NOSIZE|SWP_NOACTIVATE);auto ex=GetWindowLongPtrW(h,GWL_EXSTYLE);bool observed=(ex&WS_EX_TOPMOST)!=0;std::cout<<"{\"ok\":true,\"requested\":"<<(on?"true":"false")<<",\"observed\":"<<(observed?"true":"false")<<",\"active\":"<<((observed==on)?(observed?"true":"false"):"false")<<"}\n"<<std::flush;}else if(op==L"WINDOW_BOUNDS"){RECT r{};GetWindowRect(h,&r);std::cout<<"{\"ok\":true,\"bounds\":{\"x\":"<<r.left<<",\"y\":"<<r.top<<",\"width\":"<<(r.right-r.left)<<",\"height\":"<<(r.bottom-r.top)<<"}}\n"<<std::flush;}else if(op==L"WINDOW_CLOSE"){BOOL posted=PostMessageW(h,WM_CLOSE,0,0);if(!posted){std::cout<<"{\"ok\":false,\"closed\":false,\"code\":\"WINDOW_CLOSE_POST_FAILED\",\"win32\":"<<GetLastError()<<"}\n"<<std::flush;continue;}DWORD wait=WaitForSingleObject(it->second.pi.hProcess,3000);bool windowGone=!IsWindow(h);bool processEnded=wait==WAIT_OBJECT_0;if(windowGone||processEnded){CloseHandle(it->second.pi.hProcess);windows.erase(it);std::cout<<"{\"ok\":true,\"closed\":true,\"observedWindowGone\":"<<(windowGone?"true":"false")<<",\"observedProcessExit\":"<<(processEnded?"true":"false")<<"}\n"<<std::flush;}else{std::cout<<"{\"ok\":false,\"closed\":false,\"code\":\"WINDOW_CLOSE_NOT_CONFIRMED\"}\n"<<std::flush;}continue;}continue;}
    std::cout<<"{\"ok\":false,\"code\":\"UNKNOWN_OPERATION\"}\n"<<std::flush;
  } for(auto&[id,w]:windows){if(IsWindow(w.hwnd))PostMessageW(w.hwnd,WM_CLOSE,0,0);if(w.pi.hProcess)CloseHandle(w.pi.hProcess);}windows.clear();
}
int wmain(){auto a=parseArgs();if(a.mode==L"terminal")return terminalMode(a);if(a.mode==L"platform"){platformMode();return 0;}std::cout<<"{\"ok\":true,\"providerId\":\"cep-win32-sidecar\",\"providerVersion\":\"1.0.0\",\"modes\":[\"platform\",\"terminal\"]}\n";return 0;}
