import {NoteBindingAdapter} from './foundation/notes/note-binding.js';
import {libraryNoteBindingInput,spatialNoteBindingInput} from './adapters/note-binding-domains.js';

const assert=(condition,message)=>{if(!condition)throw Error(message)};
const stable=value=>JSON.stringify(value);
const run=(id,fn)=>{try{return {id,status:'PASS',evidence:fn()}}catch(error){return {id,status:'FAIL',error:String(error?.message||error)}}};
const rejects=(fn,token)=>{try{fn()}catch(error){const message=String(error?.message||error);assert(message.includes(token),`expected ${token}, got ${message}`);return message}throw Error(`expected rejection ${token}`)};
const available=evidence=>({state:'available',evidence});

export function runW6BNoteBindingCorrectionProof(){
  const cases=[];
  cases.push(run('01.no-source-not-applicable-remains-legal',()=>{const owner=new NoteBindingAdapter(),binding=owner.bind('note-spatial-na',spatialNoteBindingInput({noteId:'note-spatial-na',route:'PERSONAL:CEP/visualize',availability:{state:'not-applicable',reason:'no-applicable-source'}})).binding;assert(binding.availability.state==='not-applicable','not-applicable lost');assert(Object.keys(binding.source).length===0,'source fabricated');return binding}));
  cases.push(run('02.controller-repro-not-applicable-no-source-to-available-rejected',()=>{const owner=new NoteBindingAdapter();owner.bind('note-spatial-repro',spatialNoteBindingInput({noteId:'note-spatial-repro',route:'PERSONAL:CEP/visualize',availability:{state:'not-applicable',reason:'no-source'}}));const before=stable(owner.descriptor('note-spatial-repro')),sequenceBefore=owner.sequence,message=rejects(()=>owner.projectAvailability('note-spatial-repro',{state:'available'}),'SOURCE_IDENTITY_REQUIRED_FOR_AVAILABLE_BINDING');assert(stable(owner.descriptor('note-spatial-repro'))===before,'controller reproduction mutated binding');assert(owner.sequence===sequenceBefore,'rejected projection emitted receipt sequence');return {message,exactPriorRetained:true,receiptSequenceUnchanged:true}}));
  cases.push(run('03.failed-availability-projection-is-exactly-atomic',()=>{const owner=new NoteBindingAdapter();owner.bind('note-atomic',spatialNoteBindingInput({noteId:'note-atomic',route:'PERSONAL:CEP/visualize',availability:{state:'not-applicable'}}));const before=owner.descriptor('note-atomic'),beforeJson=stable(before),beforeSnapshot=stable(owner.snapshot()),sequenceBefore=owner.sequence;rejects(()=>owner.projectAvailability('note-atomic',{availability:{state:'available',evidence:{resolver:'synthetic'}}}),'SOURCE_IDENTITY_REQUIRED_FOR_AVAILABLE_BINDING');assert(stable(owner.descriptor('note-atomic'))===beforeJson,'descriptor bytes/semantic JSON changed');assert(stable(owner.snapshot())===beforeSnapshot,'binding map changed');assert(owner.sequence===sequenceBefore,'receipt sequence changed');return {descriptor:before,exactDescriptorJsonRetained:true,snapshotRetained:true,receiptSequenceUnchanged:true}}));
  cases.push(run('04.no-source-unresolved-to-available-remains-protected',()=>{const owner=new NoteBindingAdapter();owner.bind('note-unresolved',spatialNoteBindingInput({noteId:'note-unresolved',route:'PERSONAL:CEP/visualize',availability:{state:'unresolved',reason:'resolver-has-no-identity'}}));const before=stable(owner.descriptor('note-unresolved')),sequenceBefore=owner.sequence,message=rejects(()=>owner.projectAvailability('note-unresolved',{availability:{state:'available',evidence:{resolver:'back'}}}),'EXPLICIT_SOURCE_REVALIDATION_REQUIRED');assert(stable(owner.descriptor('note-unresolved'))===before,'unresolved rejection mutated binding');assert(owner.sequence===sequenceBefore,'unresolved rejection emitted receipt sequence');return {message,exactPriorRetained:true}}));
  cases.push(run('05.source-bearing-stale-to-available-still-requires-explicit-source-and-evidence',()=>{const owner=new NoteBindingAdapter();owner.bind('note-stale',libraryNoteBindingInput({noteId:'note-stale',documentId:'KU-D05-0021',blockId:'blk-d05-p1',route:'PERSONAL:CEP/library',availability:{state:'stale',reason:'resolver-offline'}}));const before=stable(owner.descriptor('note-stale'));const missingSource=rejects(()=>owner.projectAvailability('note-stale',{availability:{state:'available',evidence:{resolver:'back'}}}),'EXPLICIT_SOURCE_REVALIDATION_REQUIRED');assert(stable(owner.descriptor('note-stale'))===before,'missing-source rejection mutated binding');const missingEvidence=rejects(()=>owner.projectAvailability('note-stale',{source:{documentId:'KU-D05-0021',blockId:'blk-d05-p1'},availability:{state:'available'}}),'RESOLUTION_EVIDENCE_REQUIRED');assert(stable(owner.descriptor('note-stale'))===before,'missing-evidence rejection mutated binding');const resolved=owner.projectAvailability('note-stale',{source:{documentId:'KU-D05-0021',blockId:'blk-d05-p1'},availability:{state:'available',evidence:{resolver:'back',validated:true}}}).binding;assert(resolved.availability.state==='available','validated stale resolution failed');return {missingSource,missingEvidence,resolved:resolved.availability}}));
  cases.push(run('06.legitimate-available-binding-with-canonical-source-remains-legal',()=>{const owner=new NoteBindingAdapter(),binding=owner.bind('note-valid',spatialNoteBindingInput({noteId:'note-valid',objectId:'APP-WEB-01',route:'PERSONAL:CEP/visualize',availability:available({kind:'ENTITY_PRESENT'})})).binding;assert(binding.availability.state==='available'&&binding.source.objectId==='APP-WEB-01','valid available binding rejected');return binding}));
  cases.push(run('07.legitimate-nonviolating-availability-projections-remain-legal',()=>{const owner=new NoteBindingAdapter();owner.bind('note-status',spatialNoteBindingInput({noteId:'note-status',objectId:'APP-WEB-01',route:'PERSONAL:CEP/visualize',availability:available({kind:'ENTITY_PRESENT'})}));const stale=owner.projectAvailability('note-status',{availability:{state:'stale',reason:'view-unavailable'}});const unresolved=owner.projectAvailability('note-status',{availability:{state:'unresolved',reason:'resolver-pending'}});const owner2=new NoteBindingAdapter();owner2.bind('note-nosource',spatialNoteBindingInput({noteId:'note-nosource',route:'PERSONAL:CEP/visualize',availability:{state:'not-applicable'}}));const noSourceUnresolved=owner2.projectAvailability('note-nosource',{availability:{state:'unresolved',reason:'lookup-pending'}});assert(stale.binding.availability.state==='stale'&&unresolved.binding.availability.state==='unresolved','source-bearing legal projection failed');assert(noSourceUnresolved.binding.availability.state==='unresolved'&&Object.keys(noSourceUnresolved.binding.source).length===0,'no-source unresolved projection failed');return {stale:stale.binding.availability,unresolved:unresolved.binding.availability,noSourceUnresolved:noSourceUnresolved.binding}}));
  cases.push(run('08.spatial-shape-stays-non-structured-without-fabricated-document-block-fields',()=>{const owner=new NoteBindingAdapter();owner.bind('note-spatial-shape',spatialNoteBindingInput({noteId:'note-spatial-shape',route:'PERSONAL:CEP/visualize',availability:{state:'not-applicable'}}));const projected=owner.projectAvailability('note-spatial-shape',{availability:{state:'unresolved',reason:'entity-resolution-pending'}}).binding;assert(!('documentId'in projected.source)&&!('blockId'in projected.source),'structured fields fabricated');assert(Object.keys(projected.source).length===0,'source identity fabricated');return {domain:projected.domain,source:projected.source,availability:projected.availability}}));
  const pass=cases.filter(test=>test.status==='PASS').length,fail=cases.length-pass;
  return {schemaVersion:1,kind:'W6_B_NOTE_BINDING_AVAILABILITY_INVARIANT_CORRECTION_PROOF',status:fail?'FAIL':'PASS',pass,fail,caseCount:cases.length,cases};
}
