import {AuditProvenanceHost} from '../../foundation/audit/provenance-host.js';
import {AuditProvenanceInteractionCore} from '../../foundation/audit/provenance.js';
import {createAuditConsumerAdapter,AUDIT_COMMANDS} from '../../adapters/audit.js';

const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const STYLE=`
.s18-audit{display:grid;gap:14px;min-width:0}.s18-audit__truth{display:grid;grid-template-columns:minmax(0,1fr) minmax(260px,.42fr);gap:12px}.s18-audit__card{border:1px solid var(--border,#2b3441);border-radius:12px;background:var(--panel,#111821);padding:14px;min-width:0}.s18-audit__card h3{margin:0 0 8px;font-size:14px}.s18-audit__tokens{display:flex;gap:7px;flex-wrap:wrap}.s18-audit__token{border:1px solid var(--border,#2b3441);border-radius:999px;padding:4px 8px;font-size:11px}.s18-audit__token[data-tone="bad"]{border-color:#8c4650}.s18-audit__form{display:grid;grid-template-columns:minmax(0,.35fr) minmax(0,1fr) auto;gap:8px}.s18-audit input{min-width:0;border:1px solid var(--border,#2b3441);border-radius:9px;background:#0d131b;color:inherit;padding:9px 10px}.s18-audit button{border:1px solid var(--border,#2b3441);border-radius:9px;background:#17202b;color:inherit;padding:9px 11px;cursor:pointer}.s18-audit__notes{font-size:12px;color:var(--muted,#9ba7b8);max-height:160px;overflow:auto}.s18-audit__boundary{font-size:12px;line-height:1.55;color:var(--muted,#9ba7b8)}.s18-audit .ap-host__body{min-block-size:240px}@media(max-width:1024px){.s18-audit__truth{grid-template-columns:1fr}.s18-audit__form{grid-template-columns:1fr}.s18-audit__form button{justify-self:start}}
`;

export async function settleAuditAnnotation(effect,project=()=>{}){
  if(typeof effect!=='function')throw Error('AUDIT_ANNOTATION_EFFECT_REQUIRED');
  project(Object.freeze({state:'PENDING',code:'AUDIT_ANNOTATION_PENDING',settled:false}));
  try{
    const result=await effect(),success=result?.ok===true,state=success?'SUCCESS':'FAILURE',code=success?(result.status||result.code||'AUDIT_ANNOTATION_RECORDED'):(result?.code||result?.status||'AUDIT_ANNOTATION_FAILED');
    const settlement=Object.freeze({state,code:String(code),settled:true,result:result||null});project(settlement);return settlement;
  }catch(error){const settlement=Object.freeze({state:'FAILURE',code:String(error?.code||error?.message||'AUDIT_ANNOTATION_REJECTED'),settled:true,error:String(error?.message||error)});project(settlement);return settlement;}
}

export function mountAuditSurface({stage,registry,workspace,runtimeAdapter=null}={}){
  if(!stage||!registry)throw Error('AUDIT_PRODUCT_COMPOSITION_REQUIRED');
  const adapter=runtimeAdapter?(()=>{
    const provider={
      descriptor:()=>({providerId:'W05AuditEventProvider',domainKind:'cep-audit-events',schemaVersion:'1.0.0',authorityRef:'AuditEventProvider',label:'Durable application AuditEvents'}),
      read:()=>{const state=runtimeAdapter.snapshot(),events=state.events||[],observedAt=new Date().toISOString(),error=state.lastError;return {state:error?'ERROR':events.length?'READY':'EMPTY',identity:{id:'w05-durable-audit-events',label:'Durable application AuditEvents',revision:String(events.at(-1)?.sequence||0),correlationIds:[],provenanceRefs:['AuditEventProvider','W05AuditDomain']},entries:events.map(row=>({id:`audit-event-${row.sequence}`,label:`#${row.sequence} · ${row.action}`,kind:'AUDIT_EVENT',timestamp:row.time||row.timestamp||null,actorLabel:row.actor||'Local product user',summary:`${row.outcome||'OBSERVED'} · ${row.target||'application'}`,parentIds:row.previousHash&&row.previousHash!=='GENESIS'?[row.previousHash]:[],correlationIds:[row.correlationId].filter(Boolean),provenanceRefs:[row.recordHash].filter(Boolean),attributes:{sequence:row.sequence,recordHash:row.recordHash,previousHash:row.previousHash,outcome:row.outcome,hashAlgorithm:'SHA-256',hashIsEncryption:false,databaseImmutabilityClaim:false}})),message:error?`AuditEventProvider unavailable: ${error.code||error.error||'ERROR'}`:events.length?'Durable AuditEvents from the bounded local runtime provider.':'No durable AuditEvents observed.',observedAt,freshness:{source:'AUDIT_EVENT_PROVIDER_DURABLE_JSONL',observedAt,stale:false},truth:{domainSource:'W05AuditDomain',providerSource:'AuditEventProvider',commandReceiptSource:false,databaseImmutabilityClaim:false}};}
    };
    const provenance=new AuditProvenanceInteractionCore(provider);provenance.refresh();
    return {owner:'W05AuditDomain',runtimeAdapter,provider,provenance,search:async(filters={})=>{const result=await runtimeAdapter.search(typeof filters==='string'?{action:filters}:filters);provenance.refresh();return result},verify:async()=>{const result=await runtimeAdapter.verify();provenance.refresh();return result},annotate:async payload=>{const result=await runtimeAdapter.annotate(payload);provenance.refresh();return result},refresh:()=>provenance.refresh(),integrity:()=>runtimeAdapter.snapshot().integrity||{status:'UNVERIFIED',firstInvalidSequence:null,scope:null},annotations:()=>runtimeAdapter.snapshot().annotations||[],truth:()=>runtimeAdapter.truth()};
  })():createAuditConsumerAdapter();
  stage.innerHTML=`<section class="s18-audit" data-w05-surface="audit" data-domain-owner="W05AuditDomain"><style>${STYLE}</style><div class="s18-audit__truth"><article class="s18-audit__card" data-integrity></article><article class="s18-audit__card"><h3>Status meaning</h3><p class="s18-audit__boundary"><bdi dir="ltr">AuditEvent != SemanticCommandBus receipt</bdi><br>Application append-only contract is session-domain truth here; database immutability is not claimed. <bdi dir="ltr">SHA-256</bdi> is integrity hashing, not encryption.</p></article></div><div data-provenance></div><article class="s18-audit__card"><h3>Separate annotation revisions</h3><form class="s18-audit__form" data-annotation-form><input data-event-id inputmode="numeric" dir="ltr" placeholder="AuditEvent sequence" aria-label="AuditEvent sequence"><input data-note dir="auto" placeholder="Annotation — stored separately from AuditEvent" aria-label="Audit annotation"><button type="submit">Annotate</button></form><p class="s18-audit__boundary" data-annotation-status role="status" aria-live="polite"></p><div class="s18-audit__notes" data-annotations></div></article></section>`;
  const root=stage.querySelector('[data-provenance]'),host=new AuditProvenanceHost(root,adapter.provenance);
  const renderIntegrity=()=>{const i=adapter.integrity(),t=adapter.truth(),el=stage.querySelector('[data-integrity]'),scope=i.scope||{},watermark=scope.watermark||scope.toHash||scope.toSequence||'unobserved';el.innerHTML=`<h3>Hash-chain verification</h3><div class="s18-audit__tokens"><span class="s18-audit__token" data-tone="${i.status==='VALID_CHAIN'?'ok':'bad'}">${esc(i.status||'UNVERIFIED')}</span><span class="s18-audit__token"><bdi dir="ltr">events ${t.eventCount||0}</bdi></span><span class="s18-audit__token"><bdi dir="ltr">persistence ${esc(t.persistence||'SESSION_LOCAL')}</bdi></span><span class="s18-audit__token"><bdi dir="ltr">annotations ${t.annotationCount??adapter.annotations().length}</bdi></span></div><p class="s18-audit__boundary">First invalid: <bdi dir="ltr">${esc(i.firstInvalidSequence??'none')}</bdi> · scope <bdi dir="ltr">${esc(watermark)}</bdi></p>`;};
  const renderNotes=()=>{const rows=adapter.annotations(),el=stage.querySelector('[data-annotations]');el.innerHTML=rows.length?rows.map(row=>`<p><bdi dir="ltr">event ${esc(row.eventId)} · rev ${esc(row.revision)}</bdi> — <span dir="auto">${esc(row.note)}</span></p>`).join(''):'<p>No annotation revisions. AuditEvent bytes remain unchanged.</p>';};
  const render=()=>{adapter.refresh();host.render();renderIntegrity();renderNotes();const integrity=adapter.integrity(),truth=adapter.truth();workspace?.region?.('LEFT',{node:root,label:'AuditEvent / provenance'});workspace?.region?.('RIGHT',{html:`<section class="s18-audit__card"><h3>Selected integrity context</h3><p><bdi dir="ltr">${esc(integrity.status||'UNVERIFIED')}</bdi></p><p>Events <bdi dir="ltr">${esc(truth.eventCount||0)}</bdi> · persistence <bdi dir="ltr">${esc(truth.persistence||'SESSION_LOCAL')}</bdi></p><p>First invalid <bdi dir="ltr">${esc(integrity.firstInvalidSequence??'none')}</bdi></p></section>`,label:'Audit context'});workspace?.region?.('BOTTOM',{html:`<section class="s18-audit__card"><h3>Annotation revisions</h3>${adapter.annotations().length?adapter.annotations().map(row=>`<p><bdi dir="ltr">event ${esc(row.eventId)} · rev ${esc(row.revision)}</bdi> — <span dir="auto">${esc(row.note)}</span></p>`).join(''):'<p>No annotation revisions. AuditEvent bytes remain unchanged.</p>'}</section>`,label:'Audit revisions',summary:'Annotation revisions remain separate from immutable AuditEvent bytes.'});workspace?.status?.(`AuditEvent chain · ${truth.eventCount} events · ${integrity.status}`,'info');workspace?.refreshToolbar?.();};
  registry.register('audit.search',adapter.owner,'Search AuditEvents',async payload=>{const r=await adapter.search(payload?.filters||payload?.query||{});render();return r},()=>true);
  registry.register('audit.verify',adapter.owner,'Verify AuditEvent hash chain',async()=>{const r=await adapter.verify();render();return r},()=>true);
  registry.register('audit.annotate',adapter.owner,'Annotate AuditEvent',async payload=>{const r=await adapter.annotate(payload||{});render();return r},payload=>payload?.eventId&&String(payload?.note||'').trim()?true:'AuditEvent sequence and annotation text required');
  stage.querySelector('[data-annotation-form]').addEventListener('submit',async event=>{event.preventDefault();const eventId=stage.querySelector('[data-event-id]').value,noteField=stage.querySelector('[data-note]'),note=noteField.value,button=event.currentTarget.querySelector('button[type=submit]'),status=stage.querySelector('[data-annotation-status]');button.disabled=true;const settlement=await settleAuditAnnotation(()=>registry.execute('audit.annotate',{eventId,note,route:'audit.annotation-form'}),state=>{status.dataset.state=state.state;status.dataset.code=state.code;status.textContent=state.state==='PENDING'?'Annotation pending…':state.state==='SUCCESS'?'Annotation revision recorded separately':`Annotation unavailable · ${state.code}`;workspace?.status?.(status.textContent,state.state==='FAILURE'?'error':'info')});button.disabled=false;if(settlement.state==='SUCCESS')noteField.value='';render();});
  stage.dataset.surfaceComposition='audit-trace-workbench';render();if(runtimeAdapter)Promise.allSettled([runtimeAdapter.search({limit:100}),runtimeAdapter.verify()]).then(()=>render());workspace?.toolbar?.([...AUDIT_COMMANDS,'foundation.settings']);
  return Object.freeze({owner:'AuditTraceWorkbench',adapter,host,render,realProductConsumer:true,slots:{CENTER:'AuditTraceWorkbench',BOTTOM:'shared-bottom-shell/domain-projection'}});
}
