import {RUNTIME_ADAPTER_CONTRACT} from '../foundation/operational.js';
const clone=v=>structuredClone(v);const base=()=>globalThis.CEP_LOCAL_RUNTIME_URL||'http://127.0.0.1:4174';
async function call(path,{method='GET',body=null}={}){const r=await fetch(base()+path,{method,headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const j=await r.json();if(!r.ok||j.ok===false)throw Error(j.code||j.message||`HTTP_${r.status}`);return j;}
const bytesFromBase64=value=>{if(!value)return new Uint8Array();const bin=atob(value),out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out};
const appendBase64=(current,next)=>{const a=bytesFromBase64(current),b=bytesFromBase64(next),all=new Uint8Array(a.length+b.length);all.set(a);all.set(b,a.length);let binary='';for(const byte of all)binary+=String.fromCharCode(byte);return btoa(binary)};
export class WindowsTerminalRuntimeAdapter{
 constructor(options: any = {}){this.kind='WindowsConptyRuntimeAdapter';this.connected=options?.connected!==false;this.platformCapabilities=options?.platformCapabilities||null;this.sessions=new Map();this.pollers=new Map();this.listeners=new Map();}
 descriptor(){const cap=this.platformCapabilities;const psAvailable=cap?(cap.powershell===true||cap.powerShell?.availability?.startsWith?.('AVAILABLE')||cap.powershell?.availability?.startsWith?.('AVAILABLE')):(this.connected&&(globalThis.process?.platform==='win32'||typeof globalThis.window==='undefined'));const sshAvailable=cap?(cap.ssh===true||cap.ssh?.availability?.startsWith?.('AVAILABLE')):(this.connected&&(globalThis.process?.platform==='win32'||typeof globalThis.window==='undefined'));return {contract:RUNTIME_ADAPTER_CONTRACT,id:this.kind,label:'Windows terminal',inputLabel:'',help:'Raw Windows PTY stream',commandOwner:null,sessionOwner:'TerminalRuntimeCapability',capabilities:['OPEN_TERMINAL','runtime.raw-input','runtime.resize','runtime.restart'],connected:this.connected,runtimeTruth:'WINDOWS_CONPTY',nativeTerminal:true,rawTerminal:true,pty:true,conpty:true,powershell:Boolean(psAvailable),ssh:Boolean(sshAvailable),persistence:false,prompt:()=>''};}
 session(id){return this.sessions.get(id)||null}
 subscribe(id,handler){if(typeof handler!=='function')throw Error('TERMINAL_SUBSCRIBER_REQUIRED');let set=this.listeners.get(id);if(!set)this.listeners.set(id,set=new Set());set.add(handler);return {dispose:()=>{set.delete(handler);if(!set.size)this.listeners.delete(id)}}}
 _emit(id,event){for(const handler of this.listeners.get(id)||[]){try{handler(event)}catch{}}}
 _shape(remote,profile,label=null){return {id:remote.id,deviceId:remote.deviceId||label||profile?.label||profile?.executable||remote.id,toolId:remote.toolId||label||profile?.label||profile?.executable||remote.id,runId:remote.runId||'windows-conpty',epoch:remote.epoch||null,recorded:false,lines:[],history:[],rawOutputBase64:'',outputCursor:0,outputGeneration:Number(remote.restartCount)||0,presentation:{state:remote.state||'starting',detail:remote.detail||'Starting Windows ConPTY.',sequence:0,transitions:[]},profile:clone(remote.profile||profile||{}),restartCount:Number(remote.restartCount)||0,exitCode:remote.exitCode??null};}
 async openProfile(profile){const r=await call('/v1/terminal/open',{method:'POST',body:profile}),s=this._shape(r.session,profile);this.sessions.set(s.id,s);this._poll(s.id);return s;}
 async attachSession(sessionId,{label=null}={}){const id=String(sessionId||'').trim();if(!id)throw Error('TERMINAL_SESSION_ID_REQUIRED');const r=await call(`/v1/terminal/session/${encodeURIComponent(id)}?cursor=0`),s=this._shape(r.session,r.session.profile,label);s.rawOutputBase64=r.dataBase64||'';s.outputCursor=r.nextCursor||0;s.presentation.sequence=s.outputCursor;s.attachedExisting=true;this.sessions.set(id,s);this._poll(id);return s;}
 async _poll(id){if(this.pollers.has(id))return;const tick=async()=>{const s=this.sessions.get(id);if(!s){this.pollers.delete(id);return}try{const r=await call(`/v1/terminal/session/${encodeURIComponent(id)}?cursor=${s.outputCursor||0}`),remoteRestart=Number(r.session.restartCount)||0;if(remoteRestart!==s.outputGeneration){s.rawOutputBase64='';s.outputCursor=0;s.outputGeneration=remoteRestart;s.restartCount=remoteRestart;s.epoch=r.session.epoch??s.epoch;this._emit(id,{type:'reset',session:s,generation:remoteRestart});this.pollers.set(id,setTimeout(tick,0));return}if(r.dataBase64){s.rawOutputBase64=appendBase64(s.rawOutputBase64,r.dataBase64);this._emit(id,{type:'output',session:s,data:bytesFromBase64(r.dataBase64),cursor:r.nextCursor,generation:s.outputGeneration})}s.outputCursor=r.nextCursor;s.epoch=r.session.epoch??s.epoch;s.restartCount=remoteRestart;s.presentation={state:r.session.state,detail:r.session.detail||'',sequence:r.nextCursor,transitions:[]};s.exitCode=r.session.exitCode;if(r.session.state==='completed'||r.session.state==='error')this._emit(id,{type:'state',session:s,state:r.session.state,exitCode:s.exitCode,generation:s.outputGeneration});}catch(e){s.presentation={state:'error',detail:String(e?.message||e),sequence:s.outputCursor,transitions:[]};this._emit(id,{type:'error',session:s,error:s.presentation.detail,generation:s.outputGeneration})}this.pollers.set(id,setTimeout(tick,120));};await tick();}
 input(id,data){const bytes=new TextEncoder().encode(String(data));let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return call('/v1/terminal/input',{method:'POST',body:{sessionId:id,dataBase64:btoa(binary)}})}
 resize(id,cols,rows){return call('/v1/terminal/resize',{method:'POST',body:{sessionId:id,cols,rows}})}
 async restart(id){const current=this.sessions.get(id);if(!current)throw Error('UNKNOWN_TERMINAL_SESSION:'+id);const r=await call('/v1/terminal/restart',{method:'POST',body:{sessionId:id}}),fresh=this._shape(r.session,r.session.profile||current.profile,current.deviceId);fresh.outputGeneration=Number(r.session.restartCount)||current.outputGeneration+1;fresh.restartCount=fresh.outputGeneration;this.sessions.set(id,fresh);this._emit(id,{type:'reset',session:fresh,generation:fresh.outputGeneration});this._poll(id);return fresh;}
 async close(id){const t=this.pollers.get(id);if(t)clearTimeout(t);this.pollers.delete(id);const r=await call('/v1/terminal/close',{method:'POST',body:{sessionId:id}});this.sessions.delete(id);this._emit(id,{type:'closed',sessionId:id});this.listeners.delete(id);return r}
}
