import {RelationDomainAdapter} from '../foundation/relations.js';
import {SpatialView} from '../foundation/spatial.js';
import {TodayProjectionDomainAdapter} from '../adapters/today/domain.js';
import {RQDomainAdapter} from '../adapters/rq/domain.js';
import {VisualizeDomainAdapter} from '../adapters/visualize/domain.js';
import {BALANCED6_VISUALIZE_REPRESENTATIONS,createBalanced6VisualizeProvider} from '../adapters/balanced6-acceptance-data.js';
import {bindTodaySurface,composeTodayOrchestrationPresentation} from './today/surface.js';
import {bindRqSurface} from './rq/surface.js';
import {bindShellSurfaceCommands} from './shell/surface.js';
import {bindLibrarySurface} from './library/surface.js';
import {bindLearnSurface} from './learn/surface.js';
import {bindVisualizeSurface} from './visualize/surface.js';
import {W03EnterpriseDomain} from '../adapters/enterprise/domain.js';
import {W03LabDomain} from '../adapters/labs/domain.js';
import {W03ResultsDomain} from '../adapters/results/domain.js';
import {W03ScenarioDomain} from '../adapters/scenarios/domain.js';
import {composeEnterpriseSurface} from './enterprise/index.js';
import {composeLabsSurface} from './labs/index.js';
import {composeResultsSurface} from './results/index.js';
import {composeScenariosSurface} from './scenarios/index.js';
import {W04EvidenceDomain} from '../adapters/evidence/domain.js';
import {W04MasteryDomain} from '../adapters/mastery/domain.js';
import {W04PortfolioDomain} from '../adapters/portfolio/domain.js';
import {W04ReviewDomain,REVIEW_DECISION_OUTCOMES,REVIEW_FINDING_OUTCOMES} from '../adapters/reviews/domain.js';
import {createConfigurationSurfaceComposition} from './configuration/composition.js';
import {createManualAiSurfaceComposition} from './manual_ai/composition.js';
import {createReleasesSurfaceComposition} from './releases/composition.js';
import {createBackupRuntimeAdapter} from '../adapters/backup-runtime.js';
import {createHealthRuntimeAdapter} from '../adapters/health-runtime.js';
import {createProcessingRuntimeAdapter} from '../adapters/processing-runtime.js';
import {mountAuditSurface} from './audit/index.js';
import {mountValidationSurface} from './validation/index.js';
import {defineContextDescriptorProvider} from '../foundation/global/context-descriptor-contract.js';
import {AnalyticalCompareHost} from '../foundation/analytical/compare-host.js';
import {createW04RescueComposition} from './composition/w04-rescue.js';
import {createW05RescueComposition} from './composition/w05-rescue.js';

const html=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const titleCase=value=>String(value).replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const diagnosticsEnabled=()=>{try{const mode=new URLSearchParams(location.search).get('diagnostics');return mode==='foundation'||mode==='1'||localStorage.getItem('cep.diagnostics')==='1'}catch{return false}};
function ensureM0Style(){
  if(document.querySelector('#m0ControllerStyle'))return;
  const style=document.createElement('style');style.id='m0ControllerStyle';style.textContent=`
  .m0-controller-stage{min-width:0;min-height:0;height:100%;overflow:auto;padding:clamp(10px,1.5vw,20px);direction:inherit;box-sizing:border-box}
  .m0-studio{display:grid;gap:14px;min-width:0;direction:inherit}.m0-studio-head{display:flex;align-items:flex-start;justify-content:space-between;gap:14px;flex-wrap:wrap;border:1px solid var(--line);border-radius:12px;padding:14px;background:color-mix(in srgb,var(--panel) 92%,transparent)}
  .m0-studio-head h1{margin:3px 0 5px;font-size:clamp(20px,2vw,30px)}.m0-studio-head p{margin:0;color:var(--text2);max-width:72ch}.m0-eyebrow{font:600 10px var(--mono);text-transform:uppercase;letter-spacing:.08em;color:var(--accent)}
  .m0-command-strip,.m0-command-stack{display:flex;flex-wrap:wrap;gap:7px}.m0-command-strip .btn[disabled],.m0-command-stack .btn[disabled]{opacity:.55;text-decoration:none}.m0-studio-grid{display:grid;direction:ltr;grid-template-columns:minmax(180px,.7fr) minmax(300px,1.6fr) minmax(210px,.8fr);gap:12px;min-width:0;align-items:start}.m0-studio-grid[data-diagnostics="false"]{grid-template-columns:minmax(180px,.72fr) minmax(0,1.7fr)}
  .m0-collection-panel,.m0-workbench,.m0-truth{direction:rtl}.m0-collection,.m0-workbench,.m0-truth,.m0-domain-nav,.m0-structured-spatial,.m0-results-spatial,.m0-results-compare{border:1px solid var(--line);border-radius:12px;background:color-mix(in srgb,var(--panel) 94%,transparent);padding:12px;min-width:0}.m0-collection{display:grid;gap:6px}.m0-row{display:grid;gap:2px;text-align:start;border:1px solid transparent;border-radius:8px;background:transparent;color:inherit;padding:9px;cursor:pointer}.m0-row:hover,.m0-row[aria-pressed=true]{border-color:var(--line);background:rgba(255,255,255,.035)}.m0-row strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.m0-row small{color:var(--text3);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
  .m0-table-wrap{overflow:auto;border:1px solid var(--line);border-radius:10px;max-width:100%}.m0-table{width:100%;border-collapse:collapse;min-width:0;table-layout:fixed}.m0-table th,.m0-table td{padding:9px 10px;border-bottom:1px solid var(--line);text-align:start;vertical-align:top}.m0-table th{font-size:11px;color:var(--text3);position:sticky;top:0;background:var(--panel);z-index:1}.m0-table tr[aria-selected=true]{background:rgba(255,255,255,.045)}.m0-table tr:focus-visible{outline:2px solid var(--accent);outline-offset:-2px}.m0-table td small{display:block;color:var(--text3);margin-top:3px}.m0-table th,.m0-table td{overflow-wrap:break-word;word-break:normal}.m0-table bdi,.m0-semantic-list bdi{unicode-bidi:isolate}.m0-field-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.m0-field-grid label{display:grid;gap:4px;color:var(--text2);font-size:12px}.m0-field-grid input,.m0-field-grid textarea{width:100%;box-sizing:border-box}.m0-diagnostics{border-style:dashed}.m0-semantic-list{display:grid;gap:8px;margin:0}.m0-semantic-list>div{display:grid;grid-template-columns:minmax(120px,.4fr) minmax(0,1fr);gap:10px;padding-block:5px;border-bottom:1px solid color-mix(in srgb,var(--line) 65%,transparent)}.m0-semantic-list dt{font-weight:650;color:var(--text2)}.m0-semantic-list dd{margin:0;min-width:0;overflow-wrap:break-word;word-break:normal}.m0-technical-token{display:block;max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;direction:ltr;unicode-bidi:isolate}.m0-bottom-projection{margin-top:14px;padding-top:12px;border-top:1px solid var(--line)}.m0-truth p{color:var(--text2)}.m0-structured-spatial,.m0-results-spatial{margin-block:12px;min-height:250px}.m0-spatial-host{height:280px;min-height:220px}.m0-results-compare{margin-block-start:12px;overflow:auto}
  .m0-empty-guidance{margin-top:14px;border:1px solid var(--line);border-radius:10px;padding:12px;background:rgba(255,255,255,.02)}.m0-empty-guidance h3{margin:0 0 8px}.m0-empty-guidance ul{margin:0;padding-inline-start:20px;color:var(--text2);display:grid;gap:6px}.m0-domain-nav{display:grid;gap:10px}.m0-domain-nav h2{margin:0}.m0-domain-nav p{margin:0;color:var(--text2)}.m0-region-list{list-style:none;margin:0;padding:0;display:grid;gap:6px}.m0-region-list li{display:grid;gap:2px;min-width:0;padding:8px 9px;border:1px solid color-mix(in srgb,var(--line) 72%,transparent);border-radius:8px;background:rgba(255,255,255,.02)}.m0-region-list strong{overflow-wrap:anywhere}.m0-region-list small{color:var(--text3);overflow-wrap:anywhere}.m0-region-list bdi{direction:ltr;unicode-bidi:isolate}
  @media(max-width:1100px){.m0-studio-grid,.m0-studio-grid[data-diagnostics="false"]{grid-template-columns:minmax(160px,.68fr) minmax(0,1.5fr)}.m0-truth{grid-column:1/-1}.m0-spatial-host{height:240px}}
  @media(max-width:760px){.m0-controller-stage{padding:8px}.m0-studio-grid,.m0-studio-grid[data-diagnostics="false"]{grid-template-columns:1fr}.m0-studio-head{display:grid}.m0-truth{grid-column:auto}.m0-spatial-host{height:220px}.m0-field-grid{grid-template-columns:1fr}}
  @media(prefers-reduced-motion:reduce){.m0-controller-stage *{scroll-behavior:auto!important;transition:none!important;animation:none!important}}
  `;document.head.append(style);
}
function availabilityFor(registry,id,payload={}){try{return registry.availability(id,payload)}catch(error){return {enabled:false,reason:String(error?.message||error),code:'AVAILABILITY_ERROR'}}}
function commandButton(registry,id,payload={}){const command=registry.commands.get(id),a=availabilityFor(registry,id,payload),reason=a.reason||(!a.enabled?a.code||'Unavailable':'');return `<button type="button" class="btn" data-foundation-command="${html(id)}" ${a.enabled?'':`disabled aria-disabled="true"`} title="${html(reason)}">${html(command?.label||id)}</button>`}
function registerM0Context(wave3Assembly,{consumer,domain,summary='',snapshot=()=>({})}={}){
  const host=wave3Assembly?.contextInspector,element=wave3Assembly?.contextContainer;if(!host||!element)return null;const id=`m0.${consumer}.context`;
  if(!host.providerIds().includes(id))host.registerProvider(defineContextDescriptorProvider({id,family:`w03-${consumer}`,owner:domain?.owner||`M0:${consumer}`,isApplicable:()=>true,describe:()=>{const value=snapshot()||{},revision=value.revisionId||value.version||value.status||'current',lenses=[{id:'identity',label:'Context',tabs:[{id:'current',label:'Current',fields:[{id:'state',label:'State',value:value.status||value.state||'AVAILABLE'},{id:'revision',label:'Revision / version',value:String(revision),technical:true}]}]}];if(diagnosticsEnabled())lenses.push({id:'diagnostics',label:'Diagnostics',tabs:[{id:'truth',label:'Implementation',fields:[{id:'owner',label:'Domain owner',value:domain?.owner||'Unavailable',technical:true},{id:'provider',label:'Provider truth',value:JSON.stringify(value.persistence||value.runtimeTruth||{canonicalMutation:'COMMAND_ONLY'}),technical:true}]}]});return {id:`${id}:${revision}`,providerId:id,family:`w03-${consumer}`,subject:`${titleCase(consumer)} workspace`,eyebrow:'Workspace context',summary,domainOwner:domain?.owner||`M0:${consumer}`,revisionToken:String(revision),lenses};}}));
  const state=host.snapshot();if(!state.open)host.open(id,{}, {invoker:document.activeElement,element,fallbackFocus:()=>document.querySelector('#centerPane')});else host.activate(id,{});wave3Assembly.renderContext?.();return id;
}
function ensureStage({consumer,preserveStructured=false}){
  ensureM0Style();
  const center=document.querySelector('#centerPane');if(!center)return null;
  let stage=center.querySelector('#foundationStage');
  if(!stage){stage=document.createElement('div');stage.className='foundation-stage m0-controller-stage';stage.id='foundationStage';center.append(stage)}
  if(!preserveStructured){const doc=center.querySelector('.docscroll');if(doc){doc.hidden=true;doc.setAttribute('aria-hidden','true');doc.inert=true}}
  stage.dataset.m0Composition=consumer;stage.hidden=false;return stage;
}
function seedRelations(surface,labels){const nodes=labels.map((label,index)=>({id:`${surface}-${index+1}`,label,type:'work-item'}));return new RelationDomainAdapter({owner:`${surface}.RelationDomainAdapter`,nodes,relations:[],types:['relates','depends','connects'],readOnly:false,capabilities:{relationAuthoring:true}})}
function mountEmbeddedSpatial(host,labels){host.innerHTML='<div class="m0-spatial-host" data-m0-spatial></div>';const nodes=labels.map((label,index)=>({id:`studio-node-${index+1}`,label,x:100+(index%3)*210,y:90+Math.floor(index/3)*145,type:'work-item'})),edges=nodes.slice(1).map((node,index)=>({id:`studio-edge-${index+1}`,source:nodes[index].id,target:node.id,type:'depends',direction:'directed',kind:'representation'}));const view=new SpatialView(host.querySelector('[data-m0-spatial]'),nodes,edges);requestAnimationFrame(()=>view.fit());return view}
function setBanner(consumer,label,detail='Controller-composed product surface'){
  const banner=document.querySelector('#topBanner');if(!banner)return;banner.setAttribute('aria-label',`${label} product workspace`);banner.querySelector('.title')?.replaceChildren(document.createTextNode(label));const badge=banner.querySelector('.badge');if(badge)badge.textContent=titleCase(consumer);const lock=banner.querySelector('.lock span');if(lock)lock.textContent=detail;
}
function scalar(value){if(value===null||value===undefined)return '—';if(typeof value==='boolean')return value?'Yes':'No';if(Array.isArray(value))return value.length?value.map(item=>typeof item==='object'?(item.id||item.label||item.ref||'record'):String(item)).join(' · '):'None';if(typeof value==='object')return value.id||value.label||value.state||value.status||value.code||'Available';return String(value)}
function semanticProjection(value,{depth=0}={}){
  if(value===null||value===undefined)return '<p class="state-token" data-state="empty">No current projection.</p>';
  if(typeof value!=='object')return `<p>${html(scalar(value))}</p>`;
  const hidden=diagnosticsEnabled()?['receipts','history']:['owner','domainOwner','semanticOwner','provider','providerId','driverId','contract','receipts','history','authorityRef'];const entries=Object.entries(value).filter(([key])=>!hidden.includes(key));
  if(!entries.length)return '<p class="state-token" data-state="empty">No additional details.</p>';
  return `<dl class="m0-semantic-list">${entries.map(([key,item])=>{const label=titleCase(key);if(item&&typeof item==='object'&&depth<1){return `<div><dt>${html(label)}</dt><dd>${semanticProjection(item,{depth:depth+1})}</dd></div>`}const technical=/(?:^|_)(?:id|sha|hash|digest|revision|ref|path|version)(?:$|_)/i.test(key)||/(?:Id|SHA|Hash|Digest|Revision|Ref|Path|Version)$/.test(key);const shown=html(scalar(item));return `<div><dt>${html(label)}</dt><dd dir="${technical?'ltr':'auto'}">${technical?`<bdi class="m0-technical-token" dir="ltr" title="${shown}">${shown}</bdi>`:shown}</dd></div>`}).join('')}</dl>`;
}
function localizedRegionLabel(value){
  if(value===null||value===undefined)return '';
  if(typeof value!=='object')return String(value);
  return String(value.labels?.ar||value.labels?.en||value.title?.ar||value.title?.en||value.label?.ar||value.label?.en||value.label||value.id||value.area||value.kind||'Item');
}
function compactRegionList(items=[]){
  const rows=Array.isArray(items)?items:[];
  if(!rows.length)return '<p class="state-token" data-state="empty">No current items.</p>';
  return `<ul class="m0-region-list">${rows.map(item=>{const primary=localizedRegionLabel(item),rawMeta=[item?.kind,item?.status,item?.state,item?.id,item?.area,item?.target],meta=rawMeta.filter(value=>['string','number','boolean'].includes(typeof value)).map(String).filter((value,index,array)=>array.indexOf(value)===index&&value!==primary).join(' · ');return `<li><strong dir="auto">${html(primary)}</strong>${meta?`<small><bdi dir="ltr">${html(meta)}</bdi></small>`:''}</li>`}).join('')}</ul>`;
}
function typedCell(adapter,row,column){try{return adapter&&column?adapter.columns.includes(column)?null:null:null}catch{return null}}
function renderTypedCollectionStage(stage,{workspace=null,surface,title,summary,collection=null,rows=null,columns=null,commands=[],registry,truth=[],payloadFor=null,detailFor=null,bottomFor=null,rowId=null,rowLabel=null,rowMeta=null,collectionMode='auto',emptyGuidance=[],emptyMessage='No current records.',emptyLabel=null}={}){
  const adapter=collection?.adapter||null,currentRows=()=>collection?collection.snapshot().visibleRows:(typeof rows==='function'?rows():Array.isArray(rows)?rows:[]),idOf=(row,index)=>adapter?adapter.rowId(row):String(rowId?.(row,index)||row?.id||row?.key||row?.candidateId||row?.resultId||`row-${index+1}`),labelOf=(row,index)=>adapter?adapter.rowLabel(row):String(rowLabel?.(row,index)||row?.title||row?.label||row?.subject||row?.key||row?.candidateId||row?.resultId||row?.id||`Item ${index+1}`),metaOf=(row,index)=>String(rowMeta?.(row,index)||row?.revisionId||row?.revision||row?.state||row?.status||''),cols=columns||adapter?.columns||[];
  let selectedIndex=0,currentPayload={};
  const render=()=>{
    const list=currentRows();if(selectedIndex>=list.length)selectedIndex=Math.max(0,list.length-1);const selected=list[selectedIndex]||null,payload=typeof payloadFor==='function'?payloadFor(selected,selectedIndex,list):{id:selected?idOf(selected,selectedIndex):null,route:`r6-${surface}`};currentPayload=payload||{};
    const table=collectionMode!=='list'&&cols.length&&list.length?`<div class="m0-table-wrap"><table class="m0-table"><thead><tr>${cols.map(col=>`<th scope="col">${html(col.label||titleCase(col.id))}</th>`).join('')}</tr></thead><tbody>${list.map((row,index)=>`<tr data-r6-row="${html(idOf(row,index))}" tabindex="0" aria-selected="${index===selectedIndex}">${cols.map(col=>{let cell={text:'',secondary:''};try{cell=adapter?collection.cell(row,col.id):(typeof col.cell==='function'?col.cell(row):{text:scalar(row?.[col.id])})}catch(error){cell={text:'Unavailable',secondary:String(error?.message||error)}}return `<td><strong dir="auto">${html(cell?.text??'')}</strong>${cell?.secondary?`<small dir="auto">${html(cell.secondary)}</small>`:''}</td>`}).join('')}</tr>`).join('')}</tbody></table></div>`:`<div class="m0-collection">${list.length?list.map((row,index)=>`<button type="button" class="m0-row" data-r6-row="${html(idOf(row,index))}" aria-pressed="${index===selectedIndex}"><strong>${html(labelOf(row,index))}</strong><small>${html(metaOf(row,index))}</small></button>`).join(''):`<p class="state-token" data-state="empty">${html(emptyMessage)}</p>`}</div>`;
    const detail=selected?(detailFor?.(selected,selectedIndex,list)??selected):{state:'EMPTY'},bottom=selected?(bottomFor?.(selected,selectedIndex,list)??null):null,diagnostic=diagnosticsEnabled();
    stage.innerHTML=`<section class="m0-studio" data-controller-composed="true" data-r6-typed-surface="${html(surface)}"><header class="m0-studio-head"><div><span class="m0-eyebrow">Workspace</span><h1>${html(title)}</h1><p>${html(summary)}</p></div></header><section class="m0-workbench" data-r6-workbench tabindex="0"><h2>${html(selected?labelOf(selected,selectedIndex):(emptyLabel||title))}</h2>${semanticProjection(detail)}${!selected&&emptyGuidance.length?`<section class="m0-empty-guidance"><h3>How this workspace works</h3><ul>${emptyGuidance.map(item=>`<li>${html(item)}</li>`).join('')}</ul></section>`:''}</section>${diagnostic?`<aside class="m0-truth m0-diagnostics" data-product-diagnostics><h2>Diagnostics</h2>${truth.map(item=>`<p>${html(item)}</p>`).join('')}</aside>`:''}</section>`;
    const left=workspace?.region?.('LEFT',{html:`<section class="m0-collection-panel" aria-label="${html(title)} collection">${table}</section>`,label:`${title} · Collection`});
    workspace?.region?.('RIGHT',{html:`<section class="m0-workbench" data-region-context="selected"><h2>${html(selected?labelOf(selected,selectedIndex):(emptyLabel||title))}</h2>${semanticProjection(detail)}</section>`,label:`${title} · Context`});
    workspace?.region?.('BOTTOM',{html:bottom?`<section class="m0-bottom-projection"><h3>Deep detail</h3>${semanticProjection(bottom)}</section>`:'<p class="state-token" data-state="empty">No domain-owned deep projection is currently bound; no history or provider result is inferred.</p>',label:`${title} · Detail`,summary:bottom?'Domain-owned detail projection is available.':'No domain-owned deep projection is bound.'});
    workspace?.refreshToolbar?.();
    const refreshSelection=index=>{selectedIndex=index;render()};
    left?.querySelectorAll?.('[data-r6-row]').forEach((node,index)=>{node.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();refreshSelection(index)});node.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();event.stopPropagation();refreshSelection(index)}})});
    stage.querySelectorAll('[data-foundation-command]').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();const id=button.dataset.foundationCommand;try{const result=registry.execute(id,{...currentPayload,invoker:button,route:`r6-${surface}`});Promise.resolve(result).then(value=>{workspaceStatus(stage,value);render()}).catch(error=>{stage.dataset.lastCommandError=String(error?.message||error)})}catch(error){stage.dataset.lastCommandError=String(error?.message||error)}}));
  };
  workspace?.toolbar?.(commands,{contextProvider:()=>currentPayload});
  render();return {render,selected:()=>currentRows()[selectedIndex]||null,payload:()=>({...currentPayload})};
}
function workspaceStatus(stage,value){const status=value?.ok===false||value?.enabled===false?'error':'ok';stage.dataset.lastCommandStatus=status;stage.dataset.lastCommandCode=String(value?.code||value?.status||value?.state||'OK')}
function bridgeSemanticCommandBus(registry,bus){if(!bus?.items)return [];const ids=[];for(const item of bus.items()){if(registry.commands.has(item.id)){const current=registry.commands.get(item.id);if(current.owner!==item.owner)throw Error(`R6_DUPLICATE_COMMAND_OWNER:${item.id}:${current.owner}:${item.owner}`);continue}registry.register(item.id,item.owner,item.label,p=>bus.execute(item.id,p),p=>bus.availability(item.id,p));ids.push(item.id)}return ids}
function mountStructuredStudio({consumer,domain,composition,workspace,registry,structured,wave3Assembly,api}){
  ensureM0Style();setBanner(consumer,consumer==='labs'?'Labs · Structured + Spatial Studio':'Scenarios · Structured + Spatial Studio','Authoring workspace · structure, relationships and validation');
  const doc=document.querySelector('#centerPane .docscroll');if(doc){doc.hidden=false;doc.removeAttribute('aria-hidden');doc.inert=false;doc.dataset.m0StructuredStudio='true'}
  let spatialHost=document.querySelector('#m0StructuredSpatial');if(!spatialHost){spatialHost=document.createElement('section');spatialHost.id='m0StructuredSpatial';spatialHost.className='m0-structured-spatial';spatialHost.innerHTML='<h2>Spatial structure</h2><p>Shared spatial authoring projection; canonical domain mutation stays behind semantic commands.</p><div data-m0-spatial-slot></div>';doc?.append(spatialHost);mountEmbeddedSpatial(spatialHost.querySelector('[data-m0-spatial-slot]'),consumer==='labs'?['Task A','Task B','Validation']:['Phase 1','Lab module','Decision'])}
  const commandIds=consumer==='labs'?['labs.author','labs.revise','labs.preflight','labs.handoff']:['scenarios.author','scenarios.revise','scenarios.validate','scenarios.prepare'];
  const snapshot=domain.snapshot(),left=document.querySelector('#leftPane .pbody');if(left)left.innerHTML=`<section class="m0-domain-nav"><h2>${html(titleCase(consumer))} authoring</h2><p>Edit the structured definition and its spatial relationships in one workspace.</p><div class="m0-command-stack">${commandIds.map(id=>commandButton(registry,id,{route:`${consumer}-studio`})).join('')}</div><div data-m0-domain-summary>${semanticProjection({state:snapshot.status||snapshot.state||'ACTIVE',revision:snapshot.revisionId||snapshot.version||'current',workspaceFirst:true,globalReadEditMode:false})}</div></section>`;
  const refresh=()=>{const current=domain.snapshot(),summary=left?.querySelector('[data-m0-domain-summary]');if(summary)summary.innerHTML=semanticProjection({state:current.status||current.state||'ACTIVE',revision:current.revisionId||current.version||'current',workspaceFirst:true,globalReadEditMode:false});left?.querySelectorAll('[data-foundation-command]').forEach(button=>{const a=availabilityFor(registry,button.dataset.foundationCommand,{route:`${consumer}-studio`});button.disabled=!a.enabled;button.title=a.reason||''});registerM0Context(wave3Assembly,{consumer,domain,summary:'Structured authoring and Spatial structure share the application-level pane, focus, toolbar and context owners.',snapshot:()=>current})};
  left?.querySelectorAll('[data-foundation-command]').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.foundationCommand;let payload={route:`${consumer}-studio`};if(id.endsWith('.author'))payload=consumer==='labs'?{...payload,title:'Local lab draft',tasks:[{id:'task-1',title:'Observe state',validation:'manual-check',expectedSignal:'state observed'}]}:{...payload,title:'Local scenario draft',phases:[{id:'phase-1',name:'Phase 1',elements:[]}]};try{const result=registry.execute(id,payload);Promise.resolve(result).then(value=>{workspace.status(value?.ok===false?`${id} · ${value.code||'blocked'}`:`${id} complete`,value?.ok===false?'error':'info');refresh()}).catch(error=>workspace.status(String(error?.message||error),'error'))}catch(error){workspace.status(String(error?.message||error),'error')}}));
  workspace.toolbar(commandIds);refresh();if(api?.state?.surface&&wave3Assembly?.bottomOwner?.providerDescriptors?.().length){api.state.surface.bottomOpen=false;wave3Assembly.renderBottom?.()}
  return {surface:consumer,domain,composition,structuredOwner:structured?.owner,spatialOwner:'SpatialInteractionKernel',contextOwner:'ContextInspectorHost',bottomOwner:wave3Assembly?.bottomOwner?.owner||null,realStudio:true};
}
function mountResultsStudio({domain,composition,stage,registry,workspace,wave3Assembly}){
  ensureM0Style();const rows=domain.records||[],commands=['results.replay','results.step','results.compare','results.annotate','results.handoff','results.verifyDeterminism'];
  const ref=row=>row?{resultId:row.resultId,revisionId:row.revisionId,manifestDigest:row.manifestDigest}:null,payloadFor=(row,index)=>({route:'results-studio',ref:ref(row),delta:1,left:ref(rows[index]||row),right:ref(rows[(index+1)%Math.max(1,rows.length)]||row)});
  renderTypedCollectionStage(stage,{workspace,surface:'results',title:'Results · Replay / Compare / AAR',summary:'Recorded Result revisions remain sealed facts. Replay, AAR and exact comparison are historical analysis only and never execute the live runtime.',rows,commands,registry,payloadFor,rowId:row=>row.resultId,rowLabel:row=>row.label||row.resultId,rowMeta:row=>`${row.revisionId} · ${row.status||'SEALED'}`,detailFor:row=>({resultId:row.resultId,revisionId:row.revisionId,manifestDigest:row.manifestDigest,status:row.status||'SEALED',sealed:row.sealed===true,eventCount:row.recordedEvents?.length||0,runId:row.runId||row.sourceRunInputRef?.runId||'—'}),truth:['Replay executes runtime: false','Sealed Result facts are immutable; AAR annotations are separate analysis revisions.','Determinism remains unavailable unless an admitted verifier is bound.']});
  const grid=stage.querySelector('.m0-studio-grid'),workbench=stage.querySelector('.m0-workbench');if(workbench){const spatial=document.createElement('section');spatial.className='m0-results-spatial';spatial.innerHTML='<h2>Historical spatial relation</h2><div data-m0-results-spatial></div>';workbench.append(spatial);mountEmbeddedSpatial(spatial,rows.length?rows.map(r=>r.resultId):['Recorded result','Comparison','AAR']);const compare=document.createElement('section');compare.className='m0-results-compare';compare.innerHTML='<h2>Analytical Compare</h2>';workbench.append(compare);const compareHost=new AnalyticalCompareHost(domain.compareOwner);if(rows.length>=2){const left=ref(rows[0]),right=ref(rows[1]),providerId=domain.provider.descriptor().providerId,pair=domain.compareOwner.createPair({left:{providerId,ref:left},right:{providerId,ref:right}}),sessionId='m0-results-primary';domain.compareOwner.openSession(sessionId,pair);compareHost.mount(compare,sessionId)}else compare.insertAdjacentHTML('beforeend','<p class="state-token" data-state="unavailable">No two sealed exact Result revisions are available. Compare remains visibly unavailable; no synthetic Result is fabricated.</p>')}
  const leftPane=document.querySelector('#leftPane .pbody');if(leftPane)leftPane.innerHTML=`<section class="m0-domain-nav"><h2>Recorded Results</h2><p>Exact revision identity is preserved. Select a Result then use the shared toolbar/action surfaces.</p><div class="m0-command-stack">${commands.map(id=>commandButton(registry,id,payloadFor(rows[0]||null,0))).join('')}</div></section>`;
  workspace.toolbar(commands);registerM0Context(wave3Assembly,{consumer:'results',domain,summary:'Recorded Results and AnalyticalCompare are read-only with respect to live runtime truth.',snapshot:()=>({status:rows.length?'AVAILABLE':'EMPTY',version:rows.length,revisionId:rows[0]?.revisionId||'none',persistence:{replayExecutesRuntime:false,determinismProvider:!!domain.determinismVerifier}})});return {domain,composition,compareHostOwner:'AnalyticalCompareHost',spatialOwner:'SpatialInteractionKernel',contextOwner:'ContextInspectorHost',realStudio:true};
}
function registerW04SurfaceCommands({registry,consumer,surface,analyticalCompareOwner}){
  const domain=surface.domain,reg=(id,label,run,available=()=>true)=>{if(registry.commands.has(id)){const current=registry.commands.get(id);if(current.owner!==domain.owner)throw Error(`R6_W04_COMMAND_OWNER_COLLISION:${id}`);return}registry.register(id,domain.owner,label,run,available)};
  if(consumer==='evidence'){
    reg('evidence.inspect','Inspect Evidence',p=>domain.inspect(p.id),p=>p?.id?true:'Select Evidence');
    reg('evidence.import','Import Candidate Evidence',p=>domain.importEvidence(p.input||p),p=>{const input=p?.input;return input?.id&&input?.revisionId&&input?.sourceId&&input?.sourceRevision&&input?.subject&&input?.evidenceClaim&&(input?.criterionRefs?.length||input?.governedPurpose)?true:'Explicit Candidate identity, subject, claim and governed purpose are required';});
    reg('evidence.amend','Prepare Evidence amendment',p=>domain.amend(p.id,{expectedBaseRevisionId:domain.inspect(p.id)?.lineage?.currentRevisionId,notes:'Amendment prepared from governed Evidence workbench'}),p=>{if(!p?.id)return 'Select admitted Evidence';const row=domain.inspect(p.id);return row.status==='ADMITTED'&&row.lineage?.currentRevisionId&&row.sourceBytesAvailable===true?true:'Only current admitted Evidence with available exact source bytes can be amended';});
    reg('evidence.admit','Admit submitted Candidate',p=>domain.admit(p.id,{authority:domain.get(p.id).admissionAuthority}),p=>{if(!p?.id)return 'Select Candidate Evidence';const row=domain.get(p.id);return row.status==='CANDIDATE'&&row.candidateState==='SUBMITTED_FOR_INTAKE'&&row.verification?.status==='VERIFIED'&&row.sourceBytesAvailable===true&&row.schemaValid===true&&row.intakeValidation?.status==='VALIDATED'&&row.admissionAuthority?.available===true&&row.admissionAuthority?.proofRef?true:'Candidate requires provider verification, validated intake and explicit admission authority';});
    reg('evidence.sourceChoice','Retain superseded source',p=>domain.sourceChoice(p.id,'retain',{reason:'Owner retained historical source from governed Evidence workbench'}),p=>{if(!p?.id)return 'Select Evidence';return domain.get(p.id).sourceStatus==='SUPERSEDED'?true:'Source choice is available only for superseded Evidence';});
  }
  if(consumer==='reviews'){
    reg('reviews.review','Continue Review',p=>domain.review(p.id,{action:'continue'}),p=>{if(!p?.id)return 'Select Review';const row=domain.get(p.id);return row.reviewer?.identity&&row.reviewer?.authorityAvailable===true&&row.reviewer?.permissionProofRef&&['IN_REVIEW','READY_FOR_DECISION'].includes(row.state)?true:'Continue requires an authorized active Review';});
    reg('reviews.finding','Add scoped finding',p=>domain.finding(p.id,{findingId:p.finding?.findingId,text:p.finding?.text,state:p.finding?.state,criterionRef:p.finding?.criterionRef,scopeDisposition:p.finding?.scopeDisposition||'IN_SCOPE',outOfScopeReason:p.finding?.outOfScopeReason||null}),p=>{if(!(p?.id&&p?.finding?.findingId&&String(p?.finding?.text||'').trim()&&REVIEW_FINDING_OUTCOMES.includes(p?.finding?.state)&&p?.finding?.criterionRef))return 'Explicit governed finding ID, text, outcome and pinned criterion are required';const row=domain.get(p.id);return row.state==='IN_REVIEW'&&row.reviewer?.identity&&row.reviewer?.authorityAvailable===true&&row.reviewer?.permissionProofRef&&row.criteriaRefs.includes(p.finding.criterionRef)?true:'Finding requires an authorized IN_REVIEW record and a criterion pinned to that Review';});
    reg('reviews.compare','Compare exact Review revisions',p=>domain.compare(p.id,{compareOwner:analyticalCompareOwner,provider:surface.compareProvider,left:p.left,right:p.right,sessionId:p.sessionId}),p=>p?.id&&p?.left&&p?.right?true:'Select two exact Review revisions');
    reg('reviews.supersede','Issue superseding Decision',p=>domain.supersede(p.id,{expectedDecisionId:p.decision?.expectedDecisionId??domain.get(p.id).effectiveDecisionId??domain.get(p.id).priorDecisionRef??null,newDecision:{decisionId:p.decision?.decisionId,outcome:p.decision?.outcome,correctionReason:p.decision?.correctionReason,affectedScope:p.decision?.affectedScope},correctionReason:p.decision?.correctionReason}),p=>{if(!(p?.id&&p?.decision?.decisionId&&REVIEW_DECISION_OUTCOMES.includes(p?.decision?.outcome)&&String(p?.decision?.correctionReason||'').trim()))return 'Explicit Decision ID, allowed outcome and correction/basis reason are required';const row=domain.get(p.id);return row.state==='READY_FOR_DECISION'&&row.findings.length>0&&row.reviewer?.identity&&row.reviewer?.authorityAvailable===true&&row.reviewer?.permissionProofRef?true:'Decision requires an authorized READY_FOR_DECISION Review with findings';});
  }
  if(consumer==='mastery'){
    reg('mastery.inspect','Inspect Mastery',p=>domain.inspect(p.id),p=>p?.id?true:'Select Mastery');
    reg('mastery.explain','Explain causal basis',p=>domain.explain(p.id),p=>p?.id?true:'Select Mastery');
    reg('mastery.reevaluate','Request governed re-evaluation',p=>domain.reevaluate(p.id,{}),p=>{if(!p?.id)return 'Select Mastery';return domain.evaluatorDescriptor?true:'Authorized Mastery evaluator/provider is unavailable';});
  }
  if(consumer==='portfolio'){
    reg('portfolio.filter','Filter Portfolio',p=>domain.filter(p.query||''));
    reg('portfolio.export','Export exact references',()=>domain.export());
    reg('portfolio.curate','Remove Portfolio reference',p=>{const row=domain.get(p.id);return domain.curate({action:'remove',id:p.id,expectedRevisionId:row.revisionId})},p=>p?.id?true:'Select Portfolio member');
    reg('portfolio.group','Update governed grouping',p=>{const row=domain.get(p.id);return domain.group(p.id,p.groupingRef??null,{expectedRevisionId:row.revisionId})},p=>p?.id?true:'Select Portfolio member');
  }
}
function mountW04Group({consumer,registry,workspace,analyticalCompareOwner}){
  const group=createW04RescueComposition({analyticalCompareOwner}),surface=group[consumer],domain=surface.domain,stage=ensureStage({consumer});
  registerW04SurfaceCommands({registry,consumer,surface,analyticalCompareOwner});
  const collection=surface.collectionCore||surface.collection,rows=collection.snapshot().visibleRows,commands=consumer==='evidence'?surface.commands:surface.toolbarCommandIds||surface.commands||[...registry.commands.keys()].filter(id=>id.startsWith(`${consumer}.`));
  const payloadFor=(row,index,list)=>{const id=row?collection.adapter.rowId(row):null,p={id,route:`r6-${consumer}`};if(consumer==='reviews'&&row){const other=list[(index+1)%Math.max(1,list.length)]||row;p.left={id:row.id,revisionId:row.revisionId};p.right={id:other.id,revisionId:other.revisionId};p.sessionId=`r6-reviews:${row.id}:${other.id}`}return p};
  const detailFor=row=>consumer==='evidence'?surface.center(row.id):consumer==='reviews'?surface.center(row.id):consumer==='mastery'?domain.explain(row.id):domain.get(row.id);
  const bottomFor=row=>surface.bottom?surface.bottom(row.id):surface.bottomProjection?.(row.id)||null;
  setBanner(consumer,`${titleCase(consumer)} · Workspace`,'Evidence, review and evaluation states remain distinct');
  const mounted=renderTypedCollectionStage(stage,{workspace,surface, title:`${titleCase(consumer)} workbench`,summary:consumer==='evidence'?'Candidate Evidence → admitted immutable Evidence. Import never implies Admission, Review, Decision or Mastery.':consumer==='reviews'?'Formal Evidence Review with pinned Evidence/criteria, immutable Decision lineage and central exact comparison.':consumer==='mastery'?'Mastery is a governed evaluation projection over Evidence + Decision + policy basis; completion alone never creates Mastery.':'Portfolio is reference-only curation over canonical sources; it never copies or deletes canonical Evidence/Mastery truth.',collection,commands,registry,payloadFor,detailFor,bottomFor,collectionMode:'list',emptyLabel:`${titleCase(consumer)} workbench`,emptyMessage:consumer==='evidence'?'No current Candidate or admitted Evidence is bound.':consumer==='reviews'?'No formal Evidence Review is bound.':consumer==='mastery'?'NOT_EVALUATED · No authorized Mastery provider/evaluator is bound.': 'No canonical Portfolio memberships are bound.',emptyGuidance:consumer==='evidence'?['Declare a Candidate without inventing verification facts.','Bind an admitted verifier/provider before validation or Admission.']:consumer==='reviews'?['Formal Review starts only from admitted immutable Evidence and pinned criteria.','Findings and Decisions require explicit governed input and reviewer authority.']:consumer==='mastery'?['Current state is NOT_EVALUATED while evaluator/provider truth is unavailable.','Completion or activity never creates Mastery.']:['Portfolio starts empty when no canonical source/provider is bound.','Curation references canonical Evidence/Mastery/project records; it does not invent achievements.'],truth:diagnosticsEnabled()?[`Domain owner: ${domain.owner}`,`Analytical compare owner: ${analyticalCompareOwner.owner}`,'Persistence/provider truth is not fabricated by presentation.']:[consumer==='evidence'?'Candidate import and admission are separate actions.':consumer==='reviews'?'Review findings and review decisions remain separate.':consumer==='mastery'?'Progress and completion do not imply Mastery.':'Portfolio items reference canonical records; removing a view item does not delete its source.']});
  if(consumer==='evidence'){
    const box=document.createElement('details');box.className='m0-domain-nav';box.innerHTML=`<summary>Import candidate evidence</summary><p>Add a bounded local Candidate declaration. Source bytes, digest, schema validity, producer identity and admission authority remain <b>UNVERIFIED / UNAVAILABLE</b> until supplied by an admitted verifier/provider.</p><div class="m0-field-grid"><label>Candidate ID<input data-evidence-id dir="ltr" value="candidate-local-001"></label><label>Revision<input data-evidence-revision dir="ltr" value="candidate-r1"></label><label>Source ID<input data-evidence-source dir="ltr" value="local-source"></label><label>Source revision<input data-evidence-source-revision dir="ltr" value="r1"></label><label style="grid-column:1/-1">Title<input data-evidence-title value="Imported candidate evidence"></label><label>Subject<input data-evidence-subject dir="ltr" placeholder="subject identifier"></label><label>Governed purpose<input data-evidence-purpose placeholder="Why this candidate exists"></label><label style="grid-column:1/-1">Claim<textarea data-evidence-claim rows="3">Imported candidate evidence</textarea></label></div>${diagnosticsEnabled()?`<details class="m0-diagnostics" data-product-diagnostics><summary>Diagnostic envelope preview</summary><pre dir="ltr" data-evidence-envelope-preview></pre></details>`:''}<button type="button" class="btn" data-evidence-import-submit>Import as candidate</button><output data-evidence-import-result aria-live="polite"></output>`;
    const buildInput=()=>({id:box.querySelector('[data-evidence-id]').value.trim(),revisionId:box.querySelector('[data-evidence-revision]').value.trim(),title:box.querySelector('[data-evidence-title]').value.trim(),sourceId:box.querySelector('[data-evidence-source]').value.trim(),sourceRevision:box.querySelector('[data-evidence-source-revision]').value.trim(),subject:box.querySelector('[data-evidence-subject]').value.trim(),evidenceClaim:box.querySelector('[data-evidence-claim]').value.trim(),criterionRefs:[],governedPurpose:box.querySelector('[data-evidence-purpose]').value.trim(),verification:{status:'UNVERIFIED'}});
    stage.querySelector('[data-r6-workbench]')?.append(box);const preview=box.querySelector('[data-evidence-envelope-preview]');if(preview)preview.textContent=JSON.stringify(buildInput(),null,2);box.addEventListener('input',()=>{if(preview)preview.textContent=JSON.stringify(buildInput(),null,2)});box.querySelector('[data-evidence-import-submit]')?.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();const out=box.querySelector('[data-evidence-import-result]');try{const result=registry.execute('evidence.import',{input:buildInput(),route:'r6-evidence-import-form'});out.textContent=result?.ok?'Candidate imported; admission remains separate.':`Import blocked: ${result?.code||'INVALID'}`;mounted.render()}catch(error){out.textContent=`Import error: ${String(error?.message||error)}`}})
  }
  if(consumer==='reviews'){
    const box=document.createElement('details');box.className='m0-domain-nav';box.innerHTML=`<summary>Governed Review input</summary><p>Formal findings and Decisions require explicit reviewer-authored content. The toolbar never manufactures finding text, outcome, or supersession basis.</p><div class="m0-field-grid"><label>Finding ID<input data-review-finding-id dir="ltr"></label><label>Finding outcome<select data-review-finding-state><option value="" selected disabled>Select finding outcome</option>${REVIEW_FINDING_OUTCOMES.map(value=>`<option value="${value}">${value}</option>`).join('')}</select></label><label>Criterion ref<input data-review-criterion dir="ltr"></label><label style="grid-column:1/-1">Finding text<textarea data-review-finding-text rows="3"></textarea></label><label>Decision ID<input data-review-decision-id dir="ltr"></label><label>Decision outcome<select data-review-decision-outcome><option value="" selected disabled>Select Decision outcome</option>${REVIEW_DECISION_OUTCOMES.map(value=>`<option value="${value}">${value}</option>`).join('')}</select></label><label style="grid-column:1/-1">Decision / supersession basis<textarea data-review-decision-reason rows="3"></textarea></label></div><div class="m0-command-strip"><button type="button" class="btn" data-review-submit-finding>Add finding</button><button type="button" class="btn" data-review-submit-decision>Issue Decision</button></div><output data-review-input-result aria-live="polite"></output>`;
    stage.querySelector('[data-r6-workbench]')?.append(box);
    const selected=()=>mounted.selected(),result=box.querySelector('[data-review-input-result]');
    box.querySelector('[data-review-submit-finding]')?.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();const row=selected();if(!row){result.textContent='Select a Review first.';return}const payload={id:row.id,finding:{findingId:box.querySelector('[data-review-finding-id]').value.trim(),text:box.querySelector('[data-review-finding-text]').value.trim(),state:box.querySelector('[data-review-finding-state]').value,criterionRef:box.querySelector('[data-review-criterion]').value.trim(),scopeDisposition:'IN_SCOPE'}};try{const value=registry.execute('reviews.finding',payload);result.textContent=value?.ok?'Finding recorded; no Decision was manufactured.':`Finding blocked: ${value?.code||'INVALID'}`}catch(error){result.textContent=`Finding error: ${String(error?.message||error)}`}});
    box.querySelector('[data-review-submit-decision]')?.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();const row=selected();if(!row){result.textContent='Select a Review first.';return}const payload={id:row.id,decision:{decisionId:box.querySelector('[data-review-decision-id]').value.trim(),outcome:box.querySelector('[data-review-decision-outcome]').value,correctionReason:box.querySelector('[data-review-decision-reason]').value.trim(),expectedDecisionId:row.effectiveDecisionId||row.priorDecisionRef||null}};try{const value=registry.execute('reviews.supersede',payload);result.textContent=value?.ok?'Decision recorded with immutable lineage.':`Decision blocked: ${value?.code||'INVALID'}`}catch(error){result.textContent=`Decision error: ${String(error?.message||error)}`}});
  }
  return {group,surface,domain,mounted,centralAnalyticalCompareOwner:analyticalCompareOwner.owner};
}
function mountW05Collection({consumer,composition,registry,workspace}){
  bridgeSemanticCommandBus(registry,composition.commands);const stage=ensureStage({consumer}),collection=composition.collection,commands=composition.toolbarCommandIds||[];
  const payloadFor=(row,index,list)=>{const id=row?(row.id||row.key||row.proposalId||row.candidateId):null,p={id,key:row?.key,route:`r6-${consumer}`};if(consumer==='releases'&&list.length>=2){p.leftId=(row||list[0]).candidateId;p.rightId=(list[(index+1)%list.length]||list[1]).candidateId}return p};
  const detailFor=row=>composition.adapter?.inspect?.(row.id||row.key||row.candidateId)||row,bottomFor=row=>composition.bottomProjection?.(row.id||row.key||row.candidateId)||null;
  setBanner(consumer,`${titleCase(consumer)} · Workspace`,'Operational state and actions');
  const mounted=renderTypedCollectionStage(stage,{workspace,surface:consumer,title:`${titleCase(consumer)} workbench`,summary:consumer==='manual_ai'?'Manual provider-neutral AI bridge: prepare/export/import/review only; no automatic provider call or canonical publication.':consumer==='releases'?'Technical readiness, Owner authorization and deployment observation remain three distinct truths.':'Operational configuration is observed/proposed/validated separately from durable Global Settings.',collection,commands,registry,payloadFor,detailFor,bottomFor,collectionMode:'list',emptyGuidance:consumer==='manual_ai'?['Prepare a proposal from an explicit source revision.','Export and obtain provider output outside CEP.','Import and review the declared result before any draft acceptance.']:consumer==='releases'?['Bind an exact release candidate and candidate evidence.','Evaluate technical readiness independently from Owner authorization.','Record deployment observation separately; no deployment is executed here.']:['Observe the current operational value.','Prepare and validate a proposal without changing durable settings.','Request application only through the admitted authority boundary.'],truth:diagnosticsEnabled()?[`Domain owner: ${composition.adapter?.owner||'Domain adapter'}`,`Provider truth: ${scalar(composition.providerTruth||composition.truthCeiling||'Explicit')}`,'Unavailable/error states remain visible and never convert to success.']:['Unavailable, stale, error and success remain distinct states.']});
  workspace.toolbar([...commands,'foundation.settings'].slice(0,7));return {composition,mounted};
}

export async function mountM0ControllerComposition(context={}){
  const {consumer,registry,commandBus,workspace,structured,learn,relations,simulation,wave3Assembly,wave4Assembly,api,button,esc,shellNavigation,analyticalCompareOwner,timelineReplayOwner}=context;
  if(consumer==='library')return bindLibrarySurface({commands:registry,structured,workspace});
  if(consumer==='learn')return bindLearnSurface({commands:registry,learn,structured,workspace});
  if(consumer==='shell'){setBanner(consumer,'CEP · Workspace Home','Navigate across CEP workspaces');const stage=ensureStage({consumer});stage.innerHTML='<section class="m0-home"><h1>CEP workspace</h1><p>Choose a destination from the global shell. Navigation, history, context restoration and dirty-departure guards are owned centrally.</p></section>';if(!shellNavigation)return {surface:'shell',pendingNavigationBinding:true};const binding=bindShellSurfaceCommands({commands:registry,navigation:shellNavigation}),route=binding.routeContext,active=route.activeSurface||{},activeLabel=localizedRegionLabel(active),activeDescription=String(active.description?.ar||active.description?.en||'');workspace.region('LEFT',{html:`<section class="m0-domain-nav"><h2>Global destinations</h2>${compactRegionList(route.globalDestinations)}<h3>Current area surfaces</h3>${compactRegionList(route.areaSurfaces)}</section>`,label:'CEP destinations'});workspace.region('RIGHT',{html:`<section class="m0-domain-nav"><h2 dir="auto">${html(activeLabel)}</h2>${activeDescription?`<p dir="auto">${html(activeDescription)}</p>`:''}<dl class="m0-semantic-list"><div><dt>Surface</dt><dd><bdi dir="ltr">${html(active.id||route.surface||'shell')}</bdi></dd></div><div><dt>Area</dt><dd><bdi dir="ltr">${html(route.activeArea||'')}</bdi></dd></div></dl></section>`,label:'Route context'});workspace.region('BOTTOM',{html:semanticProjection(route.history),label:'Navigation history',summary:'Route/history state only; no domain state is inferred.'});workspace.toolbar(binding.commands,{contextProvider:()=>({surface:route.surface,activeArea:route.activeArea})});return binding;}
  if(consumer==='today'){const adapter=new TodayProjectionDomainAdapter({providers:Array.isArray(context.todayProviders)?context.todayProviders:[],continuationResolver:context.todayContinuationResolver||null});const stage=ensureStage({consumer});setBanner(consumer,'Today · Projection','Projection only · no canonical progress or Mastery writes');const composed=composeTodayOrchestrationPresentation({host:stage,commands:registry,adapter,workspace}),projection=adapter.lastProjection||adapter.project(),selected=projection.items?.[0]||null;workspace.region('LEFT',{html:`<section class="m0-domain-nav"><h2>Today projection</h2><p>Filter · <bdi dir="ltr">${html(projection.filter||'ALL')}</bdi></p>${compactRegionList(projection.items||[])}</section>`,label:'Today projection'});workspace.region('RIGHT',{html:semanticProjection(selected||{state:'UNAVAILABLE'}),label:'Selected Today context'});workspace.region('BOTTOM',{html:semanticProjection({state:projection.state,viewState:projection.viewState,sourceTotalCount:projection.sourceTotalCount,visibleCount:projection.visibleCount,retainedFromLastSuccess:projection.retainedFromLastSuccess,sources:projection.sources?.map(source=>({providerId:source.providerId,state:source.state,observedAt:source.observedAt,errorRef:source.errorRef||null}))}),label:'Projection status',summary:'Observed projection truth only; no progress or Mastery write is inferred.'});workspace.toolbar([...composed.binding.commands],{contextProvider:()=>({itemId:selected?.id||null,route:'today-orchestration'})});return {adapter,binding:composed.binding,composed};}
  if(consumer==='rq'){
    if(!analyticalCompareOwner)throw Error('R6_CENTRAL_ANALYTICAL_COMPARE_REQUIRED');
    const adapter=new RQDomainAdapter([],{analyticalCompareOwner,providerId:'rq.current-unavailable',providerAdmitted:false,providerClassification:'UNAVAILABLE_NO_ADMITTED_CURRENT_PROVIDER'}),binding=bindRqSurface({commands:registry,adapter,workspace}),stage=ensureStage({consumer});
    setBanner(consumer,'RQ · Research Analysis','Current provider unavailable · exact SourceRevision analysis only');
    const mounted=renderTypedCollectionStage(stage,{workspace,surface:'rq',title:'RQ research workbench',summary:'Search and compare are available only against an admitted current provider with exact SourceRevision identities. No non-production acceptance corpus is promoted into Product truth.',rows:()=>adapter.records,commands:binding.commands,registry,rowId:(row,index)=>row.sourceId||`rq-${index+1}`,rowLabel:(row,index)=>row.title||row.sourceId||`Source ${index+1}`,rowMeta:row=>row.revision||row.status||'',detailFor:row=>row,truth:diagnosticsEnabled()?[`Analytical compare owner: ${analyticalCompareOwner.owner}`,'Current RQ provider: UNAVAILABLE_NO_ADMITTED_CURRENT_PROVIDER','Analysis-session persistence: unavailable','Formal review authority: false']:['No current Product SourceRevision provider is admitted.','Comparisons require exact provider-bound source revisions.','This workspace does not issue formal Evidence Review decisions or Mastery.'],emptyMessage:'No admitted current RQ SourceRevision provider is bound. Non-production acceptance data is excluded from normal Product truth; Compare remains unavailable until exact provider-bound revisions exist.'});
    workspace.toolbar([...binding.commands]);return {adapter,binding,mounted,centralAnalyticalCompareOwner:analyticalCompareOwner.owner};
  }
  if(consumer==='visualize'){
    const adapter=new VisualizeDomainAdapter({provider:createBalanced6VisualizeProvider(),representations:BALANCED6_VISUALIZE_REPRESENTATIONS}),binding=bindVisualizeSurface({commands:registry,adapter,workspace}),truth=adapter.providerTruth(),stage=ensureStage({consumer});
    setBanner(consumer,'Visualize · Spatial Representations',`${truth.authority} · canonical:false · READ_ONLY`);
    const heading=stage?.querySelector('.domain-heading strong');if(heading)heading.textContent='Spatial representation workspace';
    if(stage){stage.dataset.visualizeProviderAuthority=truth.authority;stage.dataset.visualizeCanonical=String(truth.canonical);stage.dataset.visualizeEditability=truth.editability;}
    const descriptor=()=>({id:`visualize:${truth.providerId}:${truth.projectionStatus}`,providerId:'spatial-context',family:'spatial',subject:'Visualize spatial representation',eyebrow:'Representation context',summary:'Local acceptance projection only. canonical:false. Representation geometry is not canonical object/relation truth.',domainOwner:adapter.owner,revisionToken:`provider:${truth.providerId}|canonical:false|editability:${truth.editability}`,lenses:[{id:'truth',label:'Provider truth',tabs:[{id:'current',label:'Current',fields:[{id:'provider-id',label:'Provider',value:truth.providerId,technical:true},{id:'authority',label:'Authority',value:truth.authority,technical:true},{id:'canonical',label:'Canonical',value:'false',technical:true},{id:'editability',label:'Editability',value:truth.editability,technical:true},{id:'relation-mutation',label:'Relation mutation',value:truth.relationMutation,technical:true},{id:'object-edit',label:'Object edit',value:truth.objectEdit,technical:true}]}]},{id:'views',label:'Views',tabs:[{id:'adapters',label:'Adapters',fields:[{id:'engine-owner',label:'Shared Spatial engine',value:adapter.model.interactionKernel.ownerId,technical:true},{id:'view-adapters',label:'View adapters',value:adapter.viewDescriptors().map(item=>item.mode).join(' / '),technical:true},{id:'identity-boundary',label:'Identity boundary',value:'representationId != canonicalObjectId',technical:true}]}]}]});
    if(wave3Assembly?.contextInspector){if(wave3Assembly.contextInspector.providerIds().includes('spatial-context'))wave3Assembly.contextInspector.unregisterProvider('spatial-context');wave3Assembly.contextInspector.registerProvider(defineContextDescriptorProvider({id:'spatial-context',family:'spatial',owner:adapter.owner,isApplicable:()=>true,describe:descriptor}));wave3Assembly.refreshContext();}
    workspace.region('RIGHT',{html:`<section class="m0-domain-nav"><h2>Visualize provider truth</h2><p>Local acceptance representation only. Canonical mutation authority is not bound.</p>${semanticProjection({providerId:truth.providerId,authority:truth.authority,canonical:false,editability:truth.editability,relationMutation:truth.relationMutation,objectEdit:truth.objectEdit,sharedSpatialEngine:adapter.model.interactionKernel.ownerId,viewAdapters:adapter.viewDescriptors().map(item=>item.mode).join(' / '),identityBoundary:'representationId != canonicalObjectId'})}</section>`,label:'Visualize · Context'});
    return {adapter,binding,centralSpatialOwner:relations?.owner||'SpatialInteractionKernel',providerTruth:truth};
  }
  if(consumer==='enterprise'&&relations){const domain=new W03EnterpriseDomain({relationAdapter:relations}),composition=composeEnterpriseSurface({relationAdapter:relations,domain,bus:commandBus});workspace.toolbar(['enterprise.inspect','enterprise.edit','enterprise.revise','enterprise.twin','enterprise.handoff']);return {domain,composition,realStudio:true};}
  if(consumer==='labs'||consumer==='scenarios'){const relation=seedRelations(consumer,consumer==='labs'?['Task','Dependency','Validation']:['Phase','Module','Decision']),domain=consumer==='labs'?new W03LabDomain():new W03ScenarioDomain(),composition=consumer==='labs'?composeLabsSurface({domain,bus:commandBus,shared:{structuredHost:structured,spatialRelation:relation}}):composeScenariosSurface({domain,bus:commandBus,shared:{structuredHost:structured,spatialRelation:relation}});return mountStructuredStudio({consumer,domain,composition,workspace,registry,structured,wave3Assembly,api});}
  if(consumer==='results'){if(!analyticalCompareOwner||!timelineReplayOwner)throw Error('R6_RESULTS_SHARED_OWNERS_REQUIRED');const relation=seedRelations('results',['Recorded result','Comparison','AAR']),domain=new W03ResultsDomain({timelineReplayOwner,analyticalCompareOwner}),composition=composeResultsSurface({domain,bus:commandBus,shared:{spatialRelation:relation,timelineReplayOwner,analyticalCompareOwner}}),stage=ensureStage({consumer});setBanner(consumer,'Results · Replay / Compare / AAR','Recorded results · historical replay and analysis');return mountResultsStudio({domain,composition,stage,registry,workspace,wave3Assembly});}
  if(consumer==='runs'){workspace.toolbar(['OPEN_TERMINAL','runs.pause','runs.resume','runtime.disconnect','runtime.reconnect','view.recorded']);return {surface:'runs',runtimeTruth:simulation?.descriptor?.()?.runtimeTruth||'INTERNAL_SIMULATION',operationalSessionOwner:wave4Assembly?.operationalSession?.owner||null,terminalRenderer:'XtermOperationalTerminalRenderer',realStudio:true};}
  if(['evidence','mastery','portfolio','reviews'].includes(consumer)){if(!analyticalCompareOwner)throw Error('R6_CENTRAL_ANALYTICAL_COMPARE_REQUIRED');return mountW04Group({consumer,registry,workspace,analyticalCompareOwner});}
  if(['configuration','manual_ai','releases','backup','health','processing','audit','validation'].includes(consumer)){const group=createW05RescueComposition({analyticalCompareOwner});const selected=group.surfaces[consumer];if(['configuration','manual_ai','releases'].includes(consumer))return {group,...mountW05Collection({consumer,composition:selected,registry,workspace})};if(['backup','health','processing'].includes(consumer)){const stage=ensureStage({consumer});setBanner(consumer,`${titleCase(consumer)} · Runtime Capability`,'Local capability status and actions');const mounted=selected.mount({stage,registry,workspace,button,esc});const ids=[...registry.commands.keys()].filter(id=>id.startsWith(`${consumer}.`));workspace.toolbar(ids,{contextProvider:()=>consumer==='health'?{sourceId:selected.selected?.()?.sourceId||null}:consumer==='processing'?{jobId:selected.selected?.()?.jobId||null}:consumer==='backup'?{packageId:selected.snapshot?.().selectedPackageId||null}:{}});return {group,adapter:selected,mounted,providerBindings:group.providerBindings,truthCeilings:group.truthCeilings};}if(consumer==='audit'){const stage=ensureStage({consumer});setBanner(consumer,'Audit · Durable Event Trace','Application event history and provenance');return {group,...mountAuditSurface({stage,registry,workspace,runtimeAdapter:selected})};}if(consumer==='validation'){const stage=ensureStage({consumer});setBanner(consumer,'Validation · Local Bounded Rules','Technical findings remain distinct from formal review');return {group,...mountValidationSurface({stage,registry,workspace,adapter:selected})};}}
  return {surface:consumer,composition:'NO_ADDITIONAL_CONTROLLER_COMPOSITION_REQUIRED'};
}
