import {SemanticCommandBus} from '../../../foundation/global/commands.js';
import {ManualAiDomainAdapter} from '../../../adapters/manual_ai/domain-adapter.js';
import {createManualAiSurfaceComposition} from '../../../surfaces/manual_ai/composition.js';
import {describeContextProvider} from '../../../foundation/global/context-descriptor-contract.js';
const assert=(v:any,m='assertion failed')=>{if(!v)throw Error(m)};const run=(name:string,fn:()=>void,out:any[])=>{try{fn();out.push({name,status:'PASS'})}catch(e){out.push({name,status:'FAIL',error:String((e as any)?.message||e)})}};const digest='a'.repeat(64);
export function runManualAiSurfaceTests(){const t:any[]=[];
 run('manual-ai.provider-mode-is-manual-only',()=>{const a=new ManualAiDomainAdapter();assert(a.providerMode==='MANUAL_ONLY_PROVIDER_NEUTRAL')},t);
 run('manual-ai.prepare-has-no-provider-call',()=>{const a=new ManualAiDomainAdapter();const p=a.prepare({proposalId:'p1',revision:'r1',sourceDigest:digest,sourceId:'KU-1'});assert(p.state==='PREPARED'&&a.diagnosticProjection().hiddenProviderCalls===0)},t);
 run('manual-ai.export-helper-unavailable-returns-packet-not-provider-call',()=>{const a=new ManualAiDomainAdapter();a.prepare({proposalId:'p1',revision:'r1',sourceDigest:digest,sourceId:'KU-1'});const r=a.export('p1');assert(!r.ok&&r.code==='EXPORT_HELPER_UNAVAILABLE'&&r.packet.mode==='MANUAL_ONLY')},t);
 run('manual-ai.manual-import-preserves-provenance',()=>{const a=new ManualAiDomainAdapter();const r=a.import({proposalId:'p2',revision:'r2',sourceDigest:digest,sourceId:'external-manual-result',content:'نتيجة manual AI'});assert(r.ok&&r.proposal.provenance.obtainedBy==='MANUAL_IMPORT')},t);
 run('manual-ai.invalid-provenance-is-quarantined',()=>{const a=new ManualAiDomainAdapter();const r=a.import({proposalId:'bad',revision:'r1',sourceDigest:'no',content:'x'});assert(!r.ok&&r.code==='PROVENANCE_INVALID'&&r.proposal.state==='PROVENANCE_INVALID')},t);
 run('manual-ai.accept-invalid-fails-closed',()=>{const a=new ManualAiDomainAdapter();a.import({proposalId:'bad',revision:'r1',sourceDigest:'no',content:'x'});const r=a.review({id:'bad',disposition:'ACCEPT'});assert(!r.ok&&r.code==='PROVENANCE_INVALID')},t);
 run('manual-ai.accept-creates-working-draft-only',()=>{const a=new ManualAiDomainAdapter({draftSink:{createWorkingDraft:()=>({draftId:'draft-1',status:'CREATED'})}});a.import({proposalId:'p2',revision:'r2',sourceDigest:digest,sourceId:'manual',content:'x'});const r=a.review({id:'p2',disposition:'ACCEPT'});assert(r.ok&&r.code==='ACCEPTED_AS_DRAFT'&&r.canonicalPublication===false)},t);
 run('manual-ai.command-unavailable-emits-no-receipt',()=>{const c=createManualAiSurfaceComposition({commands:new SemanticCommandBus()});const before=c.commands.receipts.length;const r=c.commands.execute('manual_ai.export',{});assert(r.ok===false&&c.commands.receipts.length===before)},t);
 run('manual-ai.collection-is-shared-core-bound-domain-data',()=>{const a=new ManualAiDomainAdapter();a.prepare({proposalId:'p1',revision:'r1',sourceDigest:digest,sourceId:'KU-1'});const c=createManualAiSurfaceComposition({adapter:a,commands:new SemanticCommandBus()});assert(c.collection.snapshot().totalRows===1&&c.slots.LEFT==='collection')},t);
 run('manual-ai.context-provenance-descriptor-is-valid',()=>{const a=new ManualAiDomainAdapter();a.prepare({proposalId:'p1',revision:'r1',sourceDigest:digest,sourceId:'KU-1'});a.select('p1');const c=createManualAiSurfaceComposition({adapter:a,commands:new SemanticCommandBus()});const r=describeContextProvider(c.contextProvider,{id:'p1'});assert(r.ok&&r.descriptor.domainOwner==='ManualAiDomainAdapter')},t);
 run('manual-ai.product-declares-no-auto-publication',()=>{const c=createManualAiSurfaceComposition({commands:new SemanticCommandBus()});assert(c.providerTruth.hiddenProviderCalls===0&&c.providerTruth.automaticCanonicalPublication===false)},t);
 run('manual-ai.platform-truth-remains-unavailable-fallback',()=>{const c=createManualAiSurfaceComposition({commands:new SemanticCommandBus()});assert(c.platformTruth.activeKeyboardSource.includes('UNAVAILABLE')&&c.platformTruth.nativeWindow.includes('UNAVAILABLE'))},t);
 return t;}
if(import.meta.url===new URL(process.argv[1],'file:').href){const tests=runManualAiSurfaceTests();console.log(JSON.stringify({surface:'manual_ai',pass:tests.filter(x=>x.status==='PASS').length,fail:tests.filter(x=>x.status==='FAIL').length,tests},null,2));if(tests.some(x=>x.status==='FAIL'))process.exitCode=1;}
