#!/usr/bin/env python3
"""Build final v0.2.1 -> v0.2.1a bounded-correction assurance and changed-file registers."""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BASELINE = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else None
SUCCESSOR = "CEP-FOUNDATION-0.2.1a-REVIEW-HARDENED-CANDIDATE"
EXCLUDED_FROM_DIFF = {
    "DELIVERY_MANIFEST.json",
    "assurance/CANDIDATE_IDENTITY.json",
    "assurance/CHANGED_FILE_REGISTER.json",
}


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load(relative: str) -> dict:
    return json.loads((ROOT / relative).read_text(encoding="utf-8"))


def dump(relative: str, value: object) -> None:
    (ROOT / relative).write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def file_map(root: Path) -> dict[str, Path]:
    return {
        p.relative_to(root).as_posix(): p
        for p in root.rglob("*")
        if p.is_file() and p.relative_to(root).as_posix() not in EXCLUDED_FROM_DIFF and "node_modules" not in p.parts and "__pycache__" not in p.parts
    }


def test_ok(report: dict, test_id: str) -> bool:
    return any(x.get("id") == test_id and x.get("status") == "PASS" for x in report.get("tests", []))


if BASELINE is None or not BASELINE.is_dir():
    raise SystemExit("USAGE: python tools/build-correction-registers.py <extracted-exact-v0.2.1-baseline-directory>")

baseline_receipt = load("assurance/BASELINE_VERIFICATION_RECEIPT.json")
model = load("assurance/MODEL_TEST_RESULTS.json")
contract = load("assurance/CONTRACT_TEST_RESULTS.json")
duplicate = load("assurance/DUPLICATE_MECHANIC_SCAN.json")
scaffold = load("assurance/WRITER_SCAFFOLD_TEST_RESULTS.json")
browser = load("assurance/BROWSER_CONFORMANCE_RECEIPT.json")
w03 = load("assurance/W03_SEMANTIC_OWNER_VALIDATION.json")
authority = load("assurance/CURRENT_AUTHORITY_ISOLATION_RECEIPT.json")
deferred_guard = load("assurance/DEFERRED_BOUNDARY_GUARD.json")
deferred_preservation = load("assurance/DEFERRED_SET_PRESERVATION_RECEIPT.json")
portability = load("assurance/BROWSER_PORTABILITY_BOOTSTRAP_RECEIPT.json")
runtime = load("contracts/FOUNDATION_RUNTIME_REGISTRY.json")

required_model_ids = {
    "structured": ["structured.selection-clipboard", "structured.clipboard-readonly-schema", "structured.semantic-command-route", "structured.library-clipboard-consumer"],
    "structured-isolation": ["structured.independent"],
    "actions": ["actions.generic-policy", "actions.preflight-presentation-convergence", "actions.availability-matrix"],
    "relation": ["relation.canonical", "relation.canonical-constraints"],
    "runtime": ["runtime.contract", "runtime.w03-v34-causal"],
    "context": ["gesture.context-suppression"],
    "keyboard": ["spatial.keyboard-contract"],
}

def all_model(group: str) -> bool:
    return all(test_ok(model, x) for x in required_model_ids[group])

mandatory = [
    {"id": 1, "name": "baseline/candidate manifest validation", "status": "PASS" if baseline_receipt.get("status") == "PASS" else "FAIL", "proof": "assurance/BASELINE_VERIFICATION_RECEIPT.json + DELIVERY_MANIFEST.json generated by finalizer; packaged manifest is post-verified before handoff"},
    {"id": 2, "name": "npm test", "status": "PASS" if model.get("fail") == 0 and model.get("pass", 0) >= 57 else "FAIL", "proof": {"path": "assurance/MODEL_TEST_RESULTS.json", "pass": model.get("pass"), "fail": model.get("fail")}},
    {"id": 3, "name": "npm run check", "status": "PASS" if contract.get("fail") == 0 and contract.get("pass", 0) >= 149 else "FAIL", "proof": {"path": "assurance/CONTRACT_TEST_RESULTS.json", "pass": contract.get("pass"), "fail": contract.get("fail"), "compositeIncludes": ["duplicate guard", "Writer scaffold", "W03 semantic validator", "authority intake", "deferred-boundary guard", "contracts"]}},
    {"id": 4, "name": "Writer scaffold tests", "status": "PASS" if scaffold.get("fail") == 0 and scaffold.get("pass", 0) >= 38 else "FAIL", "proof": {"path": "assurance/WRITER_SCAFFOLD_TEST_RESULTS.json", "pass": scaffold.get("pass"), "fail": scaffold.get("fail")}},
    {"id": 5, "name": "browser critical suite", "status": "PASS" if browser.get("executionStatus") == "EXECUTED_PASS" and browser.get("summary") == {"total": 6, "pass": 6, "fail": 0} else "FAIL", "proof": {"path": "assurance/BROWSER_CONFORMANCE_RECEIPT.json", **browser.get("summary", {})}},
    {"id": 6, "name": "W03 forbidden-authority exact + semantic negative scan", "status": "PASS" if test_ok(contract, "w03.old_authority_zero_active") and test_ok(contract, "w03.semantic_authority_alias_zero") else "FAIL", "proof": ["w03.old_authority_zero_active", "w03.semantic_authority_alias_zero"]},
    {"id": 7, "name": "W03 69/318 traceability + semantic-owner validation", "status": "PASS" if w03.get("status") == "PASS" and w03.get("summary", {}).get("sections") == 69 and w03.get("summary", {}).get("atoms") == 318 else "FAIL", "proof": {"path": "assurance/W03_SEMANTIC_OWNER_VALIDATION.json", **w03.get("summary", {})}},
    {"id": 8, "name": "Structured selection/clipboard tests", "status": "PASS" if all_model("structured") else "FAIL", "proof": required_model_ids["structured"]},
    {"id": 9, "name": "non-Library Structured isolation", "status": "PASS" if all_model("structured-isolation") and test_ok(contract, "structured.non_library_isolation") else "FAIL", "proof": ["structured.independent", "structured.non_library_isolation"]},
    {"id": 10, "name": "ActionAvailability generic policy tests", "status": "PASS" if all_model("actions") else "FAIL", "proof": required_model_ids["actions"]},
    {"id": 11, "name": "relation central-reuse regression", "status": "PASS" if all_model("relation") and test_ok(contract, "relations.central_reuse") else "FAIL", "proof": [*required_model_ids["relation"], "relations.central_reuse", "browser central-change-reuse"]},
    {"id": 12, "name": "InternalSimulation causal-state regression", "status": "PASS" if test_ok(model, "runtime.w03-v34-causal") and any(x.get("id") == "runtime-causal-consequence" and x.get("status") == "PASS" for x in browser.get("flows", [])) else "FAIL", "proof": ["runtime.w03-v34-causal", "browser runtime-causal-consequence"]},
    {"id": 13, "name": "Operational provider-neutrality regression", "status": "PASS" if test_ok(model, "runtime.contract") and test_ok(contract, "operational.provider_neutral") else "FAIL", "proof": ["runtime.contract", "operational.provider_neutral"]},
    {"id": 14, "name": "Ctrl+RMB lifecycle regression", "status": "PASS" if all_model("context") and test_ok(contract, "spatial.context_lifecycle") else "FAIL", "proof": ["gesture.context-suppression", "spatial.context_lifecycle"]},
    {"id": 15, "name": "Spatial keyboard regression", "status": "PASS" if all_model("keyboard") and test_ok(contract, "spatial.keyboard_semantics") else "FAIL", "proof": ["spatial.keyboard-contract", "spatial.keyboard_semantics"]},
    {"id": 16, "name": "Writer deferred-relevance positive + negative tests", "status": "PASS" if all(test_ok(scaffold, x) for x in ["scaffold.deferred-negative.visualize-review", "scaffold.deferred-negative.library-runtime", "scaffold.deferred-positive.runs-operational"]) else "FAIL", "proof": ["scaffold.deferred-negative.visualize-review", "scaffold.deferred-negative.library-runtime", "scaffold.deferred-positive.runs-operational"]},
    {"id": 17, "name": "authority-intake contamination guard", "status": "PASS" if authority.get("fail") == 0 and authority.get("pass", 0) >= 5 else "FAIL", "proof": {"path": "assurance/CURRENT_AUTHORITY_ISOLATION_RECEIPT.json", "pass": authority.get("pass"), "fail": authority.get("fail")}},
    {"id": 18, "name": "duplicate-mechanic guard", "status": "PASS" if duplicate.get("status") == "PASS" and not duplicate.get("findings") else "FAIL", "proof": "assurance/DUPLICATE_MECHANIC_SCAN.json"},
    {"id": 19, "name": "contract/versioning checks", "status": "PASS" if all(test_ok(contract, x) for x in ["contracts.versioned", "contracts.breaking_gate", "contracts.version_fixtures", "structured.contract_version"]) else "FAIL", "proof": ["contracts.versioned", "contracts.breaking_gate", "contracts.version_fixtures", "structured.contract_version"]},
]
extra = {
    "deferredSetPreserved": deferred_preservation.get("coreDeferredObligationsUnchanged") is True and deferred_guard.get("status") == "PASS",
    "browserPortable": portability.get("codexInternalPathRequired") is False and portability.get("lockfileValidation", {}).get("status") == "PASS",
    "stackStatus": runtime.get("stackStatus"),
    "ownerAccepted": False,
}
overall = all(x["status"] == "PASS" for x in mandatory) and all([extra["deferredSetPreserved"], extra["browserPortable"], extra["stackStatus"] == "STACK_NOT_FROZEN"])
dump("assurance/AUTOMATED_TEST_RECEIPTS.json", {
    "schemaVersion": 2,
    "status": "ALL_BOUNDED_GATES_PASS" if overall else "GATE_FAILURE",
    "mandatoryRegressionAssurance": mandatory,
    "summary": {"pass": sum(x["status"] == "PASS" for x in mandatory), "fail": sum(x["status"] != "PASS" for x in mandatory), "total": len(mandatory)},
    "extraHardGates": extra,
    "truthCeiling": "Executed bounded assurance only. Successor manifest is generated and then independently post-verified before handoff; no Owner acceptance or final-product completeness claim.",
})

corrections = [
    {"id": 1, "name": "W03 semantic ownership map", "status": "PASS", "receipt": "assurance/W03_SEMANTIC_OWNERSHIP_CORRECTION_RECEIPT.json", "proof": "69/318 preserved; bounded semantic routing corrected"},
    {"id": 2, "name": "Structured selection + clipboard seam", "status": "PASS", "receipt": "assurance/STRUCTURED_SELECTION_CLIPBOARD_EXTRACTION_MAP.json", "proof": "model Structured selection/clipboard and isolation tests"},
    {"id": 3, "name": "Generic ActionAvailability", "status": "PASS", "receipt": "assurance/ACTION_AVAILABILITY_POLICY_RECEIPT.json", "proof": "generic policy + presentation/preflight convergence"},
    {"id": 4, "name": "Writer scaffold relevance filter", "status": "PASS", "receipt": "assurance/WRITER_RELEVANCE_FILTER_RECEIPT.json", "proof": "38/38 including positive and negative relevance fixtures"},
    {"id": 5, "name": "Portable browser conformance", "status": "PASS", "receipt": "assurance/BROWSER_PORTABILITY_BOOTSTRAP_RECEIPT.json", "proof": "6/6 bounded flows; package-local default; no mandatory Codex path"},
    {"id": 6, "name": "Current authority / historical isolation", "status": "PASS", "receipt": "assurance/CURRENT_AUTHORITY_ISOLATION_RECEIPT.json", "proof": "5/5 intake guard; old stack/Production authority excluded"},
]
if not overall:
    for c in corrections:
        c["status"] = "GATE_FAILURE"
dump("assurance/SIX_CORRECTION_COMPLETION_REGISTER.json", {
    "schemaVersion": 2,
    "baseline": "v0.2.1",
    "successor": "v0.2.1a",
    "successorBaselineId": SUCCESSOR,
    "corrections": corrections,
    "deferredSetCount": 10,
    "deferredSetPreserved": extra["deferredSetPreserved"],
    "stackStatus": "STACK_NOT_FROZEN",
    "ownerAccepted": False,
    "frozen": False,
    "status": "READY_FOR_INDEPENDENT_FOUNDATION_REVIEW" if overall else "GATE_FAILURE",
})

dump("checkpoints/CURRENT_HIGH_LEVERAGE.json", {
    "baseline": SUCCESSOR,
    "scope": "BOUNDED_V0_2_1_REVIEW_HARDENING_ONLY",
    "status": "READY_FOR_INDEPENDENT_FOUNDATION_REVIEW_NOT_OWNER_ACCEPTED_NOT_FROZEN" if overall else "GATE_FAILURE",
    "outcomes": [
        "V0_2_1_VALUE_PRESERVED",
        "W03_SEMANTIC_OWNERSHIP_HARDENED",
        "W03_69_318_TRACEABILITY_PRESERVED",
        "STRUCTURED_SELECTION_CLIPBOARD_EXECUTABLE",
        "ACTION_AVAILABILITY_GENERIC_POLICY_PROVEN",
        "WRITER_DEFERRED_RELEVANCE_FILTER_PROVEN",
        "BROWSER_CONFORMANCE_PORTABLE",
        "CURRENT_AUTHORITY_INTAKE_ISOLATED",
        "OLD_PRODUCTION_AUTHORITY_EXCLUDED",
        "CENTRAL_REUSE_PRESERVED",
        "INTERNAL_SIMULATION_CAUSAL_PATH_PRESERVED",
        "HIGH_VALUE_DEFERRED_SET_PRESERVED",
        "STACK_NOT_FROZEN",
        "NOT_OWNER_ACCEPTED",
        "NOT_FROZEN",
    ],
    "proof": {
        "model": {"pass": model.get("pass"), "fail": model.get("fail")},
        "contract": {"pass": contract.get("pass"), "fail": contract.get("fail")},
        "writerScaffold": {"pass": scaffold.get("pass"), "fail": scaffold.get("fail")},
        "w03Semantic": w03.get("summary"),
        "authority": {"pass": authority.get("pass"), "fail": authority.get("fail")},
        "deferredBoundary": {"pass": deferred_guard.get("pass"), "fail": deferred_guard.get("fail")},
        "browser": {"executionStatus": browser.get("executionStatus"), **browser.get("summary", {})},
    },
    "owner_accepted": False,
    "stack_frozen": False,
    "deployed": False,
    "released": False,
})

# Diff is computed after final assurance/checkpoint registers are written so their hashes are captured.
before, after = file_map(BASELINE), file_map(ROOT)
rows = []
for relative in sorted(before.keys() | after.keys()):
    old, new = before.get(relative), after.get(relative)
    old_hash, new_hash = digest(old) if old else None, digest(new) if new else None
    if old_hash == new_hash:
        continue
    status = "ADDED" if old is None else "DELETED" if new is None else "MODIFIED"
    rows.append({
        "path": relative,
        "status": status,
        "baselineBytes": old.stat().st_size if old else None,
        "candidateBytes": new.stat().st_size if new else None,
        "baselineSha256": old_hash,
        "candidateSha256": new_hash,
    })

dump("assurance/CHANGED_FILE_REGISTER.json", {
    "schemaVersion": 2,
    "scope": "BOUNDED_V0_2_1_TO_V0_2_1A_REVIEW_HARDENING",
    "verifiedBaselineZip": {
        "filename": "CEP_FOUNDATION_FORGE_v0.2.1_BOUNDED_FOUNDATION_CORRECTION_CANDIDATE.zip",
        "bytes": 3529607,
        "sha256": "523b596073920b7d2059e72bc9fe0fa718efd6ab14de7dcaf1441330f60dfc75",
        "candidateId": "ffb72c41e1a0cea2d3b2ef737675d47171a3f830dd50889d37a8dfb9cc55cede",
        "verifiedBeforeMutation": True,
    },
    "excludedGeneratedIdentityFiles": sorted(EXCLUDED_FROM_DIFF),
    "summary": {
        "added": sum(r["status"] == "ADDED" for r in rows),
        "modified": sum(r["status"] == "MODIFIED" for r in rows),
        "deleted": sum(r["status"] == "DELETED" for r in rows),
        "total": len(rows),
        "profilePathsChanged": sum(r["path"].startswith("profiles/") for r in rows),
    },
    "files": rows,
})

print(json.dumps({"overall": "PASS" if overall else "FAIL", "mandatory": len(mandatory), "changedFiles": len(rows), "profilesChanged": sum(r["path"].startswith("profiles/") for r in rows)}, indent=2))
if not overall:
    raise SystemExit(1)
