#!/usr/bin/env python3
from pathlib import Path
import hashlib,json,posixpath,re,subprocess
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1];DIST=ROOT/'dist';OUT=ROOT/'assurance'/'W6_CONTROLLER_NOTES_INTEGRATION';OUT.mkdir(parents=True,exist_ok=True)
PAT1=re.compile(r"(?:import|export)\s+(?:[^'\"]+?\s+from\s+)?['\"](\.{1,2}/[^'\"]+)['\"]");PAT2=re.compile(r"import\(\s*['\"](\.{1,2}/[^'\"]+)['\"]\s*\)")
def specs(s):return list(dict.fromkeys(PAT1.findall(s)+PAT2.findall(s)))
def resolve(rel,spec):return posixpath.normpath(posixpath.join(posixpath.dirname(rel),spec))
def graph(entry='main.js'):
 seen=set();order=[]
 def walk(rel):
  if rel in seen:return
  seen.add(rel);src=(DIST/rel).read_text()
  for sp in specs(src):walk(resolve(rel,sp))
  order.append(rel)
 walk(entry);return [{'rel':r,'source':(DIST/r).read_text(),'deps':[{'spec':sp,'dep':resolve(r,sp)} for sp in specs((DIST/r).read_text())]} for r in order]
def identity():
 code="import {canonicalSourceIdentity} from './tools/source-tree-identity.mjs'; const x=await canonicalSourceIdentity(new URL('file://' + process.cwd().replaceAll('\\\\','/') + '/')); console.log(JSON.stringify({sha256:x.sha256,files:x.files}))"
 return json.loads(subprocess.check_output(['node','--input-type=module','-e',code],cwd=ROOT,text=True).strip())
def html():
 h=(DIST/'index.html').read_text()
 for href,name in [('foundation/donor.css','donor'),('foundation/extensions.css','extensions'),('foundation/global/tokens/scale.css','scale')]:
  p=DIST/href;css=p.read_text() if p.exists() else '';h=re.sub(rf'<link rel="stylesheet" href="{re.escape(href)}">',f'<style data-inline="{name}">{css}</style>',h,flags=re.I)
 return re.sub(r'<script type="module" src="main\.js"></script>','',h,flags=re.I)
HTML=html();MODULES=graph();errors=[];steps=[]
def ok(id,detail):steps.append({'id':id,'status':'PASS','detail':detail})
def assert_(c,m):
 if not c:raise AssertionError(m)
with sync_playwright() as p:
 b=p.chromium.launch(headless=True,executable_path='/usr/bin/chromium',args=['--no-sandbox']);ctx=b.new_context(viewport={'width':1440,'height':980},reduced_motion='reduce');page=ctx.new_page();page.set_default_timeout(8000);page.on('pageerror',lambda e:errors.append(str(e)))
 page.set_content(HTML,wait_until='domcontentloaded');page.evaluate("()=>history.replaceState({},'', 'about:blank?surface=library')")
 entry=page.evaluate("""mods=>{const urls={};for(const m of mods){let src=m.source;for(const d of m.deps)src=src.split(d.spec).join(urls[d.dep]);urls[m.rel]=URL.createObjectURL(new Blob([src],{type:'text/javascript'}));}return urls['main.js']}""",MODULES);page.evaluate("u=>import(u)",entry);page.wait_for_function("()=>window.CEPFoundation?.consumer==='library'&&window.CEPBlueprint")
 base=page.evaluate("""()=>({desc:CEPFoundation.noteRuntime?.descriptor(),notes:Object.keys(CEPBlueprint.state.notes),adapters:CEPFoundation.noteRuntime?.adapters.size,owners:{binding:CEPFoundation.noteRuntime?.bindingOwner.owner,window:CEPFoundation.noteRuntime?.windowOwner.owner},hist:CEPBlueprint.state.notes['note-001'].working.historyProjectionOwner,bindingOwner:CEPBlueprint.state.notes['note-001'].binding.canonicalOwner,windowOwner:CEPBlueprint.state.notes['note-001'].window.canonicalOwner})""")
 assert_(base['desc'] and base['desc']['semanticOwner'] is False,'composition missing or semantic owner');assert_(base['adapters']==len(base['notes']),'fixture adapter count mismatch');assert_(base['owners']['binding']=='NoteBindingAdapter' and base['owners']['window']=='StickyNoteWindowOwner','canonical owners missing');assert_(base['hist']=='StructuredTransactionHistoryRecoveryOwner','note history mirror not canonical');ok('composition.owners',base)
 page.evaluate("()=>{globalThis.__noteAdapter=CEPFoundation.noteRuntime.adapter('note-001');globalThis.__noteBefore={doc:__noteAdapter.documentId,binding:JSON.stringify(__noteAdapter.bindingDescriptor()),content:JSON.stringify(__noteAdapter.snapshot()),adapter:__noteAdapter};CEPBlueprint.openNote('note-001',false)}");page.wait_for_selector('[data-note-id="note-001"]:not([hidden])')
 edit=page.locator('[data-note-id="note-001"] [data-block-id="note-001-p1"] .blockbody[data-editable-block]').first;assert_(edit.count()==1,'note block editor missing')
 edit.fill('Controller integration TCP/IP');page.locator('[data-note-id=\"note-001\"] .note-title-row').click();page.wait_for_timeout(100)
 after=page.evaluate("""()=>({html:CEPFoundation.noteRuntime.adapter('note-001').snapshot().blocks[0].html,local:CEPBlueprint.state.notes['note-001'].working.blocks[0].html,tx:CEPFoundation.noteRuntime.adapter('note-001').transactionDescriptor(),history:CEPBlueprint.state.notes['note-001'].working.history.length})""")
 assert_('Controller integration' in after['html'] and after['html']==after['local'],'UI edit did not converge to canonical document');assert_(after['tx']['canUndo'] and after['history']==after['tx']['historyLength'],'history mirror mismatch');ok('content.ui-edit-canonical',after)
 page.evaluate("()=>CEPBlueprint.undo('note:note-001')");u=page.evaluate("()=>CEPFoundation.noteRuntime.adapter('note-001').snapshot().blocks[0].html");assert_('Controller integration' not in u,'canonical undo failed');page.evaluate("()=>CEPBlueprint.redo('note:note-001')");r=page.evaluate("()=>CEPFoundation.noteRuntime.adapter('note-001').snapshot().blocks[0].html");assert_('Controller integration' in r,'canonical redo failed');ok('history.undo-redo',{'undo':u[:60],'redo':r[:60]})
 before_window=page.evaluate("()=>structuredClone(CEPFoundation.noteRuntime.windowOwner.window('note-001'))");page.evaluate("()=>CEPBlueprint.togglePin('note-001')");pin=page.evaluate("()=>({canonical:CEPFoundation.noteRuntime.windowOwner.window('note-001').pinned,mirror:CEPBlueprint.state.notes['note-001'].window.pinned,html:CEPFoundation.noteRuntime.adapter('note-001').snapshot().blocks[0].html})");assert_(pin['canonical']==pin['mirror'] and pin['canonical']!=before_window['pinned'],'pin did not delegate');assert_('Controller integration' in pin['html'],'pin mutated content');ok('window.pin-presentation-only',pin)
 win=page.locator('[data-note-id="note-001"]');win.focus();page.keyboard.press('Alt+ArrowRight');geom=page.evaluate("()=>({canonical:CEPFoundation.noteRuntime.windowOwner.window('note-001').geometry,mirror:CEPBlueprint.state.notes['note-001'].window,content:CEPFoundation.noteRuntime.adapter('note-001').snapshot().blocks[0].html})");assert_(geom['canonical']['x']==geom['mirror']['x'],'keyboard geometry mirror drift');assert_('Controller integration' in geom['content'],'geometry mutated content');ok('window.keyboard-canonical',geom['canonical'])
 page.evaluate("()=>{CEPBlueprint.requestNoteClose('note-001',null);if(CEPBlueprint.state.transient.pendingNoteClose)CEPBlueprint.closeNoteWith('discard')}");hidden=page.evaluate("()=>({life:CEPFoundation.noteRuntime.windowOwner.window('note-001').lifecycle,content:JSON.stringify(CEPFoundation.noteRuntime.adapter('note-001').snapshot()),binding:JSON.stringify(CEPFoundation.noteRuntime.adapter('note-001').bindingDescriptor()),same:CEPFoundation.noteRuntime.adapter('note-001')===globalThis.__noteAdapter})");assert_(hidden['life']=='hidden' and hidden['same'],'hide replaced adapter');page.evaluate("()=>CEPBlueprint.openNote('note-001',false)");reopen=page.evaluate("()=>({life:CEPFoundation.noteRuntime.windowOwner.window('note-001').lifecycle,doc:CEPFoundation.noteRuntime.adapter('note-001').documentId,binding:JSON.stringify(CEPFoundation.noteRuntime.adapter('note-001').bindingDescriptor()),content:JSON.stringify(CEPFoundation.noteRuntime.adapter('note-001').snapshot()),same:CEPFoundation.noteRuntime.adapter('note-001')===globalThis.__noteAdapter})");assert_(reopen['life']=='open' and reopen['same'] and reopen['doc']==page.evaluate('()=>__noteBefore.doc'),'reopen identity drift');assert_(reopen['binding']==hidden['binding'] and reopen['content']==hidden['content'],'hide/reopen changed binding/content');ok('lifecycle.hide-reopen-identity',reopen)
 page.evaluate("()=>CEPBlueprint.popoutNote('note-001')");pop=page.evaluate("()=>({platform:CEPFoundation.noteRuntime.windowOwner.window('note-001').platform.separateWindow,doc:CEPFoundation.noteRuntime.adapter('note-001').documentId,same:CEPFoundation.noteRuntime.adapter('note-001')===globalThis.__noteAdapter,content:JSON.stringify(CEPFoundation.noteRuntime.adapter('note-001').snapshot())})");assert_(pop['platform']['requestStatus']=='UNAVAILABLE' and pop['platform']['active'] is False,'popout fabricated capability');assert_(pop['same'] and pop['doc']==reopen['doc'] and pop['content']==reopen['content'],'popout changed adapter/content');ok('platform.popout-unavailable',pop)
 count=page.evaluate("()=>({adapters:CEPFoundation.noteRuntime.adapters.size,notes:Object.keys(CEPBlueprint.state.notes).length,uniqueDocs:new Set([...CEPFoundation.noteRuntime.adapters.values()].map(x=>x.documentId)).size,commands:CEPBlueprint.inspect().runtime.commands.filter(x=>x.surface==='note:note-001'&&x.command.startsWith('history.')).slice(-4)})");assert_(count['adapters']==count['notes'] and count['uniqueDocs']==count['adapters'],'duplicate note/document publication');assert_(any(x.get('owner')=='StructuredTransactionHistoryRecoveryOwner' for x in count['commands']),'history receipt not canonical');ok('identity.no-duplicate-runtime',count)
 if errors:raise RuntimeError('PAGE_ERRORS:'+json.dumps(errors,ensure_ascii=False))
 shot=OUT/'W6_CONTROLLER_NOTES_INTEGRATION.png';page.screenshot(path=str(shot),full_page=False);ctx.close();b.close()
idn=identity();receipt={'schemaVersion':1,'kind':'W6_CONTROLLER_NOTES_INTEGRATION_BROWSER_PROOF','classification':'CONTROLLER_FINAL_W6_CONVERGENCE_EVIDENCE','status':'PASS','sourceCanonicalTreeSha256':idn['sha256'],'canonicalSourceFileCount':idn['files'],'steps':steps,'pageErrors':errors,'artifacts':{'screenshot':{'path':'assurance/W6_CONTROLLER_NOTES_INTEGRATION/W6_CONTROLLER_NOTES_INTEGRATION.png','bytes':shot.stat().st_size,'sha256':hashlib.sha256(shot.read_bytes()).hexdigest()}}}
(OUT/'W6_CONTROLLER_NOTES_INTEGRATION_BROWSER_PROOF.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'status':'PASS','steps':len(steps),'source':idn,'screenshotBytes':shot.stat().st_size},ensure_ascii=False,indent=2))
