import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import net from 'node:net';
const require=createRequire(import.meta.url);
const {chromium}=require('playwright');
const root='/workspaces/cep-writer-baseline-repo/';
const freePort=()=>new Promise(res=>{const s=net.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>res(p))})});
const port=await freePort();
const server=spawn(process.execPath,[root+'tools/serve.mjs','--port',String(port)],{cwd:root,stdio:'ignore'});
const b=await chromium.launch();const ctx=await b.newContext({viewport:{width:1505,height:1045}});
const page=await ctx.newPage();
page.on('console',m=>console.log('CONSOLE',m.type(),m.text().slice(0,400)));
page.on('pageerror',e=>console.log('PAGEERROR',String(e.message).slice(0,800)));
page.on('requestfailed',r=>console.log('REQFAIL',r.url(),r.failure()?.errorText));
await page.goto(`http://127.0.0.1:${port}/?surface=learn`,{waitUntil:'networkidle'});
await page.waitForTimeout(3000);
console.log('CEPFoundation?',await page.evaluate(()=>typeof window.CEPFoundation));
console.log('body consumer',await page.evaluate(()=>document.body.dataset.consumer||''));
console.log('left', (await page.evaluate(()=>document.querySelector('#leftPane .pbody')?.innerText||'')).slice(0,500));
await b.close();server.kill();
